### ISSUE TITLE
Scope telephone poll of CA residents

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/health#102]
The goal is to get more information about those that are eligible for CalFresh but not enrolled, and the pain points or blockers they face.

The approach would be something like:
- Call CA residents broadly defined (no geographic or demographic segmenting)
- Screen based on their household income, which we will use as a proxy for eligibility. Those that fall above the threshold will be ineligible to "complete" the poll, and we will thank them and hang up.
- For those that are "eligible" we will ask if they are currently enrolled in CalFresh.
- If yes, we will ask a short poll about their experience and pain points.
- If no, we will ask a short poll about pain points and blockers.

A quote for a poll that meets this outline, that calls as many households as necessary to obtain 100 "completes" falls below the polling firm's minimum cost, which is $1,000.

**Comment by daguar** [comment]
Did we get a ballpark cost estimate on this?

**Comment by alanjosephwilliams** [comment]
^^ $1k

**Comment by daguar** [comment]
Okay cool, I thought this was written before calling and that was your estimate of the cost. Thanks!
