### ISSUE TITLE
Staff meeting updates — 1/22

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#103]
- Who wants to do?
- What are the updates?

**Comment by alanjosephwilliams** [comment]
I'll do the updates, as mentioned in Slack.

From @RebeccaCoelius 
- Reminder to help us hire for Will's Horizontal Integration Lead (let's touch base about some adjective to use to describe this person).
- HIPAA Training this afternoon (is it open to people?)
- Health & ED have 15 minutes deep dives next week. 


Other things to include? I think the results of The Talking and whatnot are appropriate content for the deep dive next week.
