### ISSUE TITLE
Talk proposal for Twilio conf 

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#107]
CFP just opened last week.

**Comment by daguar** [comment]
http://signal.twilio.com/call-for-presenters 
Closes Feb 20 but probably want to submit earlier rather than later.

Going to mention that I'll likely submit a talk in our meeting with Twilio tomorrow.

**Comment by daguar** [comment]
Erika @ Twilio today mentioned that she was planning on reaching out anyway to do this, so it seems like a lock!

**Comment by daguar** [comment]
cc @jaime-alexis to keep you in the loop on any updates to this

**Comment by Jaime-Alexis** [comment]
Great, deadline is fast approaching to submit speaker talk...we should
submit...i.e., Dave :)

--------------------------------------------------------------------------------------------------------------------------------
Jaime-Alexis Fowler | Director of Marketing | *Code for America*
<http://codeforamerica.org/> | p:*214.673.9060* | @JaimeAlexis
<http://www.twitter.com/JaimeAlexis>

*Bring the Code for America Fellowship to your city in 2016. Learn how.
<http://www.codeforamerica.org/governments/fellowship/>*

**Comment by daguar** [comment]
Emailed Erika; will draft when I hear back from her. Moving into "Ready" until I hear back; deadline is Feb 20th, and sounds like they're really down for us to talk, so should be fine.

**Comment by daguar** [comment]
Gonna do this this week, since deadline is Feb 20th.

**Comment by Jaime-Alexis** [comment]
Great!

--------------------------------------------------------------------------------------------------------------------------------
Jaime-Alexis Fowler | Director of Marketing | *Code for America*
<http://codeforamerica.org/> | p:*214.673.9060* | @JaimeAlexis
<http://www.twitter.com/JaimeAlexis>

*Bring the Code for America Fellowship to your city in 2016. Learn how.
<http://www.codeforamerica.org/governments/fellowship/>*

**Comment by daguar** [comment]
Talk submitted and Erika pinged with description for any feedback

**Comment by daguar** [comment]
Chatted with the Twilio conference folks last Thursday; after our chat, they suggested I also be on a panel session called "Selling the value of innovation." The big message/tactic I'll be focused on is just elevating the on-the-ground experience to the top, with examples and sub-tactics.

**Comment by Jaime-Alexis** [comment]
Great!

--------------------------------------------------------------------------------------------------------------------------------
Jaime-Alexis Fowler | Director of Marketing | *Code for America*
<http://codeforamerica.org/> | p:*214.673.9060* | @JaimeAlexis
<http://www.twitter.com/JaimeAlexis>

*Bring the Code for America Fellowship to your city in 2016. Learn how.
<http://www.codeforamerica.org/governments/fellowship/>*
