### ISSUE TITLE
Consider proposing a talk at RailsConf

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#111]
Suggested by @jaime-alexis and (I think?) @migurski. This is a stub/tracking issue. Deadline Feb 6: http://rubycentral-cfp.herokuapp.com/events/railsconf-2015

**Comment by lippytak** [comment]
@daguar chose not to do this?

**Comment by daguar** [comment]
Roger — not a big tie-in with any of the tracks, and I didn't have a particularly compelling idea for a proposal.

RubyConf may be a better fit for a talk, and if the aim is fellow recruitment, I could potentially attend RailsConf and do a booth or something (I think Erica did this last year).

**Comment by Jaime-Alexis** [comment]
Dave, let's chat. We're moving away from booth stuff as it's a) expensive
and b) doesn't seem to get us much in terms of recruitment. We seem to get
a lot more out of speaking.

Maybe you and I can spend a few minutes brainstorming some speaking ideas?

--------------------------------------------------------------------------------------------------------------------------------
Jaime-Alexis Fowler | Director of Marketing | *Code for America*
<http://codeforamerica.org/> | p:*214.673.9060* | @JaimeAlexis
<http://www.twitter.com/JaimeAlexis>

*Bring the Code for America Fellowship to your city in 2016. Learn how.
<http://www.codeforamerica.org/governments/fellowship/>*

**Comment by daguar** [comment]
@Jaime-Alexis: Makes sense — the deadline is passed for RailsConf (see above) but I think targeting some Ruby conferences with a talk that makes sense for their track(s) would be great.

I could also see some applied content (like, we had X social impact and we did it in Ruby) that makes its rounds in the Ruby e-sphere (Twitter, some email lists) being good.

(cc @danhon as well, because it's related to an idea I put up last week where he mentioned a how-to potentially being useful.)
