### ISSUE TITLE
SF partnership agreement

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#112]
Rebecca will send draft MOUs/partnership agreement/LOS or whatever first

**Comment by RebeccaCoelius** [comment]
@lippytak did Meghan ever send these to you?

**Comment by lippytak** [comment]
Yea sorry this fell off my radar. Just spoke to Liliana and Tiana and they're both ready for drafts. I'll try to get first drafts out the door next week. @rebeccacoelius let me know if you have specific deadlines or if I should prioritize this sooner.

**Comment by lippytak** [comment]
Next step: Draft partnership agreements for SF FB and SF HSA.

**Comment by RebeccaCoelius** [comment]
No hard deadlines on my end, but shoot me the draft when its started and I
can help. @lippytak

Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by lippytak** [comment]
Kinda getting there in a roundabout way...

Draft of FB <> CfA thing: https://docs.google.com/a/codeforamerica.org/document/d/19eQAfXVftpKgA5tT-li8knCNyAQNQSPt-mRGwY4UTY4/edit

Draftish of CfA <> County thing (more proposal, not partnership): https://docs.google.com/a/codeforamerica.org/document/d/10cxPzULmG9JbW-DEXI_Wjd1NtwKOhk5q0JptI9fjY0Y/edit

**Comment by lippytak** [comment]
Draft of FB <> CfA <> HSA partnership thing: https://docs.google.com/a/codeforamerica.org/document/d/1FJExRI7R67clOYN5_hQPklw_ECWVibKbUkdR2aPd1nA/edit#

**Comment by lippytak** [comment]
Draft sent to Tiana so we can chat at lunch

**Comment by lippytak** [comment]
Draft/agenda sent. Will meet 4pm Mon to review/sign and work on MOU for CalWIN read access.

**Comment by lippytak** [comment]
Waiting for folks to sign.
