### ISSUE TITLE
Staff meeting updates — 1/29

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#113]
@lippytak you wanna take a turn?

**Comment by lippytak** [comment]
Sure! @RebeccaCoelius and @daguar please do a quick dump of things here and I'll give a quick summary.

**Comment by RebeccaCoelius** [comment]
- Fellows are now all HIPAA trained up! We can start sharing PHI next week as we onboard them to the Aptible dev environment., but don't encourage city partners until there is a reason to use the data. 
- Rebecca at New Partners for Smart Growth and HHS tech conference in Baltimore and DC Fri-Tues, if there is somebody she needs to meet there Slack her

**Comment by lippytak** [comment]
- starting Clean outreach
- sick!
- putting Molly's WA teardown
- talked to PA user
  - Applied in person, pretty easy, PA
  - Balance doing her annual renewal

**Comment by lippytak** [comment]
Closed and onto the next https://github.com/codeforamerica/health/issues/114
