### ISSUE TITLE
Staff meeting updates — 2/5

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#114]
Back to @alanjosephwilliams (to continue the round robin approach if my memory serves).

**Comment by daguar** [comment]
I think it's Rebecca this time?

**Comment by lippytak** [comment]
@alanjosephwilliams feel free to reassign if @daguar speaks the truth!

**Comment by alanjosephwilliams** [comment]
It does feel like I did updates last week, soooo reassigning :)

**Comment by RebeccaCoelius** [comment]
YRP

On Thursday, January 29, 2015, Alan Joseph Williams <
notifications@github.com> wrote:

> It does feel like I did updates last week, soooo reassigning :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/114#issuecomment-72127956>
> .
>


-- 
Rebecca Coelius, MD
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by daguar** [comment]
Am I right that we are also presenting Health Lab stuff this week? (since we didn't have time last week?) If so, this is just a flag for someone to F/U with Gabrielle to make sure she knows.

**Comment by RebeccaCoelius** [comment]
No it needs to be scheduled, feel free to email her and coordinate date
that works well for three of you

On Monday, February 2, 2015, Dave Guarino <notifications@github.com> wrote:

> Am I right that we are also presenting Health Lab stuff this week? (since
> we didn't have time last week?) If so, this is just a flag for someone to
> F/U with Gabrielle to make sure she knows.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/114#issuecomment-72583336>
> .
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by alanjosephwilliams** [comment]
Seems like Lab updates might be:
- We are going into sales mode on Clean. If you have friends in the direct service / non-profit world, send them our way.
- Interesting thing of the week to externalize to CfA: with the help of the CalFresh director, we surveyed the front-line eligibility workers at SF HSA. We received a ton of interesting and in-depth responses.

**Comment by daguar** [comment]
+1 to mentioning the EW survey — it's been really great.

The other that comes to mind to me:
- We discovered a systemwide problem in Twilio that they didn't even know about before we told them

(I thought it was cool :P )
