### ISSUE TITLE
Add better Arizona keyword

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#122]
Right now AZ is getting away with a ton of undetected downtime! So sneaky...

UP looks like this:
![az-up](https://cloud.githubusercontent.com/assets/2533112/6036070/fbfea8fe-abf3-11e4-85e1-e0d8542ce480.png)

Down looks like this:
![screen shot 2015-02-03 at 10 27 38 pm](https://cloud.githubusercontent.com/assets/2533112/6036071/ff95404a-abf3-11e4-89e6-9a31beab290f.png)

So we need to look for some content around that 'get started' button.

**Comment by daguar** [comment]
Well, fuck that noise. Let's get these suckas.

**Comment by daguar** [comment]
PS should this be in /health???

**Comment by lippytak** [comment]
NOPE https://github.com/codeforamerica/snap-it-up/issues/22
