### ISSUE TITLE
CodeAcross writeup eligibility screener thang

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#123]
Draft by tomorrow midday

**Comment by daguar** [comment]
Changed name to "eligibility screener"

**Comment by lippytak** [comment]
:+1:

**Comment by lippytak** [comment]
SMS stood for 'Some Memorable Screener' don't worry I would never impose an arbitrary communication medium!

**Comment by lippytak** [comment]
NMP (anymore!)
