### ISSUE TITLE
Process and circulate summary of EW surveys

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#125]
There's some amazing stuff coming in...

Let's process + circulate summary. We could share the summary with Solano/Napa as a nudge if they don't circulate soon.

Also let's consider inviting SF EWs who responded over for lunch or something.

**Comment by alanjosephwilliams** [comment]
The current survey results are summarized in the wiki. Closing this issue for now, and we can open new issues for soliciting and summarizing responses from Napa & Solano.

**Comment by lippytak** [comment]
Link: https://github.com/codeforamerica/health/wiki/Eligibility-Worker-Research-(Feb-2015)

@ajw I deleted the qualitative responses as we didn't tell folks it would be public but copied them into ew_responses.md in `Research/EW surveys` in DB.

**Comment by daguar** [comment]
Can we please use the private GitHub repo for sensitive stuff? (Especially if it's a Markdown file?)

I find Dropbox to be terribly unwieldy. I'd really love to only store files we HAVE TO over there (like Powerpoint prezos, movies, audio, Illustrator assets.)

I think I've mentioned this before, but I'd like to see our prioritization of "where to put shit" be:
1. GitHub
2. Google Drive
3. Dropbox

(And each should only be if we _really_ have some pain with GitHub, ideally.)

That okay?

To that end:
- I moved the EW qualitative results to the private repo
- I linked to those results from the public wiki

**Comment by alanjosephwilliams** [comment]
We can discuss further in person, but I simply don't agree that this should
be considered sensitive to this extent. We solicited responses as
anonymous, but also advertised that we would deliver results back to
respondents. Obviously there is nothing lost in this *particular case* by
keeping things behind a private repo, but in general I wan't to make as
much of our research as publicly viewable as possible.

On Mon, Feb 9, 2015 at 3:40 PM, Dave Guarino <notifications@github.com>
wrote:

> Can we please use the private GitHub repo for sensitive stuff? (Especially
> if it's a Markdown file?)
>
> I find Dropbox to be terribly unwieldy. I'd really love to only store
> files we HAVE TO over there (like Powerpoint prezos, movies, audio,
> Illustrator assets.)
>
> I think I've mentioned this before, but I'd like to see our prioritization
> of "where to put shit" be:
> 1. GitHub
> 2. Google Drive
> 3. Dropbox
>
> (And each should only be if we *really* have some pain with GitHub,
> ideally.)
>
> That okay?
>
> To that end:
>
>    - I moved the EW qualitative results to the private repo
>    - I linked to those results from the public wiki
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/125#issuecomment-73615306>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by alanjosephwilliams** [comment]
Enjoyed our post-mortem on this topic in Slack. We are all on the same page—which looks like what @daguar has captured here and agreement that the EW responses are suited for the private repo until further preparation for public consumption.
