### ISSUE TITLE
Staff meeting updates

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#129]
Order:
- Rebecca
- Jake
- Alan
- Dave
- Rebecca (etc etc)

Once you do one week, reassign the issue to the next person.

**Comment by daguar** [comment]
Sure. Please put updates here folks!

**Comment by lippytak** [comment]
- Great Sacramento working meeting with CDSS around procurement project
- Visited with West Sac fellows, who are being treated like royalty
- Our teammate at HSA got yelled at and kinda intimidated by bosses bosses, which has been BIG challenge
- One application crash resulted in a client having to go around the city trying to deliver paperwork, so we  gave her a $50 gift card to remedy and created the official Crash to Cash program (images below)
- 41 submitted, 17 approved CalFresh apps so far. Aiming for ~50 approved by end of Feb.

![crash-to-cash](https://cloud.githubusercontent.com/assets/2533112/6175889/4c026360-b2af-11e4-9e06-ffdb3c9d4077.jpg)

**Comment by lippytak** [comment]
@alanjosephwilliams you're up for the 2/19

**Comment by RebeccaCoelius** [comment]
-Snow delayed but couldn't keep us from the Richmond Fellows! Dave and Rebecca had a great time eating BBQ, visiting with some of their city partners, and problem scoping. 
- Rebecca in NYC today working on potential 2016 Health Fellowship. 
- Health page is up! We will be making many updates this month, Rebecca appreciates your feedback. codeforamerica/health.org

**Comment by lippytak** [comment]
Because we do this every week let's try leaving the issue open and just reassigning.

**Comment by daguar** [comment]
YO, hit me with them. I'll do them this week.

**Comment by RebeccaCoelius** [comment]
From last week: 
Snow delayed but couldn't keep us from the Richmond Fellows last week. 

Health page is up and other FA pages coming very soon. We will be making continous updates,  FA leads appreciate your feedback. 

We have a CTOs health and Safety and Justice pilot launching next week in Alameda County to help Victims of Violent Crime  This work is led by Spike of Urban Strategies

**Comment by RebeccaCoelius** [comment]
(Sorry) 
... And 2014 Fellow Fureigh.

**Comment by lippytak** [comment]
@RebeccaCoelius this week. My updates:
- 23 approved cases, 87 submitted
- One case successfully overturned (!!)
- One user in the wild - bug + personal phone call
- Maybe read an EW survey? Getting more in other counties?

**Comment by lippytak** [comment]
Unexpected uptick in EBTNearMe usage:
![screen shot 2015-03-05 at 10 00 01 am](https://cloud.githubusercontent.com/assets/2533112/6511066/1410f5cc-c31f-11e4-866c-68040280047b.png)

**Comment by RebeccaCoelius** [comment]
Finally making progress on earned revenue for the health team- ie the state contract! The smaller contract for the procurement related collaboration with the Content team should be finalized this month. For the larger $ amount for the CalFresh work, we've now engaged with two primary contractors that we would subcontract through. Thanks to revenue team and especially Matt Boitano for supporting this process. 

We will do a Open Referral deep dive in staff mtg in a few weeks, but in the meantime you should know that we are considering short term Product Resident candidates to improve the documentation of the Open Referral Standard (more accurately known as the human services data specification) and help us move it to a permanent steward. As previewed last week, an Open Referral pilot also launched this week in Alameda County. 

Rebecca will be in Chicago next week for '16 City Recruitment and other meetings, let me know if I can be helpful while there for any of your Chicago based projects.

**Comment by RebeccaCoelius** [comment]
Rebecca in Chicago for '16 Recruitment

**Comment by lippytak** [comment]
This week: Done! (Next time I want to report out something on uptime...maybe which social service sites are down right now?)

Next week: @alanjosephwilliams

**Comment by alanjosephwilliams** [comment]
Ok folks!

Open call for suggestions @lippytak @daguar @RebeccaCoelius 

Obviously I'll mention:
- Our metrics
- @RebeccaCoelius is out and that her family is in our thoughts :(
- We need Spanish and Cantonese language assistance for client assistance.
- Super inspiring day at California Association of Food Banks conference.
- We are going to talk about StatusBoard publicly on April 1.

**Comment by daguar** [comment]
Big +1 to these, in particular the CTA of 3 and the 4 mention.

**Comment by daguar** [comment]
Drop 'em in here! (We'll finalize at the end of our noon spring review.)

**Comment by lippytak** [comment]
- State contract is official!
- AJW gave a sweet talk at Health Refactored about the state of social service websites
- Down to two finalist ED candidates
- Case follow up
  - Drug felons now qualify for CalFresh
  - Some eligibility workers don't think you can do a phone interview for CalFresh
  - The State website for CalFresh gives conflicting information about resource test
- Metrics: 47 approved cases, 60% approval rate but we did not hit our March goal of 75% approval rate

**Comment by alanjosephwilliams** [comment]
on the AJW talk front, the venues are:
- HealthRefactored - a design and health conf
- Etsy

On Thu, Apr 2, 2015 at 3:59 PM, Jake Solomon <notifications@github.com>
wrote:

>
>    - State contract is official!
>    - AJW gave a sweet talk at Health Refactored about the state of social
>    service websites
>    - Down to two finalist ED candidates
>    - Case follow up
>       - Drug felons now qualify for CalFresh
>       - Some eligibility workers don't think you can do a phone interview
>       for CalFresh
>       - The State website for CalFresh gives conflicting information
>       about resource test
>     - Metrics: 47 approved cases, 60% approval rate but we did not hit
>    our March goal of 75% approval rate
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/129#issuecomment-89026073>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by lippytak** [comment]
Done. @alanjosephwilliams up for 4/9.

**Comment by alanjosephwilliams** [comment]
- Visit to Sacramento tomorrow!
- Balance was down for 15 hours. Another Twilio platform error not reported by Twilio. Dave fixed it and reported it. We are going to set up monitoring for it.
- Doc Upload.
- Utah following week. Preparing for expansion
- FA are working with Communities & Content on first Community of Practice.
- OpenReferral Analyst working on the project. Improving the specification.

**Comment by daguar** [comment]
Let's get some updates in here! I think we've got some exciting ones from the work this week.

**Comment by daguar** [comment]
@RebeccaCoelius Tag! You're it!

**Comment by RebeccaCoelius** [comment]
nope, @lippytak because it will be 5am in Japan. I will take on two weeks in a row starting 5/7. 

My updates:
1. Finalists selected for 2016 Fellowships in Health. Great potential projects like user centered patient data access, helping schools participate in public health reporting systems, and connecting children and families with community resources. 
2.  Code for America hosted an event with Health 2.0 and the White House on Tuesday night educating local health technology entrepreneurs on important regulatory proposals, and collecting and encouraging public comment. Thanks to Dharmishta and Brielle for the help!
3. CfA supported the Multi Cities Innovation Challenge this year with Rebecca as a judge. 

ED:
1. An offer has been accepted for the Economic Development Lead! His name is Efrem Bycer, and he will be starting May 18th remotely, and here at CfA in early July. More info to come.

**Comment by daguar** [comment]
Ah, switching to @lippytak.

**Comment by lippytak** [comment]
Next up, @alanjosephwilliams

**Comment by alanjosephwilliams** [comment]
- Metrics our steady.
- Launched doc upload.
- Prep CBO survey which we hope to distribute with our new partners at The State.
- Meeting w Marin on Monday.
- Rebecca still out, she's back next week.

**Comment by RebeccaCoelius** [comment]
Health Lab CalFresh updates: 
- Our work is spreading: finalizing formal partnership with SF as core pilot partner, great meeting with Marin earlier this week and will launch that partnership soon 
- metrics are up (I assume this just means our applications are up to 157 submitted/72 approved?) @lippytak

- working w/ Content Team documenting our approach to researching and measuring bottleknecks in the CalFresh enrollment process, and how that approach could be relevant for other social services. This will both seed our first Health Community of Practice in SNAP, but also fulfill our first deliverable for the CA State contract.

Other Health FA stuff: 
- also related to state contract, we are working w/ Content team/Dharmishta to set up internal interviews around CDSS Procurement processes 

- Rebecca: doing follow up from an event that we co- hosted  with the Whtie House and Health 2.0 around a few proposed federal regulations of high interest to people working in health tech. Considering a future collaboration to increase participation in that community. 

- OpenReferral heads up: Code for America has been investing in opening up and making social services and referral data useful for many years now. We did this in the San Mateo Fellowship, by supporting the Ohana Team the year after the Fellowship with funding by the Knight Foundation, and will continue this vein of work in 2016 Fellowships but as a tactic for improving specific digital services. We are also currently supporting a pilot  in Alameda County, led by Fureigh and Steve Spiker, and have a fantastic data analyst  doing a two month sprint on the data specification. More on all that in an upcoming deep dive. 

Last year we also sponsored the development of OpenReferral, which was meant to be a community of practice around the tools we were developing. For a variety of reasons, some interpersonal but many strategic, we have recently  made the decision to organizationally separate from the OpenReferral Initiative. I know the brand has become deeply entangled in much of our work in this area and there is much to be done to make this a smooth transition. Please reach out to me during this process if you have any confusion about how to talk about this work or other questions.

**Comment by RebeccaCoelius** [comment]
I think its my turn since Dave went last week. Please add your updates here! @lippytak @daguar @ajw

**Comment by lippytak** [comment]
Best report ever
Grant FML

**Comment by RebeccaCoelius** [comment]
- Spending a lot of time with Jen, Kakul, Focus Area leads on our OKRs for this year. 
- Grant FML X2
- We are starting testing on  Vocatus, the prototype that makes it easier for people to request their medical records and for us to track the result of that request. Talk to me if you want to be involved!
- There is a summer health intern starting next week, Caroline Hayes. She will be focused on  user research for how to turn Market Match into a digital service in partnership with the Ecology Center, and supporting the W Sac team given her experience in connecting underserved communities with farmers markets. 
- Alameda County pilot on opening up resources data is progressing. Fureigh is continuing user research and is now actively prototyping the tool for victims of crime. Spike has completed most of the data analysis and is now hosting stakeholder conversations around how to change data collection practices and data structure. Estimate mid June for the start of publishing the data through modified Ohana API. 
- I'm in DC next Mon - Wed for Health Datapalooza.

**Comment by RebeccaCoelius** [comment]
I'll do this week since I"m about to miss two staff mtgs and a bunch of team member are out. 

Please add updates @lippytak @daguar @alanjosephwilliams

**Comment by daguar** [comment]
- USDA grant is submitted! Thanks for a heroic effort to Jessica and Matt for their help.

**Comment by RebeccaCoelius** [comment]
- hooray Caroline is here
- Rebecca just got back from Datapalooza. We launched the alpha for Vocatus.io while there as part of Data Independence Day. Vocatus is a very simple tool that makes it easy for a patient to request copies of their medical records in a digital format, and then follow up to help us measure the gaps between policy intention and the on the ground reality of patient access for those on public insurance.  Lots of interest so far, we are recruiting testers and would love to have staff members give it a try and provide feedback! 
- Also met with DC stakeholders for 2016 Fellowship while there. Matt is going to be a huge assett. 
- This is my last staff meeting for a few weeks as next thursday I head to spain to walk for two weeks to walk the El Camino with my Mom and 15 month old. This was planned three years ago when there was no Adelaide, so wish me luck carrying 25 pounds of wriggle across the country.

**Comment by alanjosephwilliams** [comment]
- Dave is automatin'
- AJW is conciergin'
- Jacobo is doing county onboarding
- Caroline is going to do some awesome research. we think its legal!
- Eff LA

**Comment by daguar** [comment]
I got today! Please hit me with any.

**Comment by daguar** [comment]
So far I have:

- Rebecca back online Friday
- In the process of onboarding a bunch of counties (Solano, Placer, Marin, Contra Costa)
- Mini-landmark: first app submitted via the legacy system programmatically 
- Launched a document upload feature

**Comment by daguar** [comment]
Ergh, edit — Rebecca back Monday

**Comment by daguar** [comment]
Done! Who's next?

**Comment by RebeccaCoelius** [comment]
I'll take it since I've been out!

On Thursday, June 25, 2015, Dave Guarino <notifications@github.com> wrote:

> Done! Who's next?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/129#issuecomment-115394240>
> .
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by lippytak** [comment]
- 48 CalFesh apps in the last week (down from 53 the prior week)
- Submitted our first automated case through the existing systems
- Some tough moments:
  - "No one has called.  I have received no letter.  I'm wondering if I have been scammed into giving my personal information...[later in the day] I have just found 15 postcards in Chinese and 24 postcards in English in my mailbox concerning CalFresh.  ?????? "
  - "my address is just temporary im homeless i go from house to house where i can shower and rest my head its hard"
- Big shout out to @alanjosephwilliams for bearing the brunt of the  stress on direct user support

**Comment by lippytak** [comment]
REBECCA BACK!

**Comment by RebeccaCoelius** [comment]
@lippytak @ajw @daguar updates please! don't stress too much as these are happening at the end of staff mtg today to allow ample time for reorg Qs.

**Comment by alanjosephwilliams** [comment]
- CDSS Deliverable #2
- "Utah Part Two" Next Week
- Setting ambitious goals for the Summit (1k Apps)?
- Alan is not yet automated, but progress continues.

**Comment by RebeccaCoelius** [comment]
Rebecca at precision med event all day yesterday- they need our help
bringing local health leaders to the table. Not just genetics-
environmental too, AddressIQ good example.



On Thursday, July 9, 2015, Alan Joseph Williams <notifications@github.com>
wrote:

>
>    - CDSS Deliverable #2 <https://github.com/codeforamerica/health/pull/2>
>    - "Utah Part Two" Next Week
>    - Setting ambitious goals for the Summit (1k Apps)?
>    - Alan is not yet automated, but progress continues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/129#issuecomment-120120653>
> .
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by RebeccaCoelius** [comment]
guessing this is me since you all are out, updates? @ajw @lippytak @daguar

**Comment by RebeccaCoelius** [comment]
Last week has been a lot of going deeper in the matrix, excited to talk about concrete work in the coming weeks. So far we've been working with Nicole on scoping a health community/content position, I'll be joining Garrett/Matthew in outreach to Long Beach to begin more seriously considering further investment in AddressIQ. 

Alameda County pilot to open up social services data, especially for victims of crime, has finished. You will hear about project  from Spike + Fureigh in staff mtg August 13th. 

SNAP team up in Sonoma getting massages and hanging out in the hot tub.  (fill in real work here) 

Health intern Caroline doing great research on user experience of existing CalFresh application process MBCW
- only 38% of those that start the online application actually submit an application in that sitting, and it takes them an average of 28 minutes (getcalfresh.org time is roughly a third of that)
-getting some great suggestions/reinforcement from users - "but you know what would be cool, if you could like snap a photo of your documents and then submit them that way...  (which is exactly what Dave built) 
- want to learn more, she's speaking July 30th at staff mtg!

**Comment by alanjosephwilliams** [comment]
Real work in Sonoma: 
- Race to 1000 applications begins (by the Summit). It's on Ducksboard.
- We are now submitting only automated applications in our partner counties.
- Food Bank in Contra Costa used GetCalFresh yesterday to enroll people in line at WIC. 
- Jake or Caroline should read something from the new "Feels" issue

**Comment by daguar** [comment]
My turn, hit me up with updates!

**Comment by alanjosephwilliams** [comment]
Race to 1000: We're at 259
Federal Gov't to Health Team: "You're not wrong"
Caroline is going to stay with us through the fall (our woman on the ground in the inland empire)
Jake is down under
---
"I am homeless staying at youth shelter trying to go back to school and hopefully find a job very soon and a stable life and a drug free life. and I don't have id card or birth certificate"
"My husband just lost his job and we are a month behind on rent, soon facing eviction."
" A nice an named Alan went beyond to help me get it sorted out. "

**Comment by RebeccaCoelius** [comment]
Rebecca is in jury duty. =(

Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by daguar** [comment]
@lippytak did this last week — who's up this one?

**Comment by RebeccaCoelius** [comment]
Dave or Alan! I might be late due to a lunch w/ the Director candidate.

Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by alanjosephwilliams** [comment]
I'll do it. Lay the updates on me

**Comment by lippytak** [comment]
The good: "I've been very pleasantly surprised at the fact that it was not
an ordeal. I was braced for that....what surprised me was that it was a
pleasant process as opposed to being a bummer."

The bad: "I currently live in a friend's garage, I have my own fridge and
supply my own food and beverage. I have a 98$ storage bill every month so
eating is kinda last on my plate. I do labor work when its available as
well.. anything will help me thank you."

506 apps

We asked one county not to submit a press release but they got so pumped
they did it anyway.

**Comment by alanjosephwilliams** [comment]
Good enough for me. Maybe also that we are cautiously stoked about hiring a new Director? and that we are stoked about Nicole's work recruiting great content & community candidates.

**Comment by RebeccaCoelius** [comment]
@daguar I think its your turn? 

My updates: 
-  We have our leading Health Director candidate coming in for finalist interviews next Tuesday. Thanks so those of you who have agreed to participate. We have several more great candidates still working through the process, but please continue to share out this opportunity!

-  Jenny and I have been working with Luke on bringing a second '16 Health Fellowship to the table, and its going incredibly well with nationally relevant scopes amenable to tech interventions, and strong partners. I leave it to him whether we want to reveal the sites. =) 

- working on health  budget projections which has meant a lot of product strategy and team growth conversations, thanks to everyone in Product, Rev Team, and Greg Johns for your support on that

**Comment by daguar** [comment]
I am not sure if we'll be back from the FB at 1 so can someone take it as backup?

**Comment by RebeccaCoelius** [comment]
I can do back up but plz still add updates

On Thursday, August 20, 2015, Dave Guarino <notifications@github.com> wrote:

> I am not sure if we'll be back from the FB at 1 so can someone take it as
> backup?
>
>
>
> > On Aug 20, 2015, at 10:11 AM, Rebecca Coelius <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > @daguar I think its your turn?
> >
> > My updates:
> >
> > We have our leading Health Director candidate coming in for finalist
> interviews next Tuesday. Thanks so those of you who have agreed to
> participate. We have several more great candidates still working through
> the process, but please continue to share out this opportunity!
> >
> > Jenny and I have been working with Luke on bringing a second '16 Health
> Fellowship to the table, and its going incredibly well with nationally
> relevant scopes amenable to tech interventions, and strong partners. I
> leave it to him whether we want to reveal the sites. =)
> >
> > working on health budget projections which has meant a lot of product
> strategy and team growth conversations, thanks to everyone in Product, Rev
> Team, and Greg Johns for your support on that
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/129#issuecomment-133081189>
> .
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by lippytak** [comment]
- Over 600 apps
- dc next week (White House and fns)
- two awesome inbounds via live chat (San Diego!!)
- **lots of good quotes in the 'feels' issue toconsider**

**Comment by RebeccaCoelius** [comment]
Plz add more context re the live chat thing? I saw that SD is now our
friend, don't get the chat part be I was out.

On Thursday, August 20, 2015, Jake Solomon <notifications@github.com> wrote:

> - Over 600 apps
> - dc next week (White House and fns)
> - two awesome inbounds via live chat (San Diego!!)
> - **lots of good quotes in the 'feels' issue toconsider**
>
>
> On Thursday, August 20, 2015, Rebecca Coelius <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > I can do back up but plz still add updates
> >
> > On Thursday, August 20, 2015, Dave Guarino <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> >
> > > I am not sure if we'll be back from the FB at 1 so can someone take it
> as
> > > backup?
> > >
> > >
> > >
> > > > On Aug 20, 2015, at 10:11 AM, Rebecca Coelius <
> > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>');>> wrote:
> > > >
> > > > @daguar I think its your turn?
> > > >
> > > > My updates:
> > > >
> > > > We have our leading Health Director candidate coming in for finalist
> > > interviews next Tuesday. Thanks so those of you who have agreed to
> > > participate. We have several more great candidates still working
> through
> > > the process, but please continue to share out this opportunity!
> > > >
> > > > Jenny and I have been working with Luke on bringing a second '16
> Health
> > > Fellowship to the table, and its going incredibly well with nationally
> > > relevant scopes amenable to tech interventions, and strong partners. I
> > > leave it to him whether we want to reveal the sites. =)
> > > >
> > > > working on health budget projections which has meant a lot of product
> > > strategy and team growth conversations, thanks to everyone in Product,
> > Rev
> > > Team, and Greg Johns for your support on that
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/codeforamerica/health/issues/129#issuecomment-133081189
> > >
> > > .
> > >
> >
> >
> > --
> > Rebecca Coelius, MD
> > Director of Health
> > Code for America
> > 415 298 2872
> > LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
> > Twitter <http://twitter.com/#!/RebeccaCoelius>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/codeforamerica/health/issues/129#issuecomment-133082623
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/129#issuecomment-133089990>
> .
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by RebeccaCoelius** [comment]
@daguar turn!

- Thanks to those who have interviewed Director of HHS candidates this past week. While there is one in particular we are pretty excited about, please still consider this open and tell the world!

(lots of transition/handoff stuff that I do think is worth discussing in staff meeting)

**Comment by alanjosephwilliams** [comment]
- Over 750 apps!
- Now, the "Flight to Quality"
- Hiring in motion on Content & Community, too. Big ups to Nicole!

**Comment by RebeccaCoelius** [comment]
from @lippytak 

Update! Nearing 800, on track to hit 1l goal. 60% approval slowly on the rise. Tell about uncovering the Documentation Devil. Tell about #govwins on Leo digging not into on demand interviews

**Comment by daguar** [comment]
A few for today:

- Client quote: "thank you I have never applied for anything with the Gov so this was TRULLY a blessing"
- We've surfaced that in one county, some workers were mailing clients paper applications and asking them to fill the whole thing out — armed with this data, we informed the Director (who didn't know) and she has said this will no longer happen (not just for our cases — for all)
- Discovered this week in Marin County, the top 2 help calls about the 39-county web site are: (1) people unable to figure out the confusing e-signature, and (2) people on iPhones — apparently clicking the "I agree" to legalese at the end just STRAIGHT UP DOESNT WORK on iPhones

**Comment by RebeccaCoelius** [comment]
- ST update
- grinch transfer
- Rev team/health pipeline, Greg Johns budgeting 
- thank you's

**Comment by daguar** [comment]
- Tears

**Comment by lippytak** [comment]
- ST verbal accept
- Stakeholder explosion, into threatened vendor plasma layer
- 1K IS GOING TO BE CLOSE!!

**Comment by lippytak** [comment]
Didn't get FNS grant :(

**Comment by lippytak** [comment]
Touring + Onboarding San Diego County
![img_3459](https://cloud.githubusercontent.com/assets/2533112/10372068/0c7a6808-6d9b-11e5-9810-9c2b06756262.jpeg)

![2015-10-08 08 53 30](https://cloud.githubusercontent.com/assets/2533112/10372078/17688d8a-6d9b-11e5-93ce-09ddc0e41da3.jpg)

- https://twitter.com/allafarce/status/652133840673046528
- https://twitter.com/lippytak/status/651602060496891904
