### ISSUE TITLE
Kill health@ email list

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#131]
Then @RebeccaCoelius will send an email to staff FYIing

**Comment by lippytak** [comment]
Looks like @jmadans is the owner. Jack can you delete this group and give @RebeccaCoelius a heads up when you do? Instructions: https://support.google.com/groups/answer/2646833?hl=en

**Comment by alanjosephwilliams** [comment]
I'm pretty sure we killed it. closing unless someone challenges.
