### ISSUE TITLE
Talking points

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/health#134]
Impetus is a potential Health Refactored interview, but its a general need. We have cultivated a lot of content with the Health Page, now let's distill it down into conversational pieces. @RebeccaCoelius I am assigning you because I think you are both best suited and have the most experience talking about the work to uninitiated audiences—but we should all review and contribute.

**Comment by alanjosephwilliams** [comment]
This conversation is going to happen Wed 2/25. I'll draft some initial thoughts for us to review on Monday.

**Comment by RebeccaCoelius** [comment]
Great, it's on my to do Monday too

On Friday, February 20, 2015, Alan Joseph Williams <notifications@github.com>
wrote:

> This conversation is going to happen Wed 2/25. I'll draft some initial
> thoughts for us to review on Monday.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/134#issuecomment-75293582>
> .
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by RebeccaCoelius** [comment]
Alan completed interview yesterday, we will do further work on this and create TPs for other staff members/use cases during the upcoming sprints.
