### ISSUE TITLE
Talk for Health Refactored Conference 

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/health#135]
I am currently slated to speak at the [Health Experience Refactored](http://www.hxrefactored.com/) conference in Boston on April 1 & 2 (thanks @mollymcleod!). I'll need to produce a draft of the presentation by early March.

**Comment by RebeccaCoelius** [comment]
Funnily I just spoke to one of the organizers and  Health 2.0 employee
involved in the conference. This conference and the people who attend are
extremely healthCARE focused.

Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by alanjosephwilliams** [comment]
Hrm :/

**Comment by RebeccaCoelius** [comment]
We will figure it out, just sharing for context

On Friday, February 20, 2015, Alan Joseph Williams <notifications@github.com>
wrote:

> Hrm :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/135#issuecomment-75293428>
> .
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>
