### ISSUE TITLE
CfA HIPAA Policies and Procedures finalization V.5

### ISSUE THREAD

**Issue by RebeccaCoelius** [codeforamerica/health#139]
Review changes with Chas on Thursday, send to CfA lawyers for their review. Goal is to have finalized end of next week.

**Comment by RebeccaCoelius** [comment]
Chas is going to make updates to our existing policies and procedures and get back to us next week. Then Rebecca will review w/ Meghan. Moving to ready for next sprint.

**Comment by RebeccaCoelius** [comment]
Chas has cautioned that he can't do this until end of week, so the review by CfA lawyers will begin this sprint, finalization w/in Aptible will take place next sprint.

**Comment by RebeccaCoelius** [comment]
I approve of all suggested changes, moved CfA lawyers review to next sprint so they can review final Aptible version.

**Comment by lippytak** [comment]
Cleaaaaanup! Feel free to re-open if it's still relevant.
