### ISSUE TITLE
Consider Balance in Richmond

### ISSUE THREAD

**Issue by RebeccaCoelius** [codeforamerica/health#140]
Prelim discussion with Dave. Lunch w/ Cyd on Thursday to discuss Product involvement.

**Comment by RebeccaCoelius** [comment]
Discussed w/ Cyd at lunch today, she's all about it. Will discuss w/ Health Lab next week when Alan is back. Jack will have bandwith to help in two weeks.

**Comment by daguar** [comment]
Andreas is tee'd up for value proposition, so probably good to ship that this or next week (I imagine next is fine given the fellows are still there this week.)

**Comment by RebeccaCoelius** [comment]
ah got it.Will do first thing next week, thanks @daguar

Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by daguar** [comment]
Just wanted to follow up on this — did we need to do anything further w/r/t VA? Okay to close?

**Comment by RebeccaCoelius** [comment]
Nothing immediate, I can explain more IRL

On Monday, April 6, 2015, Dave Guarino <notifications@github.com> wrote:

> Just wanted to follow up on this — did we need to do anything further
> w/r/t VA? Okay to close?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/140#issuecomment-90244632>
> .
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by alanjosephwilliams** [comment]
We aren't conducting efforts to expand Balance and further. Sounds like appropriate follow up was done. Let's open a new issue if the matter surfaces again.
