### ISSUE TITLE
Balance Value Prop

### ISSUE THREAD

**Issue by RebeccaCoelius** [codeforamerica/health#141]
Work with Alan to clarify marketing needs related to Balance, using Richmond as the model.

**Comment by daguar** [comment]
Concretely Andreas asked me to forward this to pass along to the state folks. Do you (+Alan?) want to take this on, or do you want me to do it? Happy either way, just assign accordingly.

**Comment by daguar** [comment]
You mentioned this was done in standup today - let's touch base about the other side, which is the "ask" for the state.

**Comment by RebeccaCoelius** [comment]
To clarify- @daguar missed the "half" before the done in standup

On Thursday, March 5, 2015, Dave Guarino <notifications@github.com> wrote:

> You mentioned this was done in standup today - let's touch base about the
> other side, which is the "ask" for the state.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/141#issuecomment-77458368>
> .
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by daguar** [comment]
Yup! Sorry about that :)


On Thu, Mar 5, 2015 at 1:56 PM, RebeccaCoelius <notifications@github.com>
wrote:

> To clarify- @daguar missed the "half" before the done in standup
>
> On Thursday, March 5, 2015, Dave Guarino <notifications@github.com> wrote:
>
> > You mentioned this was done in standup today - let's touch base about the
> > other side, which is the "ask" for the state.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/codeforamerica/health/issues/141#issuecomment-77458368>
> > .
> >
>
>
> --
> Rebecca Coelius, MD
> Director of Health
> Code for America
> 415 298 2872
> LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
> Twitter <http://twitter.com/#!/RebeccaCoelius>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/141#issuecomment-77460805>
> .
>



-- 
Dave Guarino
Engineer, Health
(2013 Fellowship alumnus)
Code for America <http://www.codeforamerica.org/>
dave@codeforamerica.org
LinkedIn <http://www.linkedin.com/in/daveguarino/> | GitHub
<https://github.com/daguar/>

**Comment by RebeccaCoelius** [comment]
Value prop portion done, have draft of the ask but will wait to send until we have the Health:Product team meeting so we are all on same page re CfA support

**Comment by alanjosephwilliams** [comment]
Perhaps we can close this one for now? I leave it up to you.

**Comment by RebeccaCoelius** [comment]
The Richmond thing didn't progress in a way that I felt warranted prioritizing, is there another reason to have a generalized version? If now sure lets close.
