### ISSUE TITLE
Prelim Intern Work

### ISSUE THREAD

**Issue by RebeccaCoelius** [codeforamerica/health#143]
- [ ] requested call with Kenny/Clarement opportunity
- [ ] work on V1 project needs for future matching when opportunities arise/we meet awesome people/need becomes acute

**Comment by RebeccaCoelius** [comment]
Draft V1: @daguar @lippytak @alanjosephwilliams please comment/make additions 
THIS IS NOT AT WORDSMITH STAGE, don't waste your time

- Policy research on Calfresh (CA food stamp program) barriers to participation
- Work between the Health Team and Product team to explore and document business models for our projects, especially CleanAssist (dramatically simplified and improved CalFresh enrollment) Examples: https://github.com/codeforamerica/clean/issues/356)
- Working closely with the Health team and our non profit and government partners, do in person research and document reasons that CalFresh applications are being denied
- Explore, experiment with, and document/publish through our Content Team innovative outreach channels for CalFresh enrollment, with a special interest in AdWords
- Work closely with the Director of Health (me) and our team working on the enrollment and usability of CalFresh to create educational content around what we have learned within the work. This will be used for a variety of purposes, including Product support, and as case studies within our government bootcamp program the Gov Academy and Peer Network.

**Comment by daguar** [comment]
I've got a bunch of input on this; in general I feel like the most valuable thing is suited towards the particular person's background. For undergrad-level interns I'd probably suggest helping us concierge to really get in the weeds on this stuff.

**Comment by RebeccaCoelius** [comment]
I'll catch you tomorrow for ten minutes to capture all of the input, but
def agreed re the persons background, and concierge   @daguar

On Tuesday, February 24, 2015, Dave Guarino <notifications@github.com>
wrote:

> I've got a bunch of input on this; in general I feel like the most
> valuable thing is suited towards the particular person's background. For
> undergrad-level interns I'd probably suggest helping us concierge to really
> get in the weeds on this stuff.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/143#issuecomment-75892651>
> .
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by RebeccaCoelius** [comment]
@daguar want to add any other thoughts here? other than of course agreeing that we fit to the person, a few sketches of work you could use help with would be a good starting point.

**Comment by RebeccaCoelius** [comment]
I'm going to close this. Meghan is connecting w/ the Claremont McKenna contact, I think we have a good initial sense of where we could use people.
