### ISSUE TITLE
Get Web Services on R's AMEX

### ISSUE THREAD

**Issue by RebeccaCoelius** [codeforamerica/health#144]

**Comment by daguar** [comment]
Which in particular do we need to move?

**Comment by lippytak** [comment]
@RebeccaCoelius slack me the info whenever and I'll do it. Only two right now are Ducksboard (other teams are using) and Pingometer (only health really...okay to put on this card or should we do something else?)

**Comment by RebeccaCoelius** [comment]
@lippytak I'd rather not do that, I will just give you the card. Yes to Pingometer. Ducksboard needs to be on the tech team account like other web services shared across CfA since it will be impossible for me to track what other teams are using vs health from my card. You can send me account info and i can figure out w/ Mike/Meghan.

**Comment by lippytak** [comment]
Sounds good. Slacked you Ducksboard credentials. I'll switch over
Pingometer when you drop off the card.
