### ISSUE TITLE
CodeAcross Follow up

### ISSUE THREAD

**Issue by RebeccaCoelius** [codeforamerica/health#147]

**Comment by RebeccaCoelius** [comment]
- [ ] what worked, what did not
- [ ] can we extract anything of value for our work

**Comment by RebeccaCoelius** [comment]
@lipptyak are you the best person to discuss this with? If not plz intro me to the right people at mHealth Relief.

**Comment by lippytak** [comment]
I'll intro you to mRelief team now + also would be worth checking with
Hannah and Dave to offer the other perspectives.

**Comment by RebeccaCoelius** [comment]
@lippytak did I miss the intro?

**Comment by lippytak** [comment]
@RebeccaCoelius done now sorry about that!
