### ISSUE TITLE
Get users for CfA about video

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#151]

**Comment by mollymcleod** [comment]
Any potential candidates in the works? We'll want to figure out a simple screener to make sure someone has a good story/potential sound bites and is good on camera. Anything else to add about what we're looking for @Jaime-Alexis?

**Comment by lippytak** [comment]
Assisters
- Carissa - Eligibility worker in SF, user of Clean and a fan. She has some nice stories about going out with the Homeless Outreach Team (SF DPH) and helping homeless folks apply on the street using Clean.
- Liliana - Leads CalFresh outreach at the SF Food Bank. She's an application assister + strong partner + user.
- Jacqueline - Financial capabilities specialist at [MEDA SF](http://medasf.org/). After helping people with tax prep her team uses Clean to help folks apply for CalFresh and have been having a really good experience this year.

Clients/end users
- Sarah of Americorps who we helped get enrolled (not via Clean): https://www.facebook.com/video.php?v=534929013315277&pnref=story
- D who applied via the current State website and had a pretty horrible experience. Took her 3 hours. She's elderly with bad vision so couldn't see a lot of it.
- Otherwise we would have to reach someone through one of the assisters listed above

Other
- Leo O - CalFresh director in SF

@mollymcleod and @Jaime-Alexis let me know if you have questions/who you all would like to connect with.

**Comment by lippytak** [comment]
@mollymcleod and @Jaime-Alexis bump

**Comment by Jaime-Alexis** [comment]
@lippytak thanks for the bump! Just watched Sarah's video. Was her sign up process tough before you helped her out?

For the assisters, which do you think is most compelling when they share stories? Should we have Leo/Molly or I meet with the assisters and maybe Sarah? D might also be good. I like the surprise of Sarah being so young.

**Comment by lippytak** [comment]
Her signup process was was rough...very confusing and black-boxy.

I think Carissa is the most compelling because it's gotten her from out of
the HSA office and out into the community doing outreach, which she loves.
She's around our office Fridays early afternoon (usually 1pm or 2pm) so it
would be easy to meet her.

**Comment by Jaime-Alexis** [comment]
Great, want to reach out to Sarah? And if Carissa is in this Friday can we
do a quick chat with her?

--------------------------------------------------------------------------------------------------------------------------------
Jaime-Alexis Fowler | Director of Marketing | *Code for America*
<http://codeforamerica.org/> | p:*214.673.9060* | @JaimeAlexis
<http://www.twitter.com/JaimeAlexis>

*Bring the Code for America Fellowship to your city in 2016. Learn how.
<http://www.codeforamerica.org/governments/fellowship/>*
