### ISSUE TITLE
Security Officer Training follow ups

### ISSUE THREAD

**Issue by RebeccaCoelius** [codeforamerica/health#155]

**Comment by RebeccaCoelius** [comment]
notes from call:  https://docs.google.com/a/codeforamerica.org/document/d/1E9A_U-bqAJYzvUYQXDtd0fAnaQsEgtdOLSvloKRE2Wc/edit?usp=sharing

**Comment by lippytak** [comment]
Cleaaaaanup! Feel free to re-open if it's still relevant.
