### ISSUE TITLE
Plan San Diego/Long Beach trip

### ISSUE THREAD

**Issue by RebeccaCoelius** [codeforamerica/health#158]
awaiting confirmation from Luke

**Comment by daguar** [comment]
I'll go! :P

**Comment by RebeccaCoelius** [comment]
Are you volunteering to take over '16 recruitment?

On Tuesday, March 3, 2015, Dave Guarino <notifications@github.com> wrote:

> I'll go! :P
>
> —
> Reply to this email directly or view it on GitHub.
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by daguar** [comment]
Offer rescinded! But go to Stone in Escondido!

**Comment by RebeccaCoelius** [comment]
still awaiting Luke confirmation (as he is awaiting confirmation from the city)
