### ISSUE TITLE
National Day of Civic Hacking 2015 Challenge

### ISSUE THREAD

**Issue by hannahyoung** [codeforamerica/health#166]
Hi Health Team,

Wanted to start the conversation around submitting a health challenge for National Day of Civic Hacking.  @daguar told me this would be a good spot to do it. cc @alanjosephwilliams @lippytak @RebeccaCoelius

**Comment by lippytak** [comment]
Yo! Thx for the heads up, we'll make sure to discuss soon. Remind me of the audience/timing of the event...same as CodeAcross basically?

PS who at IE is working on this?

**Comment by hannahyoung** [comment]
National Day is June 6. Audience will be larger than National Day b/c it's not just the CfA network.

IE?
