### ISSUE TITLE
Investigate GCal problems with health-lab@ alias

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#167]
Becca sent us an invite that eluded us, and just got a report from @ondrae that he sent one that I don't think any of us received (the dev meetup) last week. Let's look into this.

**Comment by ondrae** [comment]
Changed one setting in your group. Changed Viewing Members from `All members of the group` to  `All organization members`. Then I sent you all a fake test event. Did it work?

**Comment by daguar** [comment]
I got it! Thanks Andrew!!! GCALMASTER
