### ISSUE TITLE
Metrics for Annual Report

### ISSUE THREAD

**Issue by mollymcleod** [codeforamerica/health#177]
Could be: 
- # of people eligible but not enrolled in CalFresh
- A different problem statement metric
- Number of partners
- Anything that makes the most sense for Clean

https://cfa-annual-2014.herokuapp.com/category/deepening-impact

Any thoughts?

**Comment by alanjosephwilliams** [comment]
cc @lippytak @daguar let's finalize this for @mollymcleod and the Marketing team first thing this morning.

**Comment by daguar** [comment]
@lippytak's got it; @mollymcleod you'll have soon.

**Comment by lippytak** [comment]
c4a.me/peer-to-peer

**Comment by lippytak** [comment]
@mollymcleod :thumbsup: on the notes above. Let's go with:
- 57% of Californians who qualify for CalFresh get it
- 31 approved CalFresh applications
- 5 partners

Send questions my way. Thanks!!

**Comment by daguar** [comment]
@lippytak @alanjosephwilliams — can you review and :+1: or edit the proposed last version after discussion:

- 21 million — Number of Californians eligible for food stamps who aren't getting them
- 3 — Approximate hours it takes to apply for food assistance on the current online system
- 15 —Average minutes it takes to apply for food assistance with Clean Assist

cc @ZoeBlumenfeld

**Comment by daguar** [comment]
(We need to send final on Monday)

**Comment by daguar** [comment]
One specific thing for @mollymcleod — could we change the design of the latter two numbers so that the big-font "number" part on the left says "3 hours" and "15 minutes" (or mins)? I think the unit clarifies significantly for those catching it at a glance.

**Comment by daguar** [comment]
Still pending one number, but here's the final wording:

- XX million — Number of Californians eligible for food stamps who aren't getting them
- 3 hours — Approximate time it takes to apply on the current online system
- 15 minutes —Average time it takes to apply with CleanAssist

@lippytak — reassigning to you to fill in the participation gap number with something that's not apocryphal.

Humble request — we've worked pretty hard to make this specific wording both persuasive and (more importantly) accurate, so if you want to change it, please check in with us first.

**Comment by daguar** [comment]
(PS humble request is for whoever's finalizing the report; accuracy here is super important to us.)

**Comment by lippytak** [comment]
Edited @daguar's comment above. @mollymcleod feel free to ship these metrics.

For the record 'over 1 million' comes from a totally conservative guess that current 2014 participation is 70%. Source for caseload: http://www.cdsscounties.ca.gov/foodstamps/. Source for (very old) participation: http://www.fns.usda.gov/sites/default/files/Reaching2011.pdf.

@mollymcleod /marketing crew, ping me with questions!
