### ISSUE TITLE
Landscape CBOs in SF

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#179]
List of CBOs in SF that we might be able to activate as CF assisters with CleanAssist. Would be helpful to know (though maybe infeasible): 
- What population they serve
- What services they offer
- If they do any CF or MC application assistance currently
- Estimates of # of potentially eligible CF clients

Once we have this list we can work with HSA + the FB to identify potential users and do informational meetings.

**Comment by gabbyjones** [comment]
This is an ongoing list that will continue to be updated. Google Doc is here: https://docs.google.com/a/codeforamerica.org/document/d/1KOQhv2jts0cgvLpHyY3asGgMuDhoBbjkjLtfetxNwHo/edit?usp=sharing
