### ISSUE TITLE
FU re Youth Tech Health conference

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#182]

**Comment by lippytak** [comment]
@rebeccacoelius feel free to reassign to me if you don't have bandwidth.

**Comment by RebeccaCoelius** [comment]
I can do it they just keep going down the sponsorship route

On Saturday, March 21, 2015, Jake Solomon <notifications@github.com> wrote:

> @rebeccacoelius <https://github.com/rebeccacoelius> feel free to reassign
> to me if you don't have bandwidth.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/182#issuecomment-84445781>
> .
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>
