### ISSUE TITLE
Tell HSA their phone tree is broken (for Spanish options)

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#184]
When you call +18553555757 and navigate the Spanish language option down to talk to a rep, you get connected to an English only EW (specifically, the button sequence is 2, wait, 2, wait, 2.)

We should tell them that.

**Comment by daguar** [comment]
@cescacosta reports using this phone # as her go-to: 415-558-1040.

@lippytak any insight on the 2 numbers?

**Comment by lippytak** [comment]
No clue but I don't want to out their secret! I'll look into the 18553555757 number.

**Comment by lippytak** [comment]
Turns out they route non-English calls to English staff if there aren't language staff available or the wait time is too long. Fancy.

**Comment by cescacosta** [comment]
Yeah, I’ve heard that before. As if waiting a long time on a phone is going to somehow make you comfortable speaking English.

**Comment by lippytak** [comment]
lol! Food banker troll. Love it.
