### ISSUE TITLE
NDOCH Challenge

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#185]
How about a SNAP Census but better planned/supported this time? Don't think of this as a must or to-do just an opportunity :)

@hannahyoung can provide guidance/support throughout.

Dates:
- Should have draft by April 29th
- Final version posted early May
- NDOCH June 27th

**Comment by hannahyoung** [comment]
@lippytak yes! let me know what i can do to support!

**Comment by lippytak** [comment]
Flagging @alanjosephwilliams @daguar and @rebeccac for timing. Would love to have a quick chat to think through if we could time cap this at a day or so of work but still make a sweet challenge to teardown every SNAP app online. Remember we have HowGov.Works (!!) and this would fit well with status board.

**Comment by lippytak** [comment]
FYI @rebeccac and @hannahyoung we did a bit of brainstorming and couldn't come up with anything that we thought would be a good brigade project + move the CalFresh enrollment work forward so we're not planning on creating a challenge for this event. Feel free to grab me @hannahyoung if you want to chat and I'm happy to share what we discussed in case you want want to build/lead the challenge.

**Comment by RebeccaCoelius** [comment]
Makes sense thanks for the update

On Monday, April 27, 2015, Jake Solomon <notifications@github.com> wrote:

> Closed #185 <https://github.com/codeforamerica/health/issues/185>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/185#event-290329373>.
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>
