### ISSUE TITLE
Tell HSA their website lists the wrong CalFresh income thresholds

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#189]

**Comment by lippytak** [comment]
They're wrong by a factor of 2...:
![screen shot 2015-03-31 at 6 56 55 pm](https://cloud.githubusercontent.com/assets/2533112/6933105/da67e89e-d7d7-11e4-8920-5f736df6757c.png)

source: http://www.sfhsa.org/333.htm

**Comment by lippytak** [comment]
So this also exists: http://www.sfhsa.org/157.htm

Ahh!

**Comment by lippytak** [comment]
The tweet BLUF: 
![screen shot 2015-03-31 at 7 04 06 pm](https://cloud.githubusercontent.com/assets/2533112/6933186/ba2b1a14-d7d8-11e4-9dd2-be173120fc99.png)

https://twitter.com/lippytak/status/583086912308580353

**Comment by daguar** [comment]
Add to the list of The Basics™:

- Your website does not have wildly innacurate information

**Comment by lippytak** [comment]
The start of a good content piece...The Basics on gov digital services or
something. Plus a toolkit on how to test each. Okay fine gfs already did
this better humph

**Comment by alanjosephwilliams** [comment]
The shot clock for fixing it begins...

On Wed, Apr 1, 2015 at 1:04 PM, Jake Solomon <notifications@github.com>
wrote:

> Closed #189 <https://github.com/codeforamerica/health/issues/189>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/189#event-270829471>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
