### ISSUE TITLE
Acquire hug consent

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#192]

**Comment by lippytak** [comment]
Pre-req to #191

**Comment by daguar** [comment]
Is this covered under HIPAA?

**Comment by RebeccaCoelius** [comment]
Only if I'm being paid for it.

Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by lyzidiamond** [comment]
:+1:
