### ISSUE TITLE
Set up 2-factor auth for GitHub (Jake)

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#206]

**Comment by lippytak** [comment]
Deleted repo with PII. No longer necessary.

**Comment by daguar** [comment]
So, fair, but this is also really quick to set up and a good idea generally so can we do it still?

**Comment by lippytak** [comment]
Fine but later! My phone dies all the time so can't rely on SMS verification.

**Comment by daguar** [comment]
You should only have to do it every once in a while on your main computer; you can also save your backup passwords in another place if you need.

**Comment by daguar** [comment]
I am going to consistently push on low-effort, high-return security measures — this takes maybe 5 mins max.

**Comment by lippytak** [comment]
![screen shot 2015-08-25 at 10 56 40 am](https://cloud.githubusercontent.com/assets/2533112/9474884/06268644-4b18-11e5-99d5-ac50418b9b1a.png)
