### ISSUE TITLE
Open Referral Alameda County P1

### ISSUE THREAD

**Issue by RebeccaCoelius** [codeforamerica/health#21]
Speaking to Meagan/Lynco Monday to clarify their funder needs then update Sameer/Spike.

**Comment by RebeccaCoelius** [comment]
Spike/Sameer/Fureigh ready to roll. Waiting on Cantinas to execute contract.

**Comment by RebeccaCoelius** [comment]
Jack is going to step up the pressure this week if no word.

**Comment by RebeccaCoelius** [comment]
Jack spoke to B Wayne Chief of Staff, confirmed commitment to project, said to call back Monday EOD if Cantinas still has not come through.

**Comment by lippytak** [comment]
Done?

**Comment by RebeccaCoelius** [comment]
No but I need to break into chunks

On Saturday, February 14, 2015, Jake Solomon <notifications@github.com>
wrote:

> Done?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/21#issuecomment-74398617>
> .
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>
