### ISSUE TITLE
Document all CA counties' web pages showing CalFresh income limits (and which are wrong)

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#217]
Anecdotally, a lot are wrong. Let's check.

**Comment by daguar** [comment]
Done here: https://docs.google.com/spreadsheets/d/1XO3rdCSKx2NVjCfvul2X8LvGRVtI5t5OR1hB-cXDz5Y/edit?usp=sharing

Summary:
- Incorrect income info — 8 counties	(14%)
- Correct income info — 9 counties (16%)
- No income info — 41 counties (71%)

[Percentages don't add up due to rounding]

**Comment by lippytak** [comment]
Done/

**Comment by lippytak** [comment]
@daguar @alanjosephwilliams let's take an hour to send corrections to everyone and see how many fixes we get. Okay if I set aside an hour on Friday for beer + webmaster outreach?

**Comment by alanjosephwilliams** [comment]
This could be a standalone health-log—is it referenced there at all?

On Mon, May 18, 2015 at 10:36 AM, Jake Solomon <notifications@github.com>
wrote:

> Closed #217 <https://github.com/codeforamerica/health/issues/217>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/217#event-307626878>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
