### ISSUE TITLE
CDSS FU

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#220]
Do it
- Call w Karen
- NOA redesign w Ryan
- Link to stuff

**Comment by RebeccaCoelius** [comment]
- follow up on API access question
- Todd wants to connect us w/ program integrity and cash access
- Todd wants to help us get better atm data (prob related to cash access mention above)
- further Ben/NOA context: attend only a few organized mtgs, comment on notices

**Comment by daguar** [comment]
So this is all good?

**Comment by lippytak** [comment]
yup
