### ISSUE TITLE
Plan County solicitation

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#226]
plan it
do it

**Comment by lippytak** [comment]
v1:
- Write a paragraph
- Leo forwards + intros to CalFresh director
- Stephanie forwards + intros to FB director
- Individual calls with both
- In person meeting with both > launch

**Comment by lippytak** [comment]
@alanjosephwilliams + @daguar gut check above plz ^

Any compelling reasons to make things more complicated? Let's try to get a bay area county first, per Leo's recommendation. I also have a connection in Napa and Solano so I'll try them, as well.

**Comment by alanjosephwilliams** [comment]
Looks good to me. Do we want to copy any of the folks at CDSS on these?

On Mon, Apr 27, 2015 at 10:11 AM, Jake Solomon <notifications@github.com>
wrote:

> @alanjosephwilliams <https://github.com/alanjosephwilliams> + @daguar
> <https://github.com/daguar> gut check above plz ^
>
> Any compelling reasons to make things more complicated? Let's try to get a
> bay area county first, per Leo's recommendation. I also have a connection
> in Napa and Solano so I'll try them, as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/226#issuecomment-96743623>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
I'm not sure it needs to be more complicated, but the content of that paragraph seems to me a big thing? Want to post what you're thinking?

**Comment by lippytak** [comment]
Also BASC (something like that...) is a group of bay area counties that meet quarterly...we should go and recruit pilot counties. Noelle/Trent/Leo can intro us if necessary.

**Comment by lippytak** [comment]
Marc strongly recommended Merced and can intro to ED.

**Comment by lippytak** [comment]
I'll start this in earnest next week - maybe aim to get 3-5 intros to county EDs or CalFresh directors.
