### ISSUE TITLE
Call with CDSS CalFresh outreach team

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#229]
- Understand what they're doing
- Engage them in CBO survey (distribution/learn together!)
- Spot quick win opportunities
- Dig into county personalities/who we should we work with/avoid in more detail

**Comment by lippytak** [comment]
What's the team? What do y'all do?
- Statewide extension of outreach. Guidelines set forth by FNS. Outreach by contracting with CBOs (8 primes) who then subcontract to others (>100 subs). They do mix of outreach, pre-screening, app assistance, SAR-7 and recerts.
- Operational in 43 of 58 counties
- Big barrier = they reimburse but do not grant, so CBOs need to spend 100% up front
- Services
  - Materials, brochures, posters, fact sheets, flyers
  - Outreach tool kit
  - Each prime has an assigned analyst that they work with
  - Annual training of prime/subprime contractors
  - Resources here: http://www.cdss.ca.gov/calfreshoutreach/

What do you wish you had for yourself/CBOs?
  - County timetrends (data is in dashboard)
  - Specifically: the "mythical" (lol) participation rate, churn, and % people on MC who may be eligible (project idea!)
  - The big question is: What are effective ways to reach these populations in need (adwords writeup!)
  - Anecdotally mixed-status famillies are hardest to reach.
  - Working poor = most overlooked. Why? "I don't know exactly why." Hears: "I don't have time to wait 30 minutes...only have so much time at lunch" or "I've got a job so I don't qualify." Probably not the folks who are going to show up at a health fair or other outreach events.

County participation plans/best practices guide
  - Very early in the work, need to take participation plans, distill common themes, FU with counties to assess effectiveness.

CBO survey feedback
  - "I like the side bar comments"
  - Maybe too general? Not actionable?
  - Consider digging into training; where do they get it now? what do they want? what format?
  - General consensus that  FU and county communication is hard
  - Survey may be opp to share key changes from the farm bill - Drug felon change. 200%. But there are other changes that are happening all the time.

Pay for performance:
- "We cannot pay for performance" (I'm still skeptical)
- CBOs budgeted for estimating their work at a certain $ value for the work
- Medi-Cal pays ~$58 per successful application.
- "The Farm Bill says that you cannot compensate individuals for outreach activities based on the number of people who apply." I cannot find that part: https://twitter.com/lippytak/status/593533285197709313

**Comment by daguar** [comment]
Edited above to add link to the list of prime contractors http://www.cdss.ca.gov/calfreshoutreach/res/Prime_Contractor_Contact_List.pdf
