### ISSUE TITLE
Research this grant

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#230]
Should we consider applying?

SNAP Process, Technology Improvement Grants Application Announced
Funding intended to increase efficiency and improve customer service at the local level

**Comment by daguar** [comment]
Yes!

**Comment by RebeccaCoelius** [comment]
I researched too. What specific questions are you asking so we don't duplicate efforts?

**Comment by RebeccaCoelius** [comment]
We should apply but ugh this is going to be annoying. 
RFA: http://apply07.grants.gov/apply/opportunities/instructions/oppUSDA-FNS-FY15-SNAP-PTI-GRANTS-cfda10.580-cidUSDA-FNS-FY15-SNAP-PTI-GRANTS-instructions.pdf
Grant page: http://www.grants.gov/search-grants.html?agencies%3DUSDA%7CDepartment%20of%20Agriculture
FAQS: http://www.grants.gov/web/grants/applicants/applicant-faqs.html

**Comment by RebeccaCoelius** [comment]
20 awards (later they say will award 6-11...)
20K - 2 mill per award 
501c3's qualify
Would be applying for "technology improvements", less likely "process improvements to decrease churn"
announced 9/30/15
grants funded 9/30/15 - 8/31/18

notable limitations:
Allowable Uses of Funds
Funds from this RFA are for new projects and shall not be used for the ongoing cost of carrying out an existing project. 
Furthermore, projects predicated on
waiving SNAP regulations are not allowable and will not be considered for funding. However, if during the grant period, a State agency determines a waiver is needed, the State may apply for one but there is no guarantee FNS will approve the waiver.
SNAP Process and Technology Improvement Grants do not support projects that devote morethan 25 percent of the requested grant funds to outreach activities, such as informational materials, pure application assistance, screening/pre-qualifying applicants, or whose purpose is to attract SNAP applicants.

**Comment by lippytak** [comment]
grants officer
FNS Grants Officer at:
Kimberly Shields, Grant Officer
Grants and Fiscal Policy Division
U.S. Department of Agriculture, FNS
3101 Park Center Drive Room 740
Alexandra, VA 22302
E-mail: Kimberly.Shields@fns.usda.gov

**Comment by lippytak** [comment]
>The purpose of this grant competition is to support efforts by State agencies and their
community-based and faith-based partners to develop and implement:
- Simple SNAP application and eligibility determination systems; or
- Measures to improve access to SNAP benefits by eligible applicants.

**Comment by lippytak** [comment]
Okay, we have to apply...snippets from priority the second priority - Technology Improvements goals:
- simplify the enrollment process
- improve client retention.
- workers to spend less time on data entry
- reduce the number of telephone calls (especially about simple matters such as case status)
- fewer documents lost (for example through document imaging)
- Technology can reach populations that have difficulty visiting the local offices and thereby improve access.

**Comment by lippytak** [comment]
" if the grant proposal is from an entity other than a State agency, it must
show that a State agency strongly endorses or is involved in the proposed project in order to be
considered. "

**Comment by lippytak** [comment]
lol @daguar "In some instances the process to complete the migration of permissions and/or the renewal of the entity record will require 5-7 days or more. We strongly encourage grantees to begin the process at least 3 weeks before the due date of the grant solicitation"

**Comment by lippytak** [comment]
AHHH
> NOTICE: Special Characters not Supported
All applicants MUST follow grants.gov guidance on file naming conventions. To avoid
submission issues,

**Comment by RebeccaCoelius** [comment]
Small thing

On Tuesday, May 12, 2015, Jake Solomon <notifications@github.com> wrote:

> Assigned #230 <https://github.com/codeforamerica/health/issues/230> to
> @RebeccaCoelius <https://github.com/RebeccaCoelius>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/230#event-303281783>.
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>
