### ISSUE TITLE
Fun stakeholder update email

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#245]
For the Leos, Wills, Kims, Stephanies, TippingPoints of the world. Maybe it will turn into a monthly TinyLetter thing, maybe not!

**Comment by daguar** [comment]
:+1:

**Comment by lippytak** [comment]
Something like this...

===

Quick update for you all on what we've been up to the last month or so. As always feel free to ping me with questions/thoughts or ring my cell if you want to chat (510) 206-8727.

## We have people applying for CalFresh in under 10 minutes on their phones
In the last month we built GetCalFresh.org - a simple online application for CalFresh. Our first 50 applicants finished in less than 10 mins on average and about 1/4 of them did so on their phones. Pretty cool. We've also found that...

## without help, many (most?) applicants get denied
It's hard to get outcome data here but it's looking like only ~30 - 40% of these cases are getting approved right now. For comparison we've seen that typical assisted cases in SF get approved about 60% of the time, so that's our target rate. Our next set of features will help address this; easier verification submission, better interview reminders, etc. In supporting these 50 applicants we've also learned that...

## people LOVE getting help over text message
It's a delight for people. Check it out (these are just text messages from the client's perspective):
![happy](https://cloud.githubusercontent.com/assets/2533112/8174178/0dc8c8f6-138e-11e5-9ccb-69ee4553c774.png)

In July we'll be working on plugging GetCalFresh.org into MBCW and getting feedback from a few partner to make sure we avoid another TurboTax situation.

Cheers!
Jake and the team

**Comment by lippytak** [comment]
will
pete
stacy
kim
stephanie
liliana
tiana
leo

who'd I miss?
