### ISSUE TITLE
Follow-up from Marin meeting

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#246]
This is the follow-up aspect to the 5/5 meeting in Marin: https://github.com/codeforamerica/clean/issues/515

We should follow up (ideally today) with an email with concrete next steps to everyone who was in the room. Specifically I'm thinking:

- [x] Custom Balance phone #  ( done: 415-319-6624 for English; have not done Spanish, but we probably should?)
  - [ ] 1,000 Balance cards on the way?
- [ ] Steps for assessing Clean feasibility/business process
  - [ ] "Need to talk to a person who does X, Y, Z" (likely: processes applications, does interviews, etc)
- [ ] Link to Demo Clean and encourage them to try it on their phones

(Please edit above list and comment with your edits)

@lippytak Okay for you to own this?

**Comment by daguar** [comment]
Added:
- [ ] Link to Demo Clean and encourage them to try it on their phones

**Comment by daguar** [comment]
Done with setting up Balance # for Marin HHS — see above.

Should we also set up a Spanish one? I feel like it sends the right message about our user-centered orientation.

**Comment by lippytak** [comment]
Next step: get one Clean app! I'll ping them in a week if I don't hear anything.
