### ISSUE TITLE
Health Website

### ISSUE THREAD

**Issue by RebeccaCoelius** [codeforamerica/health#25]
talk to Dan Hon,

**Comment by RebeccaCoelius** [comment]
Alan completed V1 of Health Home. 
Chatting this afternoon about Health Home. 
Setting up chat w/ JA so marketing is aware.

**Comment by RebeccaCoelius** [comment]
Mtg w/ Marketing next week to further expand on Health Home goals and general marketing needs this year.

**Comment by alanjosephwilliams** [comment]
@rebeccaCoelius it sounds like we could close this issue, and move to more task-specific issues like "Homepage v1 Pull Request for review by Marketing" #99.

If you prefer to leave it open that's fine too—but I am going to remove the "current sprint" label, and save that for those pieces of the effort we are tackling each rev.

**Comment by RebeccaCoelius** [comment]
agreed, closing issue
