### ISSUE TITLE
Estimate drop off rate for existing SAWS

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#251]
Something like:
- get 500 adwords clicks
- do QUICK typeform/SMS survey
- send them to benefitscal.org
- wait a day
- FU with one question "were you able to finish the CalFresh application? Reply YES or NO"
- Offer them getcalfresh.org
- Wait 1 more day
- FU with "were you able to finish the CalFresh application? Reply YES or NO"

**Comment by lippytak** [comment]
@daguar possible to do a full screen iframe for BCW/other SAWS so we could get analytics while people are doing the app? Or is this basic 'internet doesn't let you do that' stuff?

**Comment by daguar** [comment]
Hrm, I thiiiiink iFrames are completely inaccessible.

**Comment by lippytak** [comment]
So we're doing this now. Kinda. w00t
