### ISSUE TITLE
CDSS Contract phase 1 deliverable

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#252]
_AJW hijacking this comment_

It's time to author and package our fist deliverable for Phase I of our work with CDSS. Specifically, we'll need to **"Document bottlenecks in the Calfresh application/enrollment process in at least two counties, noting what we suspect can be addressed by technology."**

#### Outline
   - [ ] Executive Summary
   - [ ] The Funnel
   - [ ] Saws: Bottlenecks Online
       - [ ] Section Introduction
       - [ ] Walkthrough of MBCW
       - [ ] Walkthrough of C4
       - [ ] Walkthrough of Leader
       - [ ] List of websites with incorrect information
       - [ ] Uptime
   - [ ] Deep: Bottlenecks in SF
       - [ ] Section Introduction
       - [ ] Nurses Study
       - [ ] EW Survey Results
       - [ ] Business Process Map
   - [ ] Wide: Bottlenecks across the state
       - [ ] Section Introduction
       - [ ] NOA Timeline
       - [ ] Adwords Analysis
       - [ ] Balance Survey Qualitative Feedback
       - [ ] EW Survey Solano
       - [ ] Heterogeneity across counties / county phone calls / etc
   - [ ] Next Steps (Mostly TBD / these are just ideas)
      - [ ] Section Introduction
      - [ ] More EW Surveys
      - [ ] Assister Surveys
      - [ ] Business Process Mapping? Etc. 
      - [ ] ASKS

**Comment by alanjosephwilliams** [comment]
@lippytak will post 
- The contract to reference
- Any outline that has already been written

@alanjosephwilliams will deliver a draft by EOW, including but not limited to synthesis of:

Things to repackage:
- NOA timeline
- Teardowns
- Business Process Map
- EW survey data
- Adwords analysis
- Balance survey qualitative feedback

**Comment by alanjosephwilliams** [comment]
@daguar @lippytak I'm moving forward on building these sections out, so lmk if you see any gaps, have any thoughts about tentative structure

**Comment by alanjosephwilliams** [comment]
Fuller outline taking shape here:
https://docs.google.com/document/d/15jfB5MTJ_9ppzgI8Z_6CFTBUWJs4UZ2vDU5szN-BeLU/edit#

**Comment by buckleytom** [comment]
@alanjosephwilliams I'm glad you guys included The Funnel here. Thanks.

**Comment by lippytak** [comment]
@alanjosephwilliams at your leisure could you post the repo/gh-pages link here?

**Comment by alanjosephwilliams** [comment]
I was working against the grain trying to have two frames for understanding the process. Here is an updated outline using The Funnel as the organizing principle. I think it also helps highlight where *we don't yet have good data* and could use more.

#### Outline
   - [ ] Executive Summary
   - [ ] The Funnel
      - Aware
      - Decide
      - Screen
      - Apply
      - Interview
      - Verify
      - Get EBT
      - Use EBT     
      - Stay Enrolled 
   - [ ] Bottlenecks Before Applying:
       - [ ] List of websites with incorrect information
       - [ ] Nurses Study
       - [ ] Adwords Analysis
   - [ ] Bottlenecks During the Application Process:
       - [ ] Uptime
       - [ ] Walkthrough of MBCW
       - [ ] Walkthrough of C4
       - [ ] Walkthrough of Leader
   - [ ] Bottlenecks Once Application is Submitted:
       - [ ] Business Process Map
       - [ ] EW Survey Results
       - [ ] Nurses Study
       - [ ] Heterogeneity across counties / county phone calls / etc
   - [ ] Bottlenecks Once Determined Eligible
       - [ ] NOA Timeline
       - [ ] Balance Survey Qualitative Feedback
       - [ ] EBTNearME Research

**Comment by daguar** [comment]
@alanjosephwilliams — should we comment/contribute in the GDoc linked above or did you fork it to a separate one we should add to?

**Comment by alanjosephwilliams** [comment]
Draft in progress here: https://docs.google.com/document/d/11uRKMMOpGrxu0hsuXXS8wHeE4GSyv6rNY-XNDy1Rvrs/edit#

Dev work being done here:
https://github.com/codeforamerica/calfresh-bottlenecks

**Comment by lippytak** [comment]
NOA BLUF: CalFresh clients receive many Notices of Actions, which are confusing, full of jargon, and do systematically help the customer take a successful next step.
- For one CalFresh case, we received 12 NOAs over the first 7 months of a new CalFresh case
- They were confusing: ...
- They used jargon: ...

MBCW BLUF: My Benefits CalWIN is long, confusing, and difficult to complete accurately. MBCW includes approximately 50 screens and 100 questions long for a single unemployed individual with no job.
- example
- example
- see slideshow below for details

cc @alanjosephwilliams
