### ISSUE TITLE
Draft public CalFresh issue tracker for Kim

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#257]
Our awesome friend Kim is thinking of starting/managing a public issue tracker for CalFresh and asked for some recommendations. @daguar @alanjosephwilliams what do you think? I think basic reqs are:
- public issues without account login
- super accessible/not intimidating
- can post/follow issues via email
- easy categorization (counties, NOAs, biz process, etc.)

I would propose snap.stackexchange.com but it takes some [interwebs support](http://meta.stackexchange.com/questions/76974/how-can-i-propose-a-new-site) that may take some work. Maybe an excuse for GH Forum (cc @ondrae)?

**Comment by daguar** [comment]
I think StackExchange is overkill; big thing for people is gonna be user-friendliness and searchability.

**Comment by lippytak** [comment]
SF Food Bank leading the way on this. Will provide support to them as helpful!
