### ISSUE TITLE
V1 Content: Bottleknecks

### ISSUE THREAD

**Issue by RebeccaCoelius** [codeforamerica/health#258]
- agree on goals, timeline with LD
- outline content

**Comment by RebeccaCoelius** [comment]
largely shared w/ @lippytak, but I'll be sure it happens

**Comment by lippytak** [comment]
Some links for @ladyson to get started:
- See conversion funnel for Clean Assist cases in SF: https://github.com/codeforamerica/health-logs/issues/15
- Adwords and CalFresh: https://github.com/codeforamerica/health-logs/issues/15
- The Funnel: https://github.com/codeforamerica/health-logs/issues/1
- User research
  - https://github.com/codeforamerica/health/wiki/EW-research
  - https://github.com/codeforamerica/health/wiki/User-research
  - https://github.com/codeforamerica/health/wiki/Research:-January-2015-User-Research
- Eligibility Worker survey in SF and Solano (log onto our Wufoo to see the full results): https://codeforamerica.wufoo.com/reports/ew-survey/
- Calling county social services (also see @alanjosephwilliams and my Twitter feed...): https://github.com/codeforamerica/health/issues/256

@alanjosephwilliams @daguar what else should @ladyson look through while starting to write a 'barriers to CalFresh enrollment' piece?

**Comment by lippytak** [comment]
@ladyson also: Barriers to staying enrolled = confusing letters bit.ly/calfresh-timeline

**Comment by lippytak** [comment]
I kinda think this could make for a sweet interactive slideshow...with [embedded timelines](http://bit.ly/calfresh-timeline) and [videos and things](http://citizenonboard.com/snap/ca/#147)! Just a thought :)

**Comment by RebeccaCoelius** [comment]
Ooh @lippytak is getting excited!

Generally SHOWING what we learned would be a very unique way to share this
as content.

On Monday, May 11, 2015, Jake Solomon <notifications@github.com> wrote:

> I kinda think this could make for a sweet interactive slideshow...with embedded
> timelines <http://bit.ly/calfresh-timeline> and videos and things
> <http://citizenonboard.com/snap/ca/#147>! Just a thought :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/258#issuecomment-101082234>
> .
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by daguar** [comment]
@ladyson I've also been experimenting with using a Waffle board as an interface to think through the problems/bottlenecks we've encountered in the process:

Go to https://waffle.io/codeforamerica/calfresh-bottlenecks — each issue has some content of what we've found so far

**Comment by ladyson** [comment]
We reviewed the draft with @alanjosephwilliams and brainstormed some ideas for actionable "how to" content to complement the report. Some guidance for the people who are responsible for maintaining info pages on county websites on how to improve those pages seemed like a good place to start. Details TBD but could be something like:

* How to evaluate if your page is providing the right information in a usable/findable way (using search etc)
* Template / outline for what info should be consistently provided
* Basic tips for writing for the web (potential collab with DFD team)

Thoughts? @dschrimmer is going to start working on it.

**Comment by alanjosephwilliams** [comment]
@ladyson should we circle back about whether the Content team wants to extrapolate any  of the findings from our report in to a piece more focused on external audiences?

**Comment by RebeccaCoelius** [comment]
Jen definitely wants to see this

Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by ladyson** [comment]
Yes! Here are a few generalizable practices that jump out at me from the CDSS report:

# How to use Keyword Planner to find out how many people are searching for your program and evaluate if they're getting the info they need *
# How to use Adwords to run a test on how many users successfully complete your application *
# How to do a statewide audit of the information provided by county websites about your program
# How to set up "uptime" monitoring of online services *
# How and why to make a walkthrough of an online service *
# How to make a process map of an end-to-end service
# How to survey your frontline workers *

I think we could pick a few of these to write up and bundle together in a "basic research methods to evaluate online enrollment in health/human services" guide. And the CalFresh report can serve as our example of why these applied practices are useful. I starred the practices that seem most actionable and repurposable. What do you think?

**Comment by RebeccaCoelius** [comment]
I think the process map is pretty important, but otherwise makes sense to me! What do you think @ajw

**Comment by alanjosephwilliams** [comment]
We shipped this! It was fun and well received.
