### ISSUE TITLE
Google Scholar research for SNAP barriers

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#265]
- Bonus if it's California
- Bonus if it's about application process barriers

**Comment by lippytak** [comment]
Barriers to Participation in the Food Stamp Program Among Food Pantry Clients in Los Angeles
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1470578/

>Barriers to food stamp participation in California and Los Angeles include a finger imaging requirement, a lengthy and complex application process, and lack of knowledge about eligibility.16,17 Nationally, changing eligibility restrictions and the stigma associated with participation also act as barriers to increasing food stamp enrollment.18

**Comment by lippytak** [comment]
http://www.sciencedirect.com/science/article/pii/S0740624X13001196
e-Government legislation: Implementation issues for programs for low-income people


This paper introduces a research agenda to explore the intersection of e-government implementation and the key federal programs – Medicaid, the Supplemental Nutrition Assistance Program (SNAP, a.k.a. food stamps), (SSI), and Temporary Assistance to Needy Families (TANF, a.k.a. welfare) – that provide assistance to low-income citizens in the United States. To lay the groundwork for on-going research, this paper focuses on the implementing statutes that require different levels of automation for delivering these programs to the public. It discusses the programs in terms of their breadth, impacts to recipients, and the effects of automation as implemented for each. It identifies some of the consequences of automation, such as potentially faster service delivery, different approaches to information access, and issues of privacy. It then suggests some points to consider for policymakers and for future research to more deeply understand this unique and little-studied aspect of e-government implementation. By understanding the impacts of implementing statutes on the poor, policymakers can develop a deliberately inclusive strategy that leverages technology to support access to assistance in measurable models that can be implemented at the federal, state, and county levels. This can further democratize the government-to-citizen relationship and support greater accountability to taxpayers.

**Comment by lippytak** [comment]
Working the Poor: Barriers to CalFresh Participation and Enrollment Exploring client experiences and the role of community-based organizations in outreach
http://gradworks.umi.com/15/85/1585052.html

Abstract In this thesis, I draw on qualitative research collected through a California food bank's CalFresh outreach program to examine barriers to SNAP participation. Drawing on ethnographic methodology, I conducted participant observation, semi-structured interviews, phone surveys and numerous informal interviews in order to develop a client narrative around the application process. Through this research I explored the obstacles and barriers clients must overcome to enroll and maintain enrollment in CalFresh. My research findings revealed there are numerous barriers to participation. Some barriers are a result of being a vulnerable low-income individual or household, while others are a result of program administration or service delivery. My research also revealed that having a community based advocate or CBO intermediary significantly improved the client experience. Having assistance and an advocate throughout the application process improved the application experience as well as retention in the program

**Comment by lippytak** [comment]
Recommendations on CalFresh 
- http://ccrwf.org/wp-content/uploads/2011/01/cfpa-calfreshrecommendations-wfsummit2011-final.pdf
- The “back-end” disconnected from the “front end”. Where client interfaces (for
example the C-IV online application) do exist, they have largely been funded and
developed outside of the main county system where most clients apply for CalFresh.
This means clients have not fully benefited from advances in technology.
- Wildly differential access to technology. In many of California’s larger counties,
client tools (online reporting, benefits checking) are optional components and are not
used consistently in all counties. And California’s largest county, Los Angeles, still has
not modernized its enrollment portals or joined one of the existing systems. This
patchwork system has led to “victims of geography” where an applicant can face
significantly reduced access to CalFresh simply because of the county in which
he/she resides. 
- Policy object #1: Increase access to CalFresh by removing application barriers.

**Comment by lippytak** [comment]
The labor practices of service mediation: a study of the work practices of food assistance outreach
http://dl.acm.org/citation.cfm?id=2208342
- We introduce the construct of service mediation, which includes the technical, social, and knowledge labor practices involved in enabling access to and use of an e-government service.
- The results of our research highlight the role service mediation plays in the use of services and service technologies in information-rich organizations. 
-

**Comment by lippytak** [comment]
Nearly 4 million Californians are food insecure
https://escholarship.org/uc/item/5407m7mh#page-1

**Comment by lippytak** [comment]
Access and Access Barriers to Getting Food Stamps: A Review of the Literature (2008)
- http://frac.org/wp-content/uploads/2009/09/fspaccess.pdf
![screen shot 2015-05-23 at 9 50 44 am](https://cloud.githubusercontent.com/assets/2533112/7785006/320ab702-0131-11e5-96af-8a255df043c9.png)

**Comment by lippytak** [comment]
Struggling for sustenance: SNAP access barriers in Santa Clara and San Mateo Counties
https://www.shfb.org/docs/advocacy/foodstamp_accessbarriers.pdf

gold mine
- "1. Providing verification documents is the most onerous part of the FSP process: "
- "1. Many people think they are eligible but still haven’t applied "
- "4. Many are deterred from applying by the difficulty and/or intrusiveness of the process "
- “I’ve heard from friends that it’s very difficult to apply.” 
- "Move to online application: An online application would reduce barriers for applicants and workload for eligibility workers. Applicants could scan and submit their verification documents along with their application by email and receive a decision on their case without ever having to speak with an eligibility worker. San Francisco County and others in California already use an online application."

![screen shot 2015-05-23 at 9 53 29 am](https://cloud.githubusercontent.com/assets/2533112/7785015/94bfa574-0131-11e5-9d64-6adc9c81af2f.png)

![screen shot 2015-05-23 at 9 53 50 am](https://cloud.githubusercontent.com/assets/2533112/7785016/a493b6f2-0131-11e5-9b8a-e944d6bba48d.png)

![screen shot 2015-05-23 at 9 54 10 am](https://cloud.githubusercontent.com/assets/2533112/7785017/b2eec700-0131-11e5-8a07-d3de8f520074.png)

**Comment by lippytak** [comment]
As far as I can tell: "There is not a single published study of the online application process for CalFresh"

**Comment by daguar** [comment]
This is excellent.

**Comment by lippytak** [comment]
AARP Foundation funded study:SNAP Access Barriers Faced By Low Income 50-59 Year olds

http://www.aarp.org/content/dam/aarp/aarp_foundation/2013-pdfs/SNAP_White_Paper_Mar_2013.pdf

![screen shot 2015-05-24 at 7 26 14 pm](https://cloud.githubusercontent.com/assets/2533112/7790936/c499d200-024a-11e5-87f8-d8bfff9c713d.png)

Fascinating but not focused on CA and not much on the application process itself.
