### ISSUE TITLE
Review County participation plans

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#266]
See if there's anything about barriers in the application process

http://cafoodbanks.org/statewide-calfresh-participation-plan

**Comment by lippytak** [comment]
Alameda
- "utilize new technology to generate and complete new applications in the field"

Butte - nothing

Contra Costa
- "Significantly increase the opportunities for client self-service"
- "Create multiple channels of access"
- "Reduce the amount of manual tasks that staff must complete in processing an application"

Fresno
- "Fresno County encompasses more than 6,000 square miles. These distances can make in-office visits difficult for clients"

**Comment by lippytak** [comment]
- Kern - nothing
- LA - "The goal of these expanded outreach efforts is to remove perceived barriers and increase CalFresh participation among the many potential eligible individuals and families of LA County whoare not currently receiving assistance. In furtherance of that goal, DPSS has committed to an increase in CalFresh Only participation of 12 percent annually."

**Comment by daguar** [comment]
- San Bernadino is awesome:
  - Under "Current and Future County Outreach Efforts" it says they've created an entity called the "CalFresh Improvement Consortium" made up of a bunch of CBOs, and that the county identified 5 overarching goals with the consortium:
    - 1) Unique Population Concerns
    - 2) Hunger Issues
    - 3) Policy Simplification
    - **4) Simplification of C4Yourself online application**
    - 5) Media/Marketing
 - Under "Other Creative/Innovative Strategies" it says:
   - "We would also like to collaborate with the State and other counties on developing a prepopulated RE form, and on **utilizing text messaging to contact customers regarding missed appointments or needed verifications**."

**Comment by daguar** [comment]
More San Bernadino, slightly off-topic, but love it:

- "For seniors, we have partnered with the Department of Aging and Adult Services. We pair Eligibility Workers (EWs) with Social Workers and visit 5 different Senior Centers every month. **Our EWs take laptops** so that as they share the benefits of the Calfresh program with the seniors, **they can have them complete online applications on the spot.** Pairing with the Social Workers lends credibility to our EWs and enables them to build rapport and trust more quickly with the seniors..."

- "...Prior to this outreach partnership, 7,135 senior citizens received CalFresh/SNAP benefits in the county. One year later **senior recipient numbers increased 25.6%** to 8,959 seniors. This past year we found that **of those seniors who chose to apply for CalFresh through this outreach partnership, more than 40% were found eligible and received benefits.**"

**Comment by daguar** [comment]
- Sonoma calls our online application burden as the first big biz process barrier:
  - We have also identified several business processes that create bottlenecks in application processing. The first area of improvement is the length of time needed to register new applications in the CalWIN system. **Application registration is a complicated, painstaking process, requiring attention to detail and multiple levels of file clearance to ensure accurate data entry and case set up.**

**Comment by daguar** [comment]
(Note: unclear if that's internal-facing side of CalWIN or MBCW.)

**Comment by lippytak** [comment]
Pretty sure the above comment is about "clearing" (some counties call it "app reg") from the county perspective. It's a great point though...the complexity of this step means that a single EW/person cannot take you from application to approval.

**Comment by lippytak** [comment]
Wow @sanbernadino...that's one fine CalFresh participation plan if I do say so myself...

**Comment by lippytak** [comment]
- Marin - Targeting seniors and spanish speakers
- Merced
  - "Simplified online application process by requiring only name, contact information, and signature"
  - "Simplified verification submission process through the use of up-front imaging"
  - Re working poor: "increased presence at community events with goal of web-based application and telephone interviews are ways to reach out to this population"
- Monterey has some great benchmarks
![screen shot 2015-05-24 at 12 07 34 pm](https://cloud.githubusercontent.com/assets/2533112/7789196/7b29d882-020d-11e5-98b3-417efd242dfc.png)
- OC
  - "We intend to increase the utilization of Benefits CalWIN through additional education effort for the public and community based organizations"
- Placer
  - "Despite the best efforts of the anti-hunger partnerships in Placer County, there remainobstacles to participation. The confusion and complexity of the application process..."

**Comment by lippytak** [comment]
QUICK skims:
- Sonoma - null
- Stanislaus - null
- Tulare - null
- Ventura - null

**Comment by lippytak** [comment]
Santa Baraba
- "When clients don't provide all required verification it delays the application process...obtaining the required verifications along with the applicationw ill help eliminate the need for DSS to request it and will improve applicatoin processing"

Riverside
- One of the main components of the Business Process Standardization Plan: "Encouraging customers to apply on-line via C4Yourself in the comfort of their own home"
- "A second barrier...enhancements to the CBO portal that was established on the C-IV system...could help improve our CBO Assister approval rates."
