### ISSUE TITLE
CalWIN covers what % of CF households/persons?

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#267]
Can't find it. @daguar can you dig this up (or estimate it) for the grant? I think it was reference in the CDSS operational survey aka The Kiosk Measurement Infastructure: http://www.cdss.ca.gov/research/res/pdf/foodreports/CFSurvey1314.pdf

If not there we may have to look at participation by county in the dashboard http://www.cdsscounties.ca.gov/foodstamps/ and just add up the CalWIN counties.

**Comment by daguar** [comment]
I also think it's reasonable to do it by covered population.

**Comment by daguar** [comment]
Looks like:

C4 — 607,604 (31%)
LEADER — 555,795 (29%)
MBCW — 782,941 (40%)

**Comment by lippytak** [comment]
thank you good sir
