### ISSUE TITLE
Does C4 support verification doc upload?

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#268]
Does it, @daguar?

**Comment by daguar** [comment]
Yes, but it appears to be janky — see page 135 (PDF page 145) here: http://chc-inc.org/downloads/C4Yourself_EUG.pdf 

This is what the "My Documents" page looks like:
![screen shot 2015-05-27 at 10 54 08 am](https://cloud.githubusercontent.com/assets/994938/7843479/be2a2b98-045e-11e5-9d0d-5aa7dab9e2da.png)

And then uploading:
![screen shot 2015-05-27 at 10 55 17 am](https://cloud.githubusercontent.com/assets/994938/7843504/e122bdb8-045e-11e5-873d-65acc33e005f.png)

It only accepts PDF or TIFF files (I just tried a JPG to no avail)

**Comment by daguar** [comment]
Also, not sure where it actually is in the application flow — I think you are supposed to do it afterward through your account.

**Comment by lippytak** [comment]
Can you submit docs without creating an account? Can you submit docs during
the application or only after?

**Comment by daguar** [comment]
I check.

**Comment by daguar** [comment]
You need to register an account just to APPLY, so yes you do need an account to submit docs.

**Comment by daguar** [comment]
Document submission appears to be completely separate — they don't ask you for documents anywhere in the application, and afterward there's only a list of verifications the worker may ask for, no note that you can even submit them online, much less a link to do so.
