### ISSUE TITLE
Find confusing sentences/questions in C4 and LEADER

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#273]
@daguar and @alanjosephwilliams please pull out a few confusing questions/sentence here. Focus on things that are clearly not written in plain language (passive voice, double negatives, acronyms, legalese).

**Comment by lippytak** [comment]
Two ideas:
- @ajw let's call out the C4 homeless/required permanent address issue.
- C4 we can do signature
- I'll call that doc submission is Fd for LEADER

What else...?

**Comment by daguar** [comment]
Double-negative on the voting registration that you mentioned?

**Comment by lippytak** [comment]
I'm good on BCW:
- For example, MBCW offers the following introductory information for applicants applying for CalFresh only: “You can complete this application and request health insurance for you and your non-custodial child. However, CalHEERS will not be able to determine your non-custodial child's eligibility for Medi-Cal health insurance benefits.”
- MBCW uses both passive voice and double negative in a single sentence during the optional voter registration process: “NOTE: IF YOU DO NOT CHECK A BOX, YOU WILL BE CONSIDERED TO HAVE DECIDED NOT TO REGISTER TO VOTE AT THIS TIME.”
- MBCW allows users to submit a PO Box as their “permanent address” even though many counties in California will not accept this .

**Comment by daguar** [comment]
There's a basic issue with C4 which is that it makes the bizarre design decision to include all questions for all programs regardless of which ones you said you were applying for:

![screen shot 2015-05-28 at 4 23 09 pm](https://cloud.githubusercontent.com/assets/994938/7873333/fcd7c524-0555-11e5-9643-9a1f661c24e5.png)

**Comment by lippytak** [comment]
Fantastic observation. So basic I didn't even think to mention it. Will
definitely include this.
