### ISSUE TITLE
Confirm if BCW does/does not include 'income verifications' in doc upload

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#277]
I don't see it here: http://citizenonboard.com/snap/ca/#133

But *hopefully* that's because I didn't list any income sources in the application.

@daguar could you go through with sone income and see if there is an 'income verification' section in doc upload?

**Comment by daguar** [comment]
:+1: will do

**Comment by daguar** [comment]
It DOES ask you for income verifications if you put income in the app:

![screen shot 2015-05-28 at 5 39 05 pm](https://cloud.githubusercontent.com/assets/994938/7874143/7ce0117c-0560-11e5-9477-f76035a96f51.png)

**Comment by daguar** [comment]
More detail:

![screen shot 2015-05-28 at 5 39 53 pm](https://cloud.githubusercontent.com/assets/994938/7874153/949d398e-0560-11e5-987d-2cfdf3d7ac1e.png)
