### ISSUE TITLE
Quick research lit review on connection between usability > conversion

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#280]
DO IT. Drop notes here.

**Comment by alanjosephwilliams** [comment]
- Big report behind paywall, about ROI of usability improvements: http://www.nngroup.com/reports/usability-return-on-investment-roi/
- Applicability to governments and non-profits: http://www.nngroup.com/articles/government-non-profits-usability-roi/
- Our own government thinks usability has high ROI!:  http://www.usability.gov/what-and-why/benefits-of-ucd.html (includes a link to a great short video by Human Factors International)

These three have been selected among a handful of others for inclusion in the narrative, and are currently referenced in the footnotes.
