### ISSUE TITLE
How many CA area codes have used Balance?

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#281]
Measure of scaling/spread across CA.

**Comment by lippytak** [comment]
Or (easier to measure): How many unique area codes have had 1+ successful balance check on one of the CA numbers?

**Comment by daguar** [comment]
Used? By that we mean successful balance check, correct?

**Comment by daguar** [comment]
#querypedantry

**Comment by daguar** [comment]
Uh, hrm, so... yeah — all of them. :smile: 

To be explicit — we have had successful usage from every area code in California.

(I did this check manually, but we can automate numbers by area code in the future.)
