### ISSUE TITLE
Plan CWDA presentation

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#285]
BLUF:
- We've been working with SF to build a simple online application for CalFresh
- Now working with CDSS to try it out in other counties
- We would love to pilot with you...all we need:
  - Understand a bit about your county (approval rate, online takeup, doc submission)
  - MBCW CBO account (no need for C4)
  - Data access to evaluate (the funnel)
  - Some of your time  (and your EWs)

**Comment by lippytak** [comment]
Will have a little presentation ready at getcalfresh.org/join

**Comment by daguar** [comment]
FYI going to that right now I'm getting the normal Typeform application.

**Comment by daguar** [comment]
Probably a domain/SSL cert issue? Maybe let's use another?

**Comment by lippytak** [comment]
I havnt set up code or forward yet. Will do tnight.

**Comment by daguar** [comment]
Oooooo, sorry! Misread!

**Comment by daguar** [comment]
Awesome job! (closing for waffle cleanliness)
