### ISSUE TITLE
Write 2nd CDSS deliverable

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#288]
First step: What is it?

**Comment by lippytak** [comment]
![screen shot 2015-06-08 at 12 01 47 pm](https://cloud.githubusercontent.com/assets/2533112/8042762/3b545d2a-0dd6-11e5-9fc2-7750a2f1911e.png)

**Comment by alanjosephwilliams** [comment]
July 8th is hella soon

On Mon, Jun 8, 2015 at 12:02 PM, Jake Solomon <notifications@github.com>
wrote:

> [image: screen shot 2015-06-08 at 12 01 47 pm]
> <https://cloud.githubusercontent.com/assets/2533112/8042762/3b545d2a-0dd6-11e5-9fc2-7750a2f1911e.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/288#issuecomment-110108572>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by lippytak** [comment]
yeah dude why did we do this to ourselves?

**Comment by alanjosephwilliams** [comment]
We can discuss during sprint plan, but perhaps we can build this deliverable off of our recent onboarding meetings in Solano and Placer counties.

It would look something like:
- Comprehensive business process outlines with focus on online apps
  - complete business process write-up for San Francisco (mostly already delivered in our first report, but could be expanded upon).
  - complete business process write-up for Placer County
  - complete business process write-up for Solano County
- Partial business process documentation for other counties
  - Online Apps
     - Docs
     - AR
     - Partial apps
  - Scheduling and conducting Interviews
  - Handling Document Submission

**Comment by lippytak** [comment]
@alanjosephwilliams I think this is really interesting/important content but it just feels too far from the deliverable to me. I think we should do our best to deliver what we said, even if the outcomes aren't what we had hoped at the time of writing.

So here's what I would propose:
**BLUF** = , Clients love Balance, mixed on EBTNearMe due to data quality, and GetCalFresh.org has shown VERY promising potential meaningfully increase enrollment statewide (but we aren't there yet).

**Balance**
- Client surveys
- Usage/engagement stats
- A few select examples/quotes/stories (Pull from @daguar's health log on priming for trust)

**EBTNearMe**
- Client surveys
- Usage stats
- Bad data reports
- Select app reviews from Google Play store

**GetCalFresh**
- Summary
- Data/efficacy from ad impressions > clicks > applications > approvals
- Client feedback (conversion, time to completion, qualitative)
- EW feedback (summary from SF, Solano, Placer)

**Comment by lippytak** [comment]
@alanjosephwilliams @daguar Would love your thoughts? The goal here is to deliver something great without doing much extra/new work. I'll plan to flesh out a full outline by EOW and then block off real time next week to do the thing.

**Comment by alanjosephwilliams** [comment]
My only concern is fresh information from Balance and EBT-Near-Me, since our existing research was included in the first deliverable. I love the idea of going a little deeper on trust via Balance logs.

I think a really great GetCalFresh analysis sounds spot on, and its an opportunity to fold in some of that business process stuff.

**Comment by lippytak** [comment]
Yeah good point. At the very least we should be clear about what is old info and not emphasize it.

**Comment by daguar** [comment]
I've reviewed the outline (sorry for blocking for a day!) and I think it looks good. A few notes:

- Agree with you @lippytak that we should keep this somewhat close to the deliverable text — hit those points, but we can also include more
- Looking at the deliverable text, can you flush out the EW outline a bit more @lippytak? We focused on that, and I want a better sense of what you're thinking.
- Let's be sure to hit on the GetCalFresh metrics of:
  - Avg, variance, and distribution of *time to complete application*
  - Completion rates across devices
- I'd also suggest we add in what we're seeing as the pain points reported by clients (eg, the one who went to the office and was so confused that they just came back and messaged us)

**Comment by lippytak** [comment]
# BG
5) Collect and document user feedback from both eligibility workers and CalFresh applicants on how these online tools have impacted the user experience of the enrollment process

6) Collect and document data on if these online tools have increased CalFresh enrollment in the two counties

## BLUF
- Huge potential to increase enrollment with a simple online application for CalFresh (but interviews and verifications are hard)
- Clients love Balance (but want deposit alerts)
- Clients are looking for surcharge-free ATMs (but our data sucks)

## Enrollment process improvements

**GetCalFresh**
- GetCalFresh.org is a simple online application for CalFresh... (GIF)
- Impact [FUNNEL]
    + Conversion - Does it work?
        * Adwords - Are people looking? Yes
        * Adwords numbers
        * Cost of conversion
        * Across X counties
    + Significantly better client experience (compare to Caroline's preliminary findings)
        * Works on mobile (more accessible)
        * Faster (time to completion)
        * Some quotes (?)
- What we've learned
    + Clients
        * Lots of people looking on mobile
        * Communication channels
            - Reminder response rates (txt/email comparison)
            - Comm channel preferences
    + Counties
        + https://github.com/codeforamerica/health-notes/issues/20
        + https://github.com/codeforamerica/health-notes/issues/18
        + Most important thing is correct HH, ID, income
        + EWs complain about BCW usage on phones
        + Memory for Contra Costa
        + Challenges in existing application process
            * EWs don't use most info in the existing applications
        + Clearing: 5 points, consistent across counties
        + Interview
            * Clients get mad
        + ES screening
        + What is an awesome CalFresh application?
            * Moderates client expectations (benefit amount)

## Client experience improvements

### Balance
- Balance lets CalFresh and CalWORKS clients check their EBT balance via text message
- Impact
    + Usage
    + Engagement
    + Client surveys back this up https://docs.google.com/spreadsheets/d/14Am0UUXrl6jY4H9ZgOnPBwcO0axomLJtnVuvzcyAISk/edit#gid=1646147602
- What we've learned
    + Clients want deposit alerts (usage patterns at night)
    + Clients trust non-profit services
    + ?

### EBTNearMe
- EBTNearMe lets CalFresh and CalWORKS clients 
- Impact
    - Usage
    - Engagement
    - bit.ly/ebtnearme-metrics
    - https://docs.google.com/spreadsheets/d/1-nu-E-cTeQLPVm1jLyOmsOODgb_qVTHWRPKo1YnQCH0/edit#gid=1567370572
    - Select app reviews from Google Play store
        + Embeddedin LA DPSS official app
        + https://itunes.apple.com/us/app/dpss-mobile/id638516957?mt=8
        + https://play.google.com/store/apps/details?id=gov.lacounty.dpss.MobileApp&hl=en
- What we've learned
    + Lots of alternatives for finding EBT retailers
    + Adword data + client surveys = people want restaurants (and no good data)
    + Bad data (bit.ly/ebtnearme-feedback)

**Comment by lippytak** [comment]
Writing here: https://docs.google.com/document/d/1E35UnsxjsxSLu9KC_5L8o0C5OPwihVAfVXIgMY_Cg84/edit#

**Comment by lippytak** [comment]
Draft email:

>Will, Pete - 

> I'm happy to share our second CalFresh deliverable with you - a brief report on the impacts and lessons from our work to improve CalFresh. I'm very glad to have the chance to focus a bit more on solutions and a bit less on problems. Much of this work is still in the early stages so I'm excited to see how far we can take it together.

> As always please don't hesitate to reach out if you have any questions. You're welcome to email or ring my cell anytime at (510) 206-8727.

> With gratitude,
Jake and the Code for America Team

**Comment by alanjosephwilliams** [comment]
:clap: :clap: :clap:
