### ISSUE TITLE
Plan County onboarding

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#290]
- Agendas for prelim call + in person meeting(s)
- What data do we need before we start?
- Exact case tracking options/process

**Comment by daguar** [comment]
Let's consider making a hard ask around verifications — I'm not sure faxing is sustainable, and I think we should pave the road for a better way, even if it's just email for now.

**Comment by alanjosephwilliams** [comment]
There are specific county onboarding issues that are open and mature, so I'lm closing this.
