### ISSUE TITLE
Onboard Solano

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#292]
Next steps
- [x] Adwords UP
- [x] CBO account
- [ ] Add link to website
- [ ] Flyer to CBOs
- [ ] Flyer to other divisions
- [x] Case tracking

**Comment by lippytak** [comment]
We had a pilot planning meeting: https://github.com/codeforamerica/health-notes/issues/18

**Comment by lippytak** [comment]
FU done

**Comment by lippytak** [comment]
Once we have a flyer for CBOs I'll circulate and ping for website link.

**Comment by lippytak** [comment]
Staff identified for case tracking. Angela presenting to Director then we'll add link and circulate flyer.

**Comment by lippytak** [comment]
Angela decided to review this with council and have us do confidentiality agreements before having the county officially endorse. Reasonable but it will take a bit more time.

**Comment by lippytak** [comment]
Hi Angela, Hi Kelley,

I'm out for the next couple weeks (on vacation!) so just wanted to give you a quick update on the pilot and make sure you had Alan's contact info (CC'd).

1) We're live in Solano! We've had 9 CalFresh applicants in Solano so far, including a couple homeless individuals and one family of 5. It's taken an average of about 13 minutes for these folks to apply for CalFresh (one person did it in 5 minutes flat!) and it looks like at least one of them applied from their phone.

2) Let's start tracking. Here's a spreadsheet that we can use to track a little bit of data about these cases: [REDACTED LINK]

It would be fantastic if someone could review pending cases every week or two so we can keep an eye on approval rates and see if we need to change the website to help clients submit better applications (or let them know they probably aren't eligible). Since there is no PII in here I think we're totally kosher on privacy but of course let me know if you have any concerns. I'm happy to hop on the phone with the EW to answer any questions.

3) How's outreach coming? I know we're waiting to brief the council for the website (do you have an ETA?) but I wanted to pass along this outreach flyer. Feel free to use it, edit it, or send feedback to Alan and he'll do his best to incorporate it.

I think that's it for now...have a great couple weeks and talk soon!

Best,
Jake

**Comment by alanjosephwilliams** [comment]
no additional thoughts beyond those left on #301

On Wed, Jul 15, 2015 at 10:20 PM, Jake Solomon <notifications@github.com>
wrote:

> Hi Angela, Hi Kelley,
>
> I'm out for the next couple weeks (on vacation!) so just wanted to give
> you a quick update on the pilot and make sure you had Alan's contact info
> (CC'd).
>
> 1) We're live in Solano! We've had 9 CalFresh applicants in Solano so far,
> including a couple homeless individuals and one family of 5. It's taken an
> average of about 13 minutes for these folks to apply for CalFresh (one
> person did it in 5 minutes flat!) and it looks like at least one of them
> applied from their phone.
>
> 2) Let's start tracking. Here's a spreadsheet that we can use to track a
> little bit of data about these cases: [REDACTED LINK]
>
> It would be fantastic if someone could review pending cases every week or
> two so we can keep an eye on approval rates and see if we need to change
> the website to help clients submit better applications (or let them know
> they probably aren't eligible). Since there is no PII in here I think we're
> totally kosher on privacy but of course let me know if you have any
> concerns. I'm happy to hop on the phone with the EW to answer any questions.
>
> 3) How's outreach coming? I know we're waiting to brief the council for
> the website (do you have an ETA?) but I wanted to pass along this outreach
> flyer. Feel free to use it, edit it, or send feedback to Alan and he'll do
> his best to incorporate it.
>
> I think that's it for now...have a great couple weeks and talk soon!
>
> Best,
> Jake
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/292#issuecomment-121831950>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
