### ISSUE TITLE
Look into MEDA verification issues

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#298]
EWs "not getting" verifications. Liliana will get us some case info and I'll dig into it on Monday. I suspect EWs aren't scrolling down...

**Comment by lippytak** [comment]
Details: Submitted 2 cases on June 3rd. One went through normally. Second was "not found" for a while...then they found it? Missing verifications? Unclear what they have or don't have. Doesn't seem like a Clean issue to me. I'll call Mon AM to figure out whatsup.

**Comment by lippytak** [comment]
Emailed Cristobal

**Comment by daguar** [comment]
Looked into the case that MEDA said had no documents found by HSA.

Confirmed all docs were attached in the doc that went to HSA.

**Comment by lippytak** [comment]
BLUF: all good. Closing.
