### ISSUE TITLE
Onboard Marin

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#302]
- [ ] Link on website
- [ ] Get Alexandra up and running
- [ ] Share  other CBOs on July 30th (Coalition meeting)
- [x] Figure out case tracking
- [x] Adwords UP

**Comment by lippytak** [comment]
Marin has ~500 apps/mo with ~60% approval. Online uptake unknown.

**Comment by alanjosephwilliams** [comment]
@jake do we have  visit on the books for Marin that approximates what we have done in Solano and Placer?

**Comment by lippytak** [comment]
Marty is leaving. Replaced by Angela Struckmann.

**Comment by lippytak** [comment]
Alexandra is reviewing getcalfresh.org then we'll be good to go. Once we have a case submitted I'll ping about link on website.

**Comment by lippytak** [comment]
Still trying to get in touch with Intake specialist Stuart to talk about how interviews + verification submission works. Bleh.

**Comment by lippytak** [comment]
Need to ping Alexandra to make sure all is good and see if we can get started!
