### ISSUE TITLE
Kill Clean (forward users to GCF)

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#312]
1. saws1 issue
2. SF FB + MEDA uses in August (aim for ~50 apps)
3. Join coalition meeting Sept to share
4. Change cleanassist landing page to redirect with explanation and contact info

limitations
- manual processing = delay. we aim for same biz day
- no MC
- but now we do ES :)
- don't support real time events (maybe try EOY)

**Comment by lippytak** [comment]
Here's what I'm thinking:
1. You all review GetCalFresh.org at your leisure
2. We figure out an outstanding SAWS1/SAWS2Plus issue with HSA (apparently some MBCW apps come through as SAWS-1s and this causes problems)
3. You all start using GetCalFresh.org when it makes sense for you and your clients
4. Once we're settled and feeling good, I can join a coalition meeting and share with the other orgs
5. We'll put up a note on CleanAssist.org saying we've moved to getcalfresh.org + contact info

**Comment by lippytak** [comment]
Updated steps above. They want to use for the month of August + MEDA, then roll out to other CBOs probably in late Aug early Sept. Sounds good to me!

**Comment by lippytak** [comment]
Then plan
1. Food bank reviews
2. Start using in August + MEDA
3. Present to Coalition in ~Sept
4. Forward link from CleanAssist.org

**Comment by lippytak** [comment]
Ready to transition everyone!

**Comment by lippytak** [comment]
Pinged MEDA

**Comment by daguar** [comment]
I'm assigning this to myself, and it will now be to actually take down Clean.

**Comment by daguar** [comment]
FYI — SSL cert expires in January

**Comment by daguar** [comment]
FYI,
- 4 cases in September
- 4 cases in October
- 0 cases in November

**Comment by daguar** [comment]
@lippytak — do we want to renew the SSL certificate? (To keep URLs working and forwarding on.) Mike wanted to know, and it expires in mid-January. If not, probably a good time to start redirecting folks now to give some leadup.

**Comment by lippytak** [comment]
Yes we want to renew for 1 yr. @migurski can you renew cleanassist.org SSL cert? Any info you need from me?

**Comment by lippytak** [comment]
To do
- [] Push up 'goodbye' redirect branch to demo/prod
- [] Email CFO team + MEDA just in case
- [] Change master readme to say we're not actively developing it
- [] Set calendar reminder to kill the heroku apps in 6 months
- No rush on doing anything with 'clean-cases' spreadsheet because there's no PII

**Comment by lippytak** [comment]
Looks like this: 
![screen shot 2015-12-06 at 3 12 45 pm](https://cloud.githubusercontent.com/assets/2533112/11616278/e9dd7bd6-9c2b-11e5-8109-d2f531b6a347.png)

**Comment by daguar** [comment]
I've changed Clean to the free tier, which takes this from ~$100/mo to $0. cc @migurski

**Comment by daguar** [comment]
Also removed Airbrake ($9/mo) — keeping the $20/mo SSL on for now but we can/should remove at some point

**Comment by daguar** [comment]
Did the same for dev (was on $35/mo tier and had Airbrake; it does not have the SSL addon so it is now fully zero cost)

**Comment by daguar** [comment]
Set the demo instance to free tier
