### ISSUE TITLE
Email backlog

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#318]

**Comment by lippytak** [comment]
![screen shot 2015-08-05 at 3 17 29 pm](https://cloud.githubusercontent.com/assets/2533112/9099401/3fbf2688-3b85-11e5-8a41-e02ec90c436c.png)

**Comment by daguar** [comment]
<img width="588" alt="screen shot 2015-08-05 at 3 48 19 pm" src="https://cloud.githubusercontent.com/assets/994938/9099840/6fa6cd84-3b89-11e5-8dc3-0517beec0792.png">
