### ISSUE TITLE
Full pass on outcomes

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#319]

**Comment by lippytak** [comment]
We have 80 cases with no outcome data that are 40+ days old. I'm going to contact all of them. Will draft text here. We can do a double pass with LA IVR + use aggregate stats for C4 folks who don't respond.

**Comment by lippytak** [comment]
- Initial text messages

Hi, this is Jacob from GetCalFresh.org! You applied for CalFresh a couple months ago and we have one important question: Did you get approved for CalFresh?

Reply directly to this message and we'll text you a $5 Amazon gift code! And as always, let us know if we can help you get CalFresh. Thank you!

- Response if they reply with outcomes

Thank you! Your $5 Amazon code is [INSERT CODE]. You can redeem it at www.amazon.com/redeemgift.

Also, are you interested in a 15 min phone call to give your feedback on the CalFresh application process? We can offer a $20 Amazon gift code for your time.

- Adhoc scheduling/convo from this point on

**Comment by lippytak** [comment]
- Initial email

Hi! This is Jacob from GetCalFresh.org. You applied for CalFresh a couple months ago and we just have one important question for you:

**Did you get approved for CalFresh?**

Reply directly to this message and we'll send you a **$5 Amazon gift code**! And as always, please let us know if you have any questions about CalFresh.

Best,
Jacob and the GetCalFresh Team

- Response if they reply with outcomes

Thank you! Your $5 Amazon code is [INSERT CODE]. You can redeem it at www.amazon.com/redeemgift.

We would love to hear a bit more about your CalFresh application experience if you have time. Are you interested in a 15 minute phone call to give us some feedback on your experience? This will really help us improve the process for everyone else. We can offer another **$20 Amazon gift code for your time**.

Best,
Jacob and the GetCalFresh Team

**Comment by lippytak** [comment]
@alanjosephwilliams @daguar take a quick look at ^ and LMK if you have any edits. I'm going to get all these out tomorrow.

**Comment by alanjosephwilliams** [comment]
I think it reads really well. However—I strongly recommend batching the messages. I anticipate a not-insignificant support load to come with the responses.

**Comment by lippytak** [comment]
Great point will do

**Comment by lippytak** [comment]
All email/sms outcomes for folks who applied 40+ days ago. Now...we wait!

**Comment by daguar** [comment]
:+1: Sorry didn't catch the review ping here! But looks good to me.

**Comment by lippytak** [comment]
Current C4 stats:
35 pending
14 denied
14 active

**Comment by lippytak** [comment]
Last step: Look through CalWIN read for all SF cases.

**Comment by lippytak** [comment]
Done! 50% avg in SF and C4. Lots of 'not eligible' in SF.

~53% avg overall including self-report.

Had a ~30% response rate with $5 incentive.

**Comment by daguar** [comment]
Do we have common reasons for the ineligible?

**Comment by lippytak** [comment]
Have very limited data on denial reasons (mostly from SF):

case determination	determination date	denial reason	denial notes
denied		verification	CH: I didn't have time between work and school to get everything turned in on time 
denied	interview	Missed phone interview. Never called to reschedule.
denied		interview	4 Calls no answer
denied		interview	
denied		interview	
denied		interview	
denied		interview	
denied		interview	
denied		interview	
denied		interview	
denied		interview	
denied		ineligible	over income
denied		ineligible	over income
denied		ineligible	over income
denied		ineligible	not citizen/LPR
denied		ineligible

**Comment by lippytak** [comment]
Quick summary of denial reasons from a while ago...
![screen shot 2015-12-04 at 2 06 53 pm](https://cloud.githubusercontent.com/assets/2533112/11602594/528cacbc-9a90-11e5-95fe-118d815b4cdf.png)
