### ISSUE TITLE
DC tickets/hotel (for Dave)

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#322]

**Comment by alanjosephwilliams** [comment]
book for all of us!

**Comment by daguar** [comment]
Hold on the booking for me — I may want to stop somewhere else on the East Coast before or after.

**Comment by lippytak** [comment]
@daguar forwarded you the itinerary. Do as you please!

**Comment by daguar** [comment]
Reopening for myself

**Comment by daguar** [comment]
Done for me

**Comment by daguar** [comment]
Do we have a place to stay yet? Should I plan on getting one?
