### ISSUE TITLE
DC AirBnB

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#331]

**Comment by lippytak** [comment]
AC + hottub plz

**Comment by daguar** [comment]
Booking request sent for https://www.airbnb.com/rooms/6317776?checkin=08%2F23%2F2015&checkout=08%2F26%2F2015&guests=3&s=Kpm2

**Comment by daguar** [comment]
Blech they haven't gotten back to me yet

**Comment by daguar** [comment]
Have we heard back at all on timing of Oct DC trip?

**Comment by lippytak** [comment]
No and honestly I don’t want to go if we’re the ones pushing it. Getting pulled
is different and puts us in a different position. What do you all think?

On Thu, Sep 10, 2015 at 9:57 AM, Dave Guarino < notifications@github.com > wrote:
Have we heard back at all on timing of Oct DC trip?

**Comment by daguar** [comment]
I concur — I'd check in with @jennymt on this, but then I'd like to be able to cancel.

**Comment by davidrleonard** [comment]
Hmm, how'd I get on this? Enjoy your hot tub.

**Comment by daguar** [comment]
@davidrleonard I think you were accidentally assigned at some point. Don't worry about this, though you're always welcome in the hot tub.

**Comment by alanjosephwilliams** [comment]
no hot tub :/ https://www.airbnb.com/rooms/6738004

**Comment by lippytak** [comment]
Done @alanjosephwilliams?

**Comment by alanjosephwilliams** [comment]
done, location in Slack

On Mon, Oct 19, 2015 at 5:50 PM, Jake Solomon <notifications@github.com>
wrote:

> Done @alanjosephwilliams <https://github.com/alanjosephwilliams>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/331#issuecomment-149387813>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
