### ISSUE TITLE
What does the MBCW mobile app actually do?

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#337]
Nobody knows!

@carolinehays shall figure it out and report back!

**Comment by carolinehays** [comment]
Quick feature list, see google prez for screenshots and commentary.

1. Make an account through messy mobile adaption of mybenefitscalwin.org (lots of horizontal scrolling required)
2. Check your CalFresh and cash balance
* see CalFresh past transactions (last 30 days)
see payments into account w/ date available
see if a reporting form is due this month

**Comment by carolinehays** [comment]
Quick feature list of the "My Benefits" tab, see google prez for screenshots and commentary.

1. Make an account through messy mobile adaption of mybenefitscalwin.org (lots of horizontal scrolling required)
2.See case status
3. Check your CalFresh and cash balance
  * see CalFresh past transactions (last 30 days) 
  * see payments into account and date available 
  * see "reporting" - seems to be forms and when they are due, but somewhat unclear
4. Submit Docs!
  * to existing cases for different household members
  * "add to existing" - seems to be a way to add docs to "items submitted on MyBenefits CalWIN," so maybe pending apps? unclear
  * taking a picture is the only way to do this, can't upload a file

**Comment by lippytak** [comment]
@carolinehays awesome. Can you link to the google deck here?

**Comment by lippytak** [comment]
Nevermind I'm dumb: https://docs.google.com/presentation/d/150wlKqxMZzqdBHXMRc3MsnI6P76_PVKdky-eHsin6sU/edit

**Comment by lippytak** [comment]
OH BURN!

![screen shot 2015-08-27 at 8 23 07 pm](https://cloud.githubusercontent.com/assets/2533112/9538445/74d07234-4cf9-11e5-8d78-ab3776802ead.png)

**Comment by lippytak** [comment]
WUT.

![screen shot 2015-08-27 at 8 23 43 pm](https://cloud.githubusercontent.com/assets/2533112/9538453/8bba4970-4cf9-11e5-92c7-5af83d249ca5.png)

**Comment by lippytak** [comment]
Okay that was fun. Highly recommended journey.

**Comment by alanjosephwilliams** [comment]
Great work @carolinehays!

On Thu, Aug 27, 2015 at 8:25 PM, Jake Solomon <notifications@github.com>
wrote:

> Okay that was fun. Highly recommended journey.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/337#issuecomment-135623186>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
Super well done @carolinehays.

@lippytak — Let's maybe package this up and send to all our core partners/contacts? Highly doubt any of them have seen this, and it would be a nice way to give _them_ some value and feel-goodness.
