### ISSUE TITLE
Q4 OKRs 

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/health#338]
Per Cyd's request, when she returned from vacay. Makes sense to turn to after we present a budget to Jen et al.

Should probably include:
- "The Great Q4 Flight to Quality" aka focus on product after the Race to 1000 ends
- Fun as hell research on the EW side in SF, San Diego, et al
- Begin hiring process to try to land 1st hire by Q1
- Prepping for jurisdictional expansion in Q1

**Comment by lippytak** [comment]
deprecated
