### ISSUE TITLE
(Defunct) Upgrade from Cedar-10 to Cedar-14

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#339]
> The following apps which have received traffic recently, that you own or are collaborated on, currently run on Cedar-10:
 
[ALL OUR APPS]
 
To migrate an app, run the following commands:

``` 
$ heroku stack:set cedar-14
$ git commit --allow-empty -m "Upgrading to Cedar-14"
$ git push heroku master
```

Details: https://devcenter.heroku.com/articles/cedar-14-migration

**Comment by daguar** [comment]
Moving this to current sprint because end of life is Nov 4th (tomorrow)

**Comment by lippytak** [comment]
Dup of #282

**Comment by daguar** [comment]
Punting on this since we can shave the yak in a JIT way next time we need to push (that's when it blocks you on the upgrade)
