### ISSUE TITLE
Investor letter

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#345]
(stakeholder update)
- update outcomes first

**Comment by lippytak** [comment]
- Summary of outcomes
- Funnel
- Quotes
- Problems (saws 1/2)
- mo' cases mo' places
- connecting with advocates
- how MBCW works
- link to public user interviews!

**Comment by daguar** [comment]
I assume the "how MBCW works" is @carolinehays's sweet walkthrough of the MBCW stuff but if not, let's add that!

**Comment by lippytak** [comment]
Dumping ground
===

The Numbers
- Nearing 800 applications submitted through GetCalFresh.org
- 60% approval rate
- Avg of 11 mins
- About 1/3 on mobile devices (phones or tablets)
- About 2/3 of applicants submit verification docs through GetCalFresh.org
- 40% of denials are due to the client not being eligible (mostly over net income), 35% were due to missed interviews, and 25% were due to missing verifications
- Proud to say we have five wonderful partners :)

Feels
- We try to talk to as many users as possible to understand their experience (the good and the bad) trying to enroll in CalFresh. Our notes are public: https://docs.google.com/spreadsheets/d/147TjVMTNPuVW797gAm4xBBN1x5aFDJ-p-IsA6QIu6fU/edit#gid=380838830
- "What surprised me was that it was a pleasant process as opposed to being a bummer."
- "Every time I tried to call case worker she left tons of voicemails and she never called you back."
- "Yours was way easier because there was less questions and it was just CalFresh. The other one there was pages and pages of questions and different questions you have to answer for different benefits. You also had to make a signature and do like 3 steps. It took me like 2 hours just to do that one. Yours was pretty easy."

What's next?
- Better reminders to help people get their phone interviews
- Learn how error rates work so we can (hopefully) help reduce them
- Fundraising for 2016. If you have ideas/contacts at foundations or potential individual donors, please email me directly. And expect me to be reaching out to solicit your ideas!

PS. Here's how MBCW works. Just in case you're curious. Note you can't apply for CalFresh.

**Comment by lippytak** [comment]
**Numbers**
- We're nearing 800 applications submitted through GetCalFresh.org with a 60% approval rate
- Applicants are taking an average of 11 minutes to submit an application and about 1/3 of applicants are on mobile devices
- About 2/3 of applicants submit documents through GetCalFresh.org
- 40% of denials are due to the client not being eligible (mostly over net income), 35% were due to missed interviews, and 25% were due to missing verifications
- And I'm proud to share that we now have five wonderful partners: San Francisco, Marin, Contra Costa, Solano, and Placer!

**Feelings**
- We try to talk to as many users as possible to understand their experience (the good and the bad) trying to enroll in CalFresh. You can see interview notes here: https://docs.google.com/spreadsheets/d/147TjVMTNPuVW797gAm4xBBN1x5aFDJ-p-IsA6QIu6fU/edit#gid=380838830
- A few select quotes

> What surprised me was that it was a pleasant process as opposed to being a bummer.
 
> Every time I tried to call case worker she left tons of voicemails and she never called you back.

> Yours was way easier because there was less questions and it was just CalFresh. The other one there was pages and pages of questions and different questions you have to answer for different benefits. You also had to make a signature and do like 3 steps. It took me like 2 hours just to do that one. Yours was pretty easy."

**What's next?**
- Personalized reminders to help people finish complete their phone interviews
- Learn how error rates work so we can (hopefully!) help reduce them
- Fundraise for 2016! If you have any ideas/contacts for potential funders interested in expanding access to SNAP (foundations or individuals), please reach out to me directly. Your thoughts are MUCh appreciated so thank you in advance!

**Comment by lippytak** [comment]
Done with all county/external peeps

**Comment by lippytak** [comment]
Done with county/external folk. Going to writeup health-notes and call it done.
