### ISSUE TITLE
Start SD pilot

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#349]

**Comment by alanjosephwilliams** [comment]
what's next

**Comment by lippytak** [comment]
- email rick about MOU
- email SD211 with info/tools (and setup call to identify a GCF use case for them?)

What do y'all think?

**Comment by daguar** [comment]
Those sound good to me — I also replied to Rick's asking for the phone number of our quick Connect SD deploy.

**Comment by lippytak** [comment]
Dropbox done

**Comment by lippytak** [comment]
Scheduled calls next week w Hunger coalition + SD211. Done with this for the week.

**Comment by lippytak** [comment]
Three distribution strats to try with SD 211:
1. Their enrollment specialists use GCF instead of MBCW. They'll plan to start 2-3 staff on Tues Jan 26th.
- We'll have to be able to attach wav/mp3 files (voice sig) in MBCW for initial apps
2. Social media marketing with a custom URL - they do shtuff like this
3. Print marketing at community events with custom URL

For all of these we'll have to figure out a way to share aggregate outcome data by source

**Comment by alanjosephwilliams** [comment]
I can run point on producing some outreach materials—the social media and print stuff. The only blocker is a custom URL. We've discussed a few different approaches in the past, so let's pick one.  Any reason not to go with getcalfresh.org/sandiego?
