### ISSUE TITLE
Process food bank feedback

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#354]
- Very quick
- No big problems
- Don't know which questions are about ES
- Contra Costa migrant farm worker
- Estimated medical expenses....
- Do people get ES?
- Questions flowed all
- Bernal Heights Neighborhood center = get their own ID
- Have BCW account but don't use it
- Laura of MEDA loves Clean > 
- Confirmation for YOU
- Check consent from text messages and what messages CalWIN 
- Question 21 - 
- Couldn't find. Limited IDs to 4? Or something
  - ~20 of each doc type
- "More fun than benefits CalWIN"
- "Feels like you're playing a game whereas MBCW feels like actual work."
- Other languages. Confirmation #.
- Cindy would actually want to empower them to do it themselves. > Importance of new languages.
- Are these apps being processed by outreach unit or?

**Comment by lippytak** [comment]
Issues:
- Specify which questions are ES https://github.com/codeforamerica/getcalfresh.org/issues/245
- More than 4 IDs https://github.com/codeforamerica/getcalfresh.org/issues/244
- Transition MEDA Clean > GCF https://github.com/codeforamerica/health/issues/312

**Comment by alanjosephwilliams** [comment]
Love this so much:

"Feels like you're playing a game whereas MBCW feels like actual work."

On Sun, Sep 6, 2015 at 2:59 PM, Jake Solomon <notifications@github.com>
wrote:

> Closed #354 <https://github.com/codeforamerica/health/issues/354>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/354#event-402252091>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
