### ISSUE TITLE
Guide to interview Will L during summit

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#357]
- Intro
- Questions/topics
- Review with Will/priorities for him
- If/how to do audience questions

FYI @daguar @alanjosephwilliams instead of a solo presentation I'm going to interview him. Would love to brainstorm good questions/topics in the next couple weeks.

**Comment by lippytak** [comment]
Starting brainstorm
===


- Intro/bg
  - HSA director SF, Santa Cruz, Santa Clara
  - Director Catholic Charities in SF
  - Summarize programs/impact and what they did in 2014
  - There is no more important job in California

- Why are you here? What do you see in this community and this work? What do you hope will happen?
  - Begin story
  - You and Trent Rhorer...0 from social services just a couple years ago

- What do you see as the big opportunities for better digital services/service design? What are some changes you hope to see over the next 5-10 years?
  - CalFresh work, foster care transformation

- What are the specific challenges to delivering excellent social services (digital or not)?
  - Lots of stakeholders (state, county, consortia, advocates, 
  - Clients/customers are economically/politically disenfranchised (vs. DMV - no advocates + even CEOs and politicians have to go)

- We've seen consistent disconnect between policy and delivery. Do you observe that as well? What could we do about it? What tools/views would support leadership in bridging this gap?

- What else do you think is important for this audience to know? Lots of young professionals in the room...what's one thing you wish you knew when you were 30?

- Thank you. Personal story/makes you want to be better.

**Comment by MatthewLoveless** [comment]
Failed gov it projects: 
LA USD Student Information System: http://www.latimes.com/local/education/la-me-lausd-software-20141012-story.html
Cover Oregon: https://en.wikipedia.org/wiki/Cover_Oregon

**Comment by lippytak** [comment]
https://twitter.com/niki_virani/status/646020754702602240

**Comment by lippytak** [comment]
1) Why are you here today?
What did you see in this community and this work that resonated with you and where do you hope it will go in the future?

2) What do you see as the biggest opportunities for better government digital services in the next 5-10 years?
What would a digital-first social service program look like? What are you/CDSS doing to get there? Feel free to pull 1-2 examples from the CDSS portfolio and go deeper on current challenges you're facing. I'd really love to get into some of the big upcoming shifts in foster care and what problems/solutions you see.

3) What are some specific challenges to delivering excellent social services (digital or not)?
Social services are not like the DMV…there are many disparate stakeholders (feds, state, county, advocates, vendors, clients, etc.) and we serve some of most vulnerable and hard-to-reach populations. What are the unique challenges?

4) What tools/views would help you (or leadership generally) in bridging the policy/implementation gap?
At CfA we've seen a consistent disconnect between policy as-written and policy as-implemented. Examples include low take-up of Prop 47 (felony expungement), EITC, CalFresh, Federal student loan refinancing options, etc. Do you see this at CDSS? What can we do about it?

5) How can advocates / outsiders be effective in improving the delivery of government services?
Since you have both the outside (Catholic Charities) and inside government perspective, I would love to know how you think external stakeholders like advocates can be most effective. There will be lots of tech saavy advocate types in the room.

6) What is one thing you wish you knew when you were 30?
Or more generally - is there anything else that you think is important for the audience to know? For context there will be lots of young professionals in the room starting careers in technology, government, and the intersection.
