### ISSUE TITLE
Summit presentation

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#371]
Assets
- [ ] Screenshot or GIF of Balance 
- [ ] Screenshot or GIF EBTNM
- [ ] Screenshot or GIF of the GCF Homepage (Desktop, with photo)
- [ ] Screenshot or GIF, uploading Docs from a phone
- [ ] Screenshot: Timeout on MBCW
- [ ] Screenshot: MBCW or C4 on Mobile
- [ ] Icon that can be repeated for 50 People on a single slide
- [ ] GIF or Screenshot of GCF live support

Things to make:
- [ ] Image: Diagram of Chaos Phone Tree
- [ ] Image: The "Delivery circle "
- [ ] Image: Policy –> Implementation line, or waterfall
- [ ] GIF: A supervisor discusses prop F on Slack
- [ ] Mockup: Push notifications asking you'd like an escort
- [ ] GIF: SMS for foster care
- [ ] GIF: Email about Unemployment Benefits
- [ ] Mockup: Enroll in SNAP when you have a low Balance at the Point of Sale

Other to do:
- [ ] Names of The Big TEAMMMM!
- [x] Edit and slow down all app-videos
- [x] Redo balance mov on iphone 6s
- [ ] Turn auto play on all media slides
- [ ] Make address thing a scrolling GIF (meh, have the vid, not sure if I want to use it)
- [ ] Remove custom fonts (fyi @alanjosephwilliams  since presentation comp won't have them)

**Comment by lippytak** [comment]
NOTES!
===
BIG US GOV IT FAILURES
- DMV
- VA
- 


POLICY DELIV GAP
- SNAP
- Prop 47
- 

THE REAL COST (what it could be)
- Foster care
- SNAP comes to you. No more "applications." Truly automatic stabilizers.
- Open source eligibility
- 

"The poorer the person, the more he or she is likely to be the non voluntary client of not one but several street-level bureaucracies"


Our role: We are witness to critical role of public systems in civic life

5.3 million teachers, 1 million police, over 500k public welfare

“It was only in the mid-1960s that political scientists began to focus on the now-obvious point that the passage of laws and the promulgation of regulations did not fully encopass the policy-making process. On the contrary, as we now take for granted, policy is only finally made when laws or regs are fully implemented, through subsequent processes that cascade from the initial declarations" - Street level bureaucracy

Implementation is not a phase, but a process (called Delivery)

Accessing many public services remains a series of small indignities

Organic government. Responsive. Flow. Government is not the stable long-lasting thing. Fluid. 

- Transaction costs LOW. Transactional services become services.

A foster care system where every kid has a phone and gets a message every day to make sure everything is going okay.

A SNAP system where you don't apply. It's an automatic stabilizer.

It's a safety net.

We can build a safety net that lifts you up doesn't tie you down.

Policy / delivery gap examples

Overall happens from the inside out.

User needs is the organizing principle.

No more overhauls.

"You are underestimating the compounding awesomeness of continually fixing small broken things.    @rands"

Open source eligibility project.

Websites down

Start at the core and work your way out

There is no playbook for improving government service delivery.

Services are sexy.

Digital transformation of government provides the opportunity to design government services for the first time.

If it doesn't happen now, we won't have another opportunity in our lives.

No longer policy, but government service delivery that is the next frontier for social impact in the United States.

We have gotten the policy RIGHT.

It's not about what. It's about HOW.

Build buildings out of bandaids.

Mike GDS digital transformation

Delivery crisis.

The status quo is an emergency.

WE have failed. RFPs, gov staff, vendors, voting public.

Courage and persistence to break bureaucracy.

http://mikebracken.com/blog/the-strategy-is-delivery-again/

CHAOS report https://www.projectsmart.co.uk/white-papers/chaos-report.pdf

"But there is another difference between software failures and bridge failures, beside 3,000 years of experience. When a bridge falls down, it is investigated and a report is written on the cause of the failure. This is not so in the computer industry where failures are covered up, ignored, and/or rationalised. As a result, we keep making the same mistakes over and over again"
Our bridges are falling down...just so slowly that it never makes the news.

THIS ISN'T THE COST. THE REAL COST IS THE CHANCE TO BUILD A NEW TYPE OF GOVERNMENT. SOLVES PEOPLES NEEDS. FOOD STAMPS THAT STABILIZES THE MOMENT YOU GET YOUR LAY OFF NOTICE. WHEN YOU MOVE ACROSS THE BORDER...DIVORCE PAPERS.



Our government provides the most important services to the most vulnerable people at their most vulnerable times. And that’s why we’re here — to work on stuff that matters. Join us!

"When HealthCare.gov crashed for middle class Americans it was a crisis. But in the social safety net, the status quo is crisis."

"emergencies with no urgency"

"Your website shouldn't have more days off than you do."

Everything we do is service delivery
Everyone is on a service delivery team

Respect costs less
Policy happens between people
User needs
User needs are human needs
How vs what

BOTTOM UP POLICY-MAKING/ Delivery-driven policy
Fraud and waste...$50B!
Technology reports to digital
Organize differently. User needs is the organizing principle
Apps > opps (no...to services)
Needs lead you through the service

Examples
Example (federal): $3T of student loan debt not refinanced because IBR website is so bad (unusable website)

Our Strategy is Delivery. Policy Must Serve Delivery
Hands not voices
Gov efficiency = social justice
Government services are our social services
There are holes in our safety net
Policy in service of user needs
Law in service of user needs
Operations in service of user needs
Software in service of user needs
GOVERNMENT IN SERVICE OF USER NEEDS (HUMAN NEEDS)
Governments must go from being policy-driven, to being user-driven.
The organizing principle of government services.

Governments must create new organizational structures and cultures to replace ones where policy makers are at the top and implementers at the bottom, with little communication between the two.

We must require policy and delivery to be fundamentally connected and responsive to results.  Linear processes that move from policy to implementation and then stop must give way to iterative processes centered around users’ needs.

Digital transformation of government

Circles over lines

**Comment by lippytak** [comment]
http://mikebracken.com/blog/the-strategy-is-delivery-again/

"But in the case of public service provision, it is too often a completely closed loop, the ultimate insider job."

"Delivery based on user need is like kryptonite to policy makers and existing suppliers, as it creates rapid feedback loops and mitigates against vendor lock-in."

**Comment by lippytak** [comment]
User needs are the fulcrum.

![screen shot 2015-09-21 at 11 16 01 am](https://cloud.githubusercontent.com/assets/2533112/10000667/72675794-6052-11e5-9ae3-db134d34435a.png)

**Comment by lippytak** [comment]
Big fails
- In 2007, DMV hired blablabla to build blablabla. After X years and Y dollars. They gave up.
- In 2010, VA hired bilabial to build blablabla. After X years and Y dollars they gave up.
- [ONRE MORE]
$XB is a lot of money. But that's not the cost.

This isn't the cost. The true cost is the missed opportunity to do the digital transformation of government services.
- SNAP that happens automatically when you need it
- Unemployment that comes with your lay off notice
- Foster care that works like CTL
- Open source eligibility
We are missing our chance to realize the digital transformation of gov.

Policy is not the problem
- CalFresh policy WINS (long list)
- And STILL, 40% of people don't get it...
- This is about implementation (not delivery?). Not policy.

Implementation is a process, not a phase (called delivery)
- Policy > implementation > ??
- Some circle thinggg

> Talk through our work in this context.

**Comment by lippytak** [comment]
Users bear the burden when navigating gov services. Especially the poor, the young, the old, the disabled, the undocumented, the vulnerable.

**Comment by lippytak** [comment]
We're missing a huge opportunity.

We're still implementing instead of delivering.

Implementing is a phase. Delivering is a process.

Delivery = the continual process of understanding & addressing user needs.

**Comment by lippytak** [comment]
User needs radiate outwards.
ripple
waves
build momentum as they go

**Comment by daguar** [comment]
Love the "implementation vs delivery" concept. Compelling to me.
