### ISSUE TITLE
Ask Hali for training instance or screenshots + heads up about SD + SAR-7

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#380]

**Comment by daguar** [comment]
Even more specifically, let's ask for screenshots for what it looks like with a BCW app (since it appears to be a separate window where you need to import, and I think we'd benefit from understanding specifically what our EW users experience)

**Comment by lippytak** [comment]
just going to give her a heads up about SD but not really comfortable asking her for things ATM

**Comment by daguar** [comment]
Agreed 👍
