### ISSUE TITLE
Connect for SD

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#381]
- [ ] Get voice file from Rick
- [x] Record new audio
 - [x] New loop just for SD (pre-Rick)
 - [x] More generic intro audio ("your county CalFresh office...")
- [x] Figure out button sequence
- [x] Get county phone #  — 866-262-9881
- [x] Fork and change voice URL
- [x] Upload new initial call audio file to S3
- [x] Upload SD specific file
- [x] Set up new phone # 
- [x] Deploy
 - [x] Set config variable for San Diego audio
 - [x] Set config variable for button sequence
- [x] Test

### Later:
- [x] Migrate to billing@
- [ ] Move to connect production subaccount

**Comment by daguar** [comment]
@lippytak Semi-blocked on your phone #

**Comment by daguar** [comment]
Emailed Rick

**Comment by daguar** [comment]
Broke out tasks in a more fine-grained way

**Comment by daguar** [comment]
New audio recordings done

**Comment by daguar** [comment]
Punting on Rick's audio for now

**Comment by daguar** [comment]
Done with audio and uploading

**Comment by daguar** [comment]
A shitton done — it is working with just calling our phones!

**Comment by daguar** [comment]
Button sequence: wwwwwwwwwwwwwwwwwwwwwwww1wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww1wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww4wwwwwwwwwwwwww#ww

**Comment by daguar** [comment]
First call out the door — expected 10-20 min wait, we'll see!

**Comment by daguar** [comment]
TESTED! IT WORKED!!!

**Comment by daguar** [comment]
Transferred to CFA account (it still sleeps)

**Comment by daguar** [comment]
Closing this because it's functionally done — the next step would be going live, which is a separate process
