### ISSUE TITLE
Balance SD number

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#382]
Let's do this and deliver on Friday — DELIVERY MOFOS

**Comment by lippytak** [comment]
Oooh, could we rush order today?

**Comment by daguar** [comment]
@alanjosephwilliams How could we do cards? Thoughts?

**Comment by daguar** [comment]
English: (619) 356-2921
Spanish: (619) 356-2784

**Comment by daguar** [comment]
@lippytak — Maybe put this in prezo? Assigning to you because I think "deliver" is the last piece.

**Comment by lippytak** [comment]
![balance](https://cloud.githubusercontent.com/assets/2533112/10383229/2b730c6a-6de1-11e5-8c95-419dfabd8390.jpg)

**Comment by alanjosephwilliams** [comment]
Let's ship them 1000 cards. I'll put in an order today.

On Thu, Oct 8, 2015 at 5:22 PM, Jake Solomon <notifications@github.com>
wrote:

> [image: balance]
> <https://cloud.githubusercontent.com/assets/2533112/10383229/2b730c6a-6de1-11e5-8c95-419dfabd8390.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/382#issuecomment-146723797>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
Might be good to check in with Rick since he's wanted a bit of consulting on some of this stuff I think
