### ISSUE TITLE
Find Ren a client to chat with

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#383]
$50 incentive is okay

**Comment by alanjosephwilliams** [comment]
Is this time sensitive?

**Comment by alanjosephwilliams** [comment]
10 more clients pinged today.

On Mon, Oct 26, 2015 at 2:20 PM, Jake Solomon <notifications@github.com>
wrote:

> Assigned #383 <https://github.com/codeforamerica/health/issues/383> to
> @alanjosephwilliams <https://github.com/alanjosephwilliams>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/383#event-446083306>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
