### ISSUE TITLE
CalFresh journey asset

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#395]
No particular rush but I'd love to have something like this in a more visual/linear form.

![screen shot 2015-10-20 at 4 55 37 pm](https://cloud.githubusercontent.com/assets/2533112/10624251/6c7f7428-774b-11e5-823d-eed836eb5552.png)

**Comment by alanjosephwilliams** [comment]
![image](https://cloud.githubusercontent.com/assets/2983464/10624343/621d469e-774c-11e5-85b6-9007654448c3.png)

**Comment by lippytak** [comment]
Are you just teasing me?

**Comment by alanjosephwilliams** [comment]
health > CANONICAL-MEDIA > static assets > funnel_default

we should update it to be more clear about NOAs, SAR-7, RRR, etc.

**Comment by lippytak** [comment]
Ahh, yea could include that. I also use this to make the point about fractured ownership (friends, feds, HP, county, xerox, etc.) so that would be another thing to incorporate.

**Comment by alanjosephwilliams** [comment]
@lippytak we have the illustrator file — we could pretty easily do a version about fractured ownership. just about priorities.

**Comment by alanjosephwilliams** [comment]
in other words, just say the word if you want it.

**Comment by lippytak** [comment]
:+1: consider word not spoken quite yet!

**Comment by alanjosephwilliams** [comment]
It's time. Moving to this week's Meditative Walk.
