### ISSUE TITLE
TY cards for WH peeps

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#397]

**Comment by alanjosephwilliams** [comment]
- [ ] Luke
- [ ] Katherine
- [ ] Farrah
- [ ] Ginny / Lucy

Others?

20 postcards ordered from Moo, should arrive at CfA on Tuesday.

On Sat, Oct 24, 2015 at 3:21 PM, Jake Solomon <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/397>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by alanjosephwilliams** [comment]
Cards have arrived, just have to write them. Happy to do this over the weekend and send Monday.

**Comment by lippytak** [comment]
Meh too late
