### ISSUE TITLE
Outcomes spike!

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#401]
- Get all new conf #s into spreadsheet
 - [x] Solano
 - Contra Costa (not doing — no updates)
 - [x] Placer
 - [x] Marin
- [x] Ping county contacts in Placer, Solano, and Marin 
 - [x] Solano
 - [x] Placer
 - [x] Marin
- [x] Set up SF tracking doc inside workbook for team manual entry
- [x] Process existing, unprocessed outcomes from county tracking into master doc
 - [x] Solano
 - [x] Placer
 - [x] Marin
- [x] Data cleaning (Dave leads, can distribute)
- [x] Clean up input fields in county tracking for consistency (can tell Jake to do)
- [x] Quick research on distribution of ineligible details (what % income, active case, did not clear, etc.)

**Comment by daguar** [comment]
First step, get all new conf #s into tracking, and then ping the counties to update

**Comment by daguar** [comment]
Contra Costa :hocho: :panda_face:

**Comment by daguar** [comment]
Solano already up to date

**Comment by daguar** [comment]
Placer conf #s migrated

**Comment by daguar** [comment]
Marin conf #s migrated

**Comment by daguar** [comment]
Added
- [ ] Ping county contacts in Placer, Solano, and Marin

**Comment by daguar** [comment]
Added:
- [ ]  Process existing, unprocessed outcomes from county tracking into master doc

**Comment by daguar** [comment]
Solano outcomes processed, a fair number of denials... (2 interview, 3 verification)

**Comment by daguar** [comment]
Pinged Solano contacts

**Comment by daguar** [comment]
@lippytak — what's our process for cases whose statuses may change? (Specifically I'm thinking of denials due to verification where the client turns them in later.)

**Comment by daguar** [comment]
Pinged Placer

**Comment by daguar** [comment]
Jake pinged Marin (thanks Jake!)

**Comment by lippytak** [comment]
- Why are people getting denied?
- Are there important differences by county?
- Are we making the right call re investing in income screening?

**Comment by daguar** [comment]
Master doc has Placer and Marin (auto-updating) along with Solano — pulls in from county tracking data

**Comment by daguar** [comment]
Have set up a SF tracking tab for us to do outcome lookup on — note: we fill out the YELLOW columns:

<img width="611" alt="screen shot 2015-11-06 at 12 13 40 pm" src="https://cloud.githubusercontent.com/assets/994938/11007604/ea514fb6-847f-11e5-83e1-8624b28376bf.png">

**Comment by daguar** [comment]
I have also assigned people in the `San Francisco` tab for our group outcomes pass today:

<img width="494" alt="screen shot 2015-11-06 at 12 24 13 pm" src="https://cloud.githubusercontent.com/assets/994938/11007814/59e67f9e-8481-11e5-87d5-e7934f9bc05d.png">

**Comment by lippytak** [comment]
fyi @daguar I added one last thing above before closing out this issue: 'Quick research on distribution of ineligible details (what % income, active case, did not clear, etc.)'

**Comment by daguar** [comment]
One  more SF  outcomes pass today 230-330, cal invite sent

**Comment by daguar** [comment]
It does look like it goes:
- Verifications
- Interviews/eligibility

as the big denial reasons

<img width="313" alt="screen shot 2015-11-13 at 2 31 55 pm" src="https://cloud.githubusercontent.com/assets/994938/11160881/55840206-8a25-11e5-9603-20da77794b90.png">

**Comment by daguar** [comment]
@lippytak To your question of the "ineligible breakdown", here's what I've calculated (manual count):

26 — over income
7 — not eligible during first 2 months (or “ineligible in the first and second month”) — these are all Solano County
3 — immigration/not citizen/LPR (note: these were mostly early cases)
3 — student ineligibility
2 — active on other case
1 — SSI/SSP
1 — “Not a separate household”

(Note: these include both denials and withdrawals)

**Comment by daguar** [comment]
Added 'composite details' column which shows (a) county detailed denial explanation, or (b) our own denial details we've input.

**Comment by daguar** [comment]
Finished with the useful data cleaning (it's how I consolidated Level 1 denial reasons above)

**Comment by daguar** [comment]
I have cleaned up the validation fields to be consistent across the various tracking columns

**Comment by daguar** [comment]
Crosstabbing denial reasons with counties, here's what we find:

<img width="383" alt="screen shot 2015-11-13 at 5 01 14 pm" src="https://cloud.githubusercontent.com/assets/994938/11161054/3ccac864-8a28-11e5-9ae4-dc06e9f4b1f9.png">

- Placer: verifications are dominate (~55%)
- Marin: interviews are biggest (~45%)
- SF: pretty even split interview/verifications/eligibility
- Solano: eligibility (~37%)

**Comment by daguar** [comment]
That said, The Big 3™ really are what we have to solve, and roughly in equal portions — let's get to it.
