### ISSUE TITLE
Decide on Pivotal allocation

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#405]

**Comment by alanjosephwilliams** [comment]
What needs to be done and what is the required turnaround for FU?

**Comment by lippytak** [comment]
sent - next step is to talk to Richard to understand tradeoffs then make a decision on cash/people allocation

**Comment by lippytak** [comment]
Scheduled for next Wed

**Comment by lippytak** [comment]
All engineering (team of 3-4 full time for ~6mo) to start somewhere in Q1 depending on best timing for both parties.

**Comment by daguar** [comment]
@lippytak One clarification — I interpret this to mean we have the BANDWIDTH-EQUIVALENT of 3-4 FT people for 6 months. Would we be able to spread that over a year? (I think that would be useful.)

**Comment by lippytak** [comment]
Correct, though we probably don't have full control over the allocation because it will depend on how their usual pivotal process works.

**Comment by alanjosephwilliams** [comment]
@lippytak what is the next step on this?
