### ISSUE TITLE
Research missing Placer docs

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#407]
What's the root cause?

**Comment by daguar** [comment]
Taking this so Alan can focus on user search

**Comment by daguar** [comment]
Here's what we know:
- The attachments appear to be included in the secure email forward that Placer clerk is sending to us
- This issue appears to correlate with them moving to a secure email system
- Confirmed that the attachments were included in the outbound emails (at least as they appear there)

**Comment by daguar** [comment]
Emailed the Placer email address with details

**Comment by daguar** [comment]
Confirmed with a test to my Gmail from Front that Front attachments are working

**Comment by daguar** [comment]
@lippytak Would me emailing Logan be the best option here? Assuming we don't hear back from the records clerk.

**Comment by daguar** [comment]
Attachments are coming through to them when sent from Gmail, but do not appear to be working with Front.

I'm testing one more Front email, this time directly to Kelly's email.

**Comment by daguar** [comment]
As a temporary stopgap, I'm emailing the currently pending ones from Gmail (and deleting there).

**Comment by alanjosephwilliams** [comment]
This research has concluded, yes?

Going forward we send docs later to Placer via the encrypted email service? This might be a good opportunity to discuss docs later through MBCW with Placer too, right?

**Comment by daguar** [comment]
Research concluded? — yup!

Also yes to using encrypted email service for Placer moving forward — I've updated the county contact spreadsheet with that info, and credentials for our account are in the creds doc.

RE docs later, I think you're right — I'll ping Logan.

**Comment by daguar** [comment]
Actually, I'm going to hold off on pinging Logan re MBCW doc uploader for now until we're at the point of wanting to use that — the big reason is that thing requires a valid case #, and secure email does not, so secure email may actually be preferable at this point.

**Comment by lippytak** [comment]
I already pinged him about it.

On Fri, Oct 30, 2015 at 8:42 AM, Dave Guarino < notifications@github.com > wrote:
Actually, I'm going to hold off on pinging Logan re MBCW doc uploader for now
until we're at the point of wanting to use that — the big reason is that thing
requires a valid case #, and secure email does not, so secure email may actually
be preferable at this point.
