### ISSUE TITLE
Ask CDSS to update its income guidelines

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#409]
The COLA for 2015-2016 became effective on October 1st, per ACIN I-75-15 (released 9/4/15): http://www.cdss.ca.gov/lettersnotices/EntRes/getinfo/acin/2015/I-75_15.pdf

The CDSS site still currently has the 2014-2015 income guidelines which are no longer effective: http://www.cdss.ca.gov/foodstamps/PG3628.htm

@lippytak Okay for me to just email Kim? Should I CC anyone?

**Comment by daguar** [comment]
This is also related to the campaign to check all county web sites #393 since the state site being up-to-date can be referenced.

**Comment by daguar** [comment]
Emailed Kim

**Comment by daguar** [comment]
Kim says "Yikes! Will do!" :)

**Comment by alanjosephwilliams** [comment]
When we see a change on the state website, lets move forward with
contacting counties!

On Thu, Oct 29, 2015 at 9:17 AM, Dave Guarino <notifications@github.com>
wrote:

> Closed #409 <https://github.com/codeforamerica/health/issues/409>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/409#event-449414754>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
Agreed! I've set up an alert to know when it goes live in #410
