### ISSUE TITLE
Add some structured data to user interviews

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#411]
- Was the interview positive or negative?
- Complete interview? Did they need to reschedule once or more?

What else?

**Comment by alanjosephwilliams** [comment]
- phone or in person interview
- number of discrete times documents were submitted
- method by which documents were submitted
- benefit amount
- NPS?

On Thu, Oct 29, 2015 at 3:44 PM, Jake Solomon <notifications@github.com>
wrote:

>
>    - Was the interview positive or negative?
>    - Complete interview? Did they need to reschedule once or more?
>
> What else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/411>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by alanjosephwilliams** [comment]
Updates to the script include ~7 structured questions, some of which are updates to existing content we've been collecting. 

Script here: https://docs.google.com/a/codeforamerica.org/forms/d/1DSzyb0tF4N7sHrg3GOXfvBQZMQUltopjhRdojG_4uf8/edit?uiv=1

List of changes:
- Deleted the why now question. It's always delicate and rarely informative in terms of our service.
- Were you able to complete the eligibility interview?
- Was the interview positive or negative?
- Did you receive clear guidance on what documents you needed to submit?
- What documents did you submit?
- How did you actually send in the documents?
- Did you need to fill out any other paperwork after your interview?
- What happened after you submitted your documents?
-  Is that (the benefit amount) what you expected?
