### ISSUE TITLE
Write up EBTNearMe pounce project

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#413]
Draft: https://docs.google.com/document/d/1mKNuACDuCX2QAZknPSOqgwT7GBIVyx4geEW7dP1BXWA/edit#

**Comment by lippytak** [comment]
Main questions:
- How the eff are we going to recruit CalWORKS peeps across CA to validate ATM data?
- What kind of qualitative info do we want...only bad experiences to understand magnitude? Or should we do another Ethnio across all users? Or something else?

**Comment by daguar** [comment]
@lippytak re recruitment, what about talking to your buddy who runs CalWORKS in SF? I'm sure they'd love to validate this stuff. I think the easiest way to validate some local stuff is to offer some compensation to the client for their time and ask them to use the card at various ATMs and we can refund any fees that occur?

**Comment by lippytak** [comment]
Waiting for Meghan to finalize.

**Comment by lippytak** [comment]
Waiting for Meghan to finalize.
