### ISSUE TITLE
Onboard Norris

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#416]

**Comment by alanjosephwilliams** [comment]
- Entry into this atmosphere this week—Friday we are going to review research and sketches for the pre-screening feature. Probably in front of a whiteboard, I'll send cal invite.
- Definitely interested in joining sprint planning on Monday. Test driving working with us through the design and development of the pre-screening feature.
- Lots of shared goals and interests that make us both optimistic about medium-and-long term work together. 
- A sense that he and I are both opinionated design generalists weighted on opposite ends of the spectrum (Me: support, research, ux-oriented, he visual design and code-oriented)
