### ISSUE TITLE
Draft structured denial survey

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#419]
Goal is to learn why people get denied and what features we can build to change them. "What actually fucking happened?"

Structured incentivized survey for folks who were denied.

Things to note
- subsampling to improve survey as we go
- contact prefs
- ask for interview at end

**Comment by alanjosephwilliams** [comment]
- Select a subsample of known denials in the last 60 days, across all five CPP. We have 21 known denials that have expressed preferences for either email or SMS follow-up (four with no status have been excluded).
 
| County  | # of Denied  |
|---|---|
| Contra Costa | 0  |
| Marin  | 5 |
| Placer |10 |
| San Francisco  | 4 |
| Solano | 6  |

- Solicit a response to a short structured survey that a) optimizes for completion (many respondents will be on mobile) and b) only attempts to get one level deeper on the friction they experienced after submitting an application. We have known denial reasons for some of these folks, so it will be interesting to see how it maps to what we already know.

- Details: Try incenting at $30 of Amazon codes, use bit.ly to keep the solicitation short, promise under 5 minutes.  @lippytak @daguar any other thoughts on how to craft a strong appeal?

##### Solicitation copywriting:
- I see no need to explain to them that we are only targeting denied applicants.
- "Hi from GetCalFresh.org! What was difficult about applying for CalFresh? Take a 3 min survey & get $30 in Amazon.com credit for your feedback bit.ly/gcf-survey" <-- 159 chars

- subject: Take a 3 minute survey & earn $30 at Amazon.com from GetCalFresh.org
    "Hello! 
    
    You applied for CalFresh X month(s) ago at GetCalFresh.org. We were sorry to see that your     application was not approved—and we want to help improve the application experience for others that apply. 
    
    Will you take this 3 minute survey to help us? We can offer $30 in Amazon.com gift credit for your time and feedback. Share your experience now at bit.ly/gcf-survey.

   Thanks so much for your time. Your feedback is incredibly valuable. 

   Best,
   Alan & the GetCalFresh.org Team

**Comment by alanjosephwilliams** [comment]
#### Draft denial survey for your feedback @daguar @lippytak 

- Was this your first time appyling for CalFresh?

  - Yes
  - No

- On a scale of 1 to 5, how clear were you on next steps after you applied?

  - 5 - very clear
  - 4
  - 3 - somewhat clear
  - 2
  - 1 - not clear

- Were you able to get an eligibility interview?

  - Yes
  - No

   -> YES

    - When did you have your eligibility interview?

      - 1-2 days after I applied
      - Less than a week after I applied
      - More than a week after I applied

    - Did you receive a notice in the mail about your scheduled interview?

      - Yes, I received a notice in the mail before they called.
      - Yes, I received a notice in the mail, but it came *after* they called.
      - No, I never received a notice in the mail.

   -> NO

    - Darn, sorry to hear that. Is one or more of the following true?

      - It wasn't clear I needed an interview
      - It wasn't clear when my interview was scheduled
      - My phone number or phone plan has changed
      - I've had difficulty calling the county
      - I have limited transportation
      - I've been dealing with other issues


- Were you denied during the eligibility interview or later?

  - During the interview
  - Not until later

   -> DURING THE INTERVIEW

   - Darn, sorry to hear that. Is one or more of the following true?

     - I was denied told I had too much income to receive CalFresh
     - I was that because I receive other benefits, I cannot receive CalFresh
     - I was told that because of my immigration status, I cannot receive CalFresh
     - I was told I am not eligible for other reasons

   - On a scale of 1 to 5, how surprised were you that you application was denied?

	  - 5 - very surprised
	  - 4
	  - 3 - somewhat surprised
	  - 2
	  - 1 - not surprised

   -> NOT UNTIL LATER

	- On a scale of 1 to 5, how clear were you on next steps after your interview?

	  - 5 - very clear
	  - 4
	  - 3 - somewhat clear
	  - 2
	  - 1 - not clear

	- Were you able to submit documents to the county?

	  - Yes
	  - No

	    -> YES

	    - On a scale of 1 to 5, how clear were you on what documents you needed to submit to get CalFresh?

          - 5 - very clear
          - 4
          - 3 - somewhat clear
          - 2
          - 1 - not clear

        - How did you submit documents to the county?

          - From my phone
          - By e-mail
          - By fax
          - By mail
          - In-person

        - How many different times did you submit documents to the county?

          - Once
          - Twice
	      - More than twice

	   -> NO

	   - Darn, sorry to hear that. Is one or more of the following true?

	     - I didn't submit documents because I was told I did not qualify.
	     - I didn't know what documents to submit.
	     - I couldn't get the documents the county wanted.
	     - I had the documents, but couldn't send them in.

	- How did you learn that your CalFresh application was denied?

	  - I recieved a letter in the mail
	  - I received a phone call
	  - I had to call the county to find out
	  - I tried to use my EBT card, and it didn't work

- Thank you so much for your time and feedback. Is there anything else we should know about your CalFresh application experience?

**Comment by lippytak** [comment]
Lots of good stuff. I think it would be helpful to state the specific goal and then look through each question with that lens. I also think we could get a lot out of some open ended questions, like "Why weren't you able to do your interview?"

**Comment by alanjosephwilliams** [comment]
Indeed—updated with thinking inline. I'm open to more open-ended questions, but the grab-bag question serve that function currently. My thinking was that since its a relatively substantial survey, we could give ease the ux burden by offering options and then the opportunity to respond with "other".

**Comment by daguar** [comment]
@alanjosephwilliams Okay for me to pull this into a Google Doc to suggest changes?

**Comment by alanjosephwilliams** [comment]
Go for it!

Ultimately, we'll likely be implementing in Typeform.

On Thu, Nov 5, 2015 at 11:08 AM, Dave Guarino <notifications@github.com>
wrote:

> @alanjosephwilliams <https://github.com/alanjosephwilliams> Okay for me
> to pull this into a Google Doc to suggest changes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/419#issuecomment-154155991>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
Big picture suggestion — how about we remove the conditional logic for now and just do each of these branches as standalone surveys for the cohorts based on the county outcomes? (ie, a denial survey with depth about INTERVIEWS for N clients who we know were denied due to interview; a denial survey with depth about VERIFICATIONS for N clients we know were denied for verifications, etc. — probably shipping first for interview)

**Comment by alanjosephwilliams** [comment]
Big reason not to is just very small cohort size. We have 10 denials in the past 60 days that have denial reasons reported.

**Comment by daguar** [comment]
I've suggested some edits here: https://docs.google.com/a/codeforamerica.org/document/d/1JvfvqrJV-pcp6ovKkshO0cSBc1H64FhfvyNu3CS2NO0/edit?usp=sharing

**Comment by daguar** [comment]
Okay — I think with what I'm doing I can expand the 10-denial size somewhat. Can I also suggest we expand the window beyond past 60 days? Right now we are somewhat behind on outcomes for recent cases because of the county tracking.

**Comment by alanjosephwilliams** [comment]
We can definitely go beyond 60 days if we need to, but I think we should
index towards the most recent applicants we can that fit the criteria we
are interested to.

Responding to your thoughts in the gdoc for now.

On Thu, Nov 5, 2015 at 11:30 AM, Dave Guarino <notifications@github.com>
wrote:

> Okay — I think with what I'm doing I can expand the 10-denial size
> somewhat. Can I also suggest we expand the window beyond past 60 days?
> Right now we are somewhat behind on outcomes for recent cases because of
> the county tracking.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/419#issuecomment-154164434>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
Okalie dokalie — if we have 10 that's fine, and I can pull more post-full-outcomes.

Could we maybe start at $20? I think it'll get same result and I want to be able to go up if people don't respond.

**Comment by alanjosephwilliams** [comment]
The interview script has been updated in Google Docs, and ported over to Typeform with the requisite logic. I'll author a thank you page and ship to our first small batch today. $20 solicitation seems like a good place to start.

**Comment by alanjosephwilliams** [comment]
Survey has been QA'd: http://bit.ly/calfresh-survey

**Comment by alanjosephwilliams** [comment]
New SMS solicitation (to those that have opted-in). Doing a batch of 10 now, marking in GCF-cases.

Hi from GetCalFresh.org! What applying for CalFresh difficult? Take a 5 min survey & get $20 in Amazon credit for your feedback -> http://bit.ly/calfresh-survey

**Comment by alanjosephwilliams** [comment]
9 SMS surveys sent—3 to Solano, 3 to Marin, 3 to Placer. All marked in GCF-cases. I'm going to wait an hour for responses before sending an e-mail test.

**Comment by alanjosephwilliams** [comment]
9 sent, 1 click through, 0 completes. As mentioned in Slack, going to push out to 10 denied users via email, and up the incentive to $30.
