### ISSUE TITLE
Survey/Interview HSA Eligibility Workers

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/health#42]
Eligibility Workers are the customer service representatives of HSA. They handle applications, help manage cases, and make critical decisions. They also hear more feedback, and more questions, directly from clients than anyone else. Let's discuss the most appropriate and effective way to learn about our users by talking to the people that interact with them most. cc @lippytak

**Comment by lippytak** [comment]
Dup https://github.com/codeforamerica/health/issues/98
