### ISSUE TITLE
Test if MBCW late attachments works in SF

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#421]

**Comment by lippytak** [comment]
Sent test doc/email to Phillip in RM, will ping in 2 days if I don't hear

**Comment by lippytak** [comment]
BLUF is they are getting automatically imported into iFiles but not into AIMS (task mgmt) so EWs don't know proactively to process the docs. Fix is in process for next week. @alanjosephwilliams @daguar do not use MBCW CBO feature until they confirm and we test that it works. I'm opening another ticket to check on the old few docs that I submitted through this feature (probably 3-5 total).

There are also some pretty big #govwin implications for this so I'll be writing up a email for the team/org.

**Comment by alanjosephwilliams** [comment]
woof.

On Thu, Nov 5, 2015 at 11:23 AM, Jake Solomon <notifications@github.com>
wrote:

> BLUF is they are getting automatically imported into iFiles but not into
> AIMS (task mgmt) so EWs don't know proactively to process the docs. Fix is
> in process for next week. @alanjosephwilliams
> <https://github.com/alanjosephwilliams> @daguar
> <https://github.com/daguar> do not use MBCW CBO feature until they
> confirm and we test that it works. I'm opening another ticket to check on
> the old few docs that I submitted through this feature (probably 3-5 total).
>
> There are also some pretty big #govwin implications for this so I'll be
> writing up a email for the team/org.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/421#issuecomment-154162191>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
woof+
