### ISSUE TITLE
FU with SDHC

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#426]
To do
- Amanda will share more about student eligibility
- Share dashboard!
- Figure out the online confirmation
- Send Amanda
- Send example of tracking data

**Comment by daguar** [comment]
BLUF in channel after 5?

**Comment by lippytak** [comment]
BLUF
- SD hunger coalition is a sub to CAFP for CF outreach but has 12 subs of their own and submit ~8-9k apps/yr
- Two largest subs are the 2 Food Banks who have ~75% approval rate
- Amanda will present GCF to her subs on the 19th and see if there are 1-3 folks who'd like to start using GCF
- Amanda thought that not having a confirmation number/page would be a blocker

In the meantime we'll
- Get the dropbox setup
- Do some creative brainstorming about the confirmation issue
