### ISSUE TITLE
Re-send any docs that were sent teo SF via MBCW portal

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#430]
Or at least report to Beverly/Tiana/Leo

**Comment by lippytak** [comment]
Will do this weekend...important and didn't prioritize late in sprint!

**Comment by daguar** [comment]
I'm not sure we did any; I didn't myself. @alanjosephwilliams do you remember doing any?

**Comment by lippytak** [comment]
I did a few, I think that was it. Should be commented in Front…

On Sat, Nov 7, 2015 at 9:49 AM, Dave Guarino < notifications@github.com > wrote:
I'm not sure we did any; I didn't myself. @alanjosephwilliams do you remember
doing any?

**Comment by alanjosephwilliams** [comment]
I did not do any. I'll leave this issue open until we discuss IRL.

**Comment by lippytak** [comment]
SF is now assigning these docs. We have 2 denied cases likely affected by this. I'm going to escalate these (and others) to Beverly.
