### ISSUE TITLE
TY user need cards for SF CFO team

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#440]
Tough time and they're still going out of their way to help us out so let's show them some <3. I'll bring cards tomorrow.

**Comment by daguar** [comment]
Let's finish and ship these today before you head out? I can handle shipping them if we're all signed.

**Comment by alanjosephwilliams** [comment]
this issue appears to longer be timely

**Comment by lippytak** [comment]
Timeless!

**Comment by lippytak** [comment]
Do Less™

Yaya I was wrong.
