### ISSUE TITLE
Get to know Alexis and brainstorm content work

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#442]
Possibility to do some awesome content work with Alexis.

I'll get an hour on the calendar to:
- Get to know her humanness / skills / interests
- Brainstorm a few content strats

Scope should be 1-3 long form pieces at ~50% time for ~3 months. Let's discuss in sprint plan.

**Comment by alanjosephwilliams** [comment]
@lippytak had the meeting and reported back that it wasn't the right time or fit.
