### ISSUE TITLE
Simple web form for clients scheduling CalFresh interviews (sent via email to counties)

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#443]
@alanjosephwilliams surfaced that people can schedule interviews over email (at least in Marin, Placer, and SF.)

Since a lot of what the counties want in that email is boilerplate (client info) that we have from the initial application, we could create a much simpler form/experience for the client where the only thing they provide is *desired timeframes in the M-F, 8-5 (or whatever) window* and we populate the email to the county.

Slightly trickier problem — we probably want the county to be able to reply with the scheduled time, so we either want to send it from the client's address or have some sort of (client -> GCF, GCF -> county, county -> GCF, GCF -> client) flow to pass the info back and forth.

Cool thing about this — we could also theoretically also offer an SMS way to offer interview where the client puts in times they want, and we just pass it along via email, and when we receive a response from county pass it back to the client.

Opening this more as an idea — worth noting interviews are the biggest bottleneck for Marin County right now.

**Comment by alanjosephwilliams** [comment]
this is a duplicate issue, i suggest closing
