### ISSUE TITLE
Confirm if Adobe wants to do CitizenOnboard

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#446]
Send problem statement and examples. See if they want to do it. If not, we'll pass. They weren't stoked on the call.

**Comment by alanjosephwilliams** [comment]
include links to the NYT and WaPo articles

On Mon, Nov 16, 2015 at 3:35 PM, Jake Solomon <notifications@github.com>
wrote:

> Send problem statement and examples. See if they want to do it. If not,
> we'll pass. They weren't stoked on the call.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/446>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by alanjosephwilliams** [comment]
and anil dash's tweet

On Tue, Nov 17, 2015 at 9:23 AM, Alan Williams <alanjosephwilliams@gmail.com
> wrote:

> include links to the NYT and WaPo articles
>
> On Mon, Nov 16, 2015 at 3:35 PM, Jake Solomon <notifications@github.com>
> wrote:
>
>> Send problem statement and examples. See if they want to do it. If not,
>> we'll pass. They weren't stoked on the call.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/codeforamerica/health/issues/446>.
>>
>
>
>
> --
> t:  @alanjosephwilli
> p: 817 713 6264
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
Just to confirm, closing this makes it seem like a 'no'?

**Comment by lippytak** [comment]
Correct

On Sunday, November 29, 2015, Dave Guarino <notifications@github.com> wrote:

> Just to confirm, closing this makes it seem like a 'no'?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/446#issuecomment-160480281>
> .
>


-- 
Via thumbs
