### ISSUE TITLE
Partner county EOY awards

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#448]

**Comment by daguar** [comment]
👍👍👍 This is an excellent idea.

**Comment by lippytak** [comment]
http://www.tinkeringmonkey.com/tabletop-sign/

**Comment by lippytak** [comment]
CalFresh Innovation Award

**Comment by lippytak** [comment]
@daguar @alanjosephwilliams looks like we can get a simple 5x5" self-standing engraved wood w a logo on front / quote on back for about ~$65/per = ~325 total for partners. Think we should do this?

**Comment by alanjosephwilliams** [comment]
Yes.

On Mon, Jan 4, 2016 at 2:56 PM, Jake Solomon <notifications@github.com>
wrote:

> @daguar <https://github.com/daguar> @alanjosephwilliams
> <https://github.com/alanjosephwilliams> looks like we can get a simple
> 5x5" self-standing engraved wood w a logo on front / quote on back for
> about ~$65/per = ~325 total for partners. Think we should do this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/448#issuecomment-168783291>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
Also yes, though ping ST to get her take on whether any partners would be freaked out by the gift aspect.

**Comment by alanjosephwilliams** [comment]
great to see this shipped!

**Comment by lippytak** [comment]
Do Less™
