### ISSUE TITLE
Help Victor figure out what MBCW recert looks like 

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#455]
> I hope the two of you are doing well.  I was wondering if either of you could answer a question for me?  I’m curious about the BCW portal option for customers that wants to complete their CalFresh renewal paperwork through the BCW portal.  If someone clicks on the renewal option, what form are they filling out?  Is it a CF 37 or a SAWS 2 Plus?  We recently received a SAWS 2 Plus from a customer that has a December renewal and we’re wondering if that was what came up for her in the portal or if she just submitted a new application by mistake?

@alanjosephwilliams I'm going to ping our SF CalWIN contact (Bernadette) but otherwise do yo' thang. LMK if I can help.

**Comment by daguar** [comment]
The food bank may help clients with recert online already. Maybe we should quickly ping them?

**Comment by alanjosephwilliams** [comment]
good idea will do.

On Fri, Dec 11, 2015 at 8:41 AM, Dave Guarino <notifications@github.com>
wrote:

> The food bank may help clients with recert online already. Maybe we should
> quickly ping them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/455#issuecomment-163986211>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by lippytak** [comment]
Value has been DELIVERED.

Answer is CF 37 as verified by AJW

**Comment by daguar** [comment]
Ooo, how'd we find out? Food bank?

**Comment by alanjosephwilliams** [comment]
@daguar Carissa and Beverly

**Comment by lippytak** [comment]
AND Bernadette :)

On Wed, Dec 16, 2015 at 10:33 AM, Alan Joseph Williams < notifications@github.com > wrote:
@daguar Carissa and Beverly
