### ISSUE TITLE
Help ES clients submit IDs

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#457]
Todo
- [x] Change confirmation page copy
- [x] Change ES confirmation/reminder copy
- [x] Change 'income docs' and 'other docs' to emphasize you can come back and do it later

**Comment by lippytak** [comment]
My recommendation is to cut down on the confirmation page copy substantially and just tell people to submit IDs, like so:

![screen shot 2015-12-11 at 12 19 39 pm](https://cloud.githubusercontent.com/assets/2533112/11754670/83862566-a001-11e5-989c-acf4436e3ad1.png)

'Submit ID Now' takes them to the appropriate doc upload page with more info:
![screen shot 2015-12-11 at 12 13 33 pm](https://cloud.githubusercontent.com/assets/2533112/11754682/aa638e80-a001-11e5-9e9a-a37379a113f7.png)

**Comment by lippytak** [comment]
Policy Q to confirm - to get ES do you need to show ID for everyone in the HH or just primary application? I assume everyone...

**Comment by lippytak** [comment]
Suggested SMS ES campaign changes:

Old confirmation: *You applied for CalFresh! County staff will call you within 2-3 days. If you don't hear anything in 3 days, reply to this text & we will help you w/ next steps.*

New conf: *You applied for CalFresh 👍! A CalFresh rep will call you in 2-3 days to finalize things. You can reply here w/ a pic of your ID if you didn't send it before.*

Old 4day: *Hi! You applied for CalFresh a few days ago. Have you had the req'd interview yet? If not, call your county. Find the phone # at http://getcalfresh.org/contact*

New 4day: *Hi! You applied for CalFresh a few days ago. Have you had your CalFresh interview? If not, call your county CalFresh office ASAP at www.getcalfresh.org/contact*

**Comment by lippytak** [comment]
For Email ES campaign, I suggest we shorten the first part a tiny bit and add this near the top:

**If you haven't submitted a copy of your ID, you should do that right now. You can reply directly to this email with a picture of your ID or upload it to https://www.getcalfresh.org/docs**

**Comment by alanjosephwilliams** [comment]
This looks good. Ship this iteration!

**Comment by alanjosephwilliams** [comment]
When we test it, lets see how it feels after submitting an ID. We may want to update the language in the docs flow to recognize that we anchor expectations around only one document being submitted, and we are now offering _the opportunity_ to submit more (there may be a way to tease this in the confirmation page copy as well).

**Comment by carolinehays** [comment]
@lippytak re policy Q above. I think ES households only need ID of head of HH. This is from San Bern MPP. I assume others are within the 30 day window
<img width="469" alt="es id" src="https://cloud.githubusercontent.com/assets/12751256/11759976/d72d1842-a03c-11e5-9be6-df848c0cb891.PNG">

**Comment by lippytak** [comment]
oh fantastic @carolinehays ! I'll figure out how we can emphasize that appropriately above.

**Comment by lippytak** [comment]
I think for now we can specifically say the first person's name in the confirmation page:

![screen shot 2015-12-12 at 12 16 45 pm](https://cloud.githubusercontent.com/assets/2533112/11763731/81454736-a0ca-11e5-9458-6bc72f40eb06.png)

But the doc upload screen will still reference 'all HH members' so we don't have to create another Typeform or do weird param passing:
![screen shot 2015-12-12 at 12 19 52 pm](https://cloud.githubusercontent.com/assets/2533112/11763735/b0e295d4-a0ca-11e5-8ce2-586fdfba76ff.png)

Slightly confusing but I think okay and a big improvement for ES HHs.

**Comment by lippytak** [comment]
Since more people are going to be hitting our income docs section when they're really only intending to submit ID, I'm changing the income and 'other docs' copy from this:
![income-before](https://cloud.githubusercontent.com/assets/2533112/11763750/6881ca66-a0cb-11e5-90b4-b83db3fcc2da.png)

To this:
![income](https://cloud.githubusercontent.com/assets/2533112/11763753/6cbc4b6a-a0cb-11e5-81cc-6822e7e2caef.png)
