### ISSUE TITLE
Transfer recurring expenses to ST amex

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#460]
- Typeform
- Zapier
- Front
- Creative Cloud
- Microsoft 360
- GetDrip
- Textit.in
- Intercom
- Hellofax
- Browserstack

Probably more...will look through my expense reports

**Comment by daguar** [comment]
Some of these probably can probably also be CFA accounts (exception: PII) and help others use them

**Comment by lippytak** [comment]
@daguar good point - I'd say that's only creative cloud and MS though, right?

**Comment by daguar** [comment]
I don't know the account structure of all of these, but there's probably some economies of scale out there
