### ISSUE TITLE
Open health repos to org (and generally fiddle with GH config)

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#461]
- health = public
- health-logs = open to org
- health-notes = open to org
- health-private = team stuff, mainly for PII
- project specific = open to org (project team = contributors, as needed)

**Comment by lippytak** [comment]
@daguar feel free to FISI at your convenience. Otherwise I'll take care of it soon.

**Comment by daguar** [comment]
:+1: I prolly won't get to it; also request to review logs + notes + project ones just to be sure no PII or other stuff we'd NOT want org-open in there (I believe there may be)

**Comment by lippytak** [comment]
K there are 3 main concepts now:
- *Org owners* = can read/push/add collaborators on every CfA repo regardless of any other permissions (technically not a 'team' but...whatevs)
- *Teams* = groups of org members. The important ones for us are Health, CfA Staff, and 2015 Fellows (soon to be 2016)
- *Permissions* = Teams of people (or individual 'collaborators') can either have admin, write, or read permission for a repo (permissions are set on a per-repo basis).

Here are the permissions I setup for our repos:
- health (and most of our other repos) = public
- health-logs AND health-notes
  - Health team = admin
  - CfA staff team = write
  - 2015 Fellows team = write
- getcalfresh.org / saws-drivers
  - Health team = admin
  - Individual collaborators (Norris, William) = write
  - CfA staff team = read
  - 2015 Fellows team = read
- health-private
  - Health team = admin (note all org owners have full access)

@daguar plz sanity check at your convenience and re-open if I missed anything.

**Comment by lippytak** [comment]
PS. I did glance through health-notes and health-logs and didn't see any PII, but double checking is encouraged
