### ISSUE TITLE
ADS for holiday week (new year's)

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#463]
How does this split sound:
- Monday: dave 
- Tuesday: jake
- Wednesday: ajw
- Thursday: ajw
- Friday: ajw(edited)

**Comment by daguar** [comment]
This is me today

**Comment by alanjosephwilliams** [comment]
:+1:

On Monday, December 28, 2015, Dave Guarino <notifications@github.com> wrote:

> This is me today
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/463#issuecomment-167594889>
> .
>


-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
@lippytak is on today

**Comment by alanjosephwilliams** [comment]
My day today :+1:

**Comment by lippytak** [comment]
I'm up!

**Comment by alanjosephwilliams** [comment]
actually I am up today! Have time blocked out and everything :)

**Comment by alanjosephwilliams** [comment]
I'm on it today :)

**Comment by alanjosephwilliams** [comment]
_fin_

**Comment by daguar** [comment]
Apps in before 5 will still go in tho yes?

**Comment by alanjosephwilliams** [comment]
Same Day Service Guaranteed™

On Fri, Jan 1, 2016 at 5:40 PM, Dave Guarino <notifications@github.com>
wrote:

> Apps in before 5 will still go in tho yes?
>
> > On Jan 1, 2016, at 3:31 PM, Alan Joseph Williams <
> notifications@github.com> wrote:
> >
> > Closed #463.
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/463#issuecomment-168350832>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by lippytak** [comment]
Pens down 2016
