### ISSUE TITLE
Decide if/how we can give Contra Costa FB better outcome data

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#464]
- Can we get/share outcomes through the county?
- Can we submit CC cases through their CBO account?
- Other ideas?

**Comment by alanjosephwilliams** [comment]
Are we sharing outcome data with any CBO partners right now?

**Comment by lippytak** [comment]
no

**Comment by lippytak** [comment]
We decided to offer to offer them monthly screenshots of CC segment of MBCW report on a monthly basis. I pinged Caitlin to confirm and will close this when I hear back from her that this solves her issue.

**Comment by lippytak** [comment]
Caitlin confirmed
