### ISSUE TITLE
Little hoover UX commission

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#467]
5 min talk on Jan 21 in Sac, preferably about CalFresh stuff, anyone from CfA works.

**Comment by alanjosephwilliams** [comment]
I was interested / planning on at least attending this

**Comment by alanjosephwilliams** [comment]
link?

On Sat, Jan 16, 2016 at 9:27 AM, Jake Solomon <notifications@github.com>
wrote:

> Closed #467 <https://github.com/codeforamerica/health/issues/467>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/467#event-517010604>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
