### ISSUE TITLE
Give SF Food Bank clients access to Connect

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#468]
Liliana requested this, and said it would be a huge benefit (even with only ~75% connection rate of calls). Let's consider and give the :+1: if it makes sense. This probably also requires recording a Spanish language message for the Spanish line (can probably wait on Chinese or ask the FB).

**Comment by daguar** [comment]
Can I get a :+1: to say yes and say we can change the voice audio for new language in the future? @lippytak

**Comment by lippytak** [comment]
:+1:

**Comment by daguar** [comment]
Done
