### ISSUE TITLE
Prepare "rapid prototyping" prezo

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#472]
This is this Wed 3-4

cc @lippytak @alanjosephwilliams

**Comment by lippytak** [comment]
@alanjosephwilliams plz drop slide link here (w edit access). I have 2:30-3 blocked off to prep.

**Comment by alanjosephwilliams** [comment]
edit access sent yesterday:
https://docs.google.com/presentation/d/128l0lSjRYmibJM4mF29MN5WfHBgVYMEJv7tstTOdPM4/edit#slide=id.g1067c29d1a_0_10
