### ISSUE TITLE
Turn on SD adwords

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#473]
It's time.

**Comment by daguar** [comment]
👍🚀🚢

**Comment by lippytak** [comment]
![screen shot 2016-01-25 at 10 24 58 am](https://cloud.githubusercontent.com/assets/2533112/12560146/ebd7d672-c34d-11e5-8de0-464d745e4496.png)

**Comment by daguar** [comment]
@lippytak any interest in adding an adwords source var?

**Comment by lippytak** [comment]
already there, source=google.

On Mon, Jan 25, 2016 at 10:31 AM, Dave Guarino < notifications@github.com > wrote:
@lippytak any interest in adding an adwords source var?

**Comment by daguar** [comment]
:+1: #lackofrigor
