### ISSUE TITLE
Watch Yes Minister

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#475]

**Comment by lippytak** [comment]
Thx will discuss at next sprint plan.

On Wednesday, January 20, 2016, Dave Guarino <notifications@github.com>
wrote:

> Assigned #475 <https://github.com/codeforamerica/health/issues/475> to
> @lippytak <https://github.com/lippytak>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/475#event-521334023>.
>


-- 
Via thumbs

**Comment by daguar** [comment]
<img width="493" alt="screen shot 2016-01-20 at 11 03 15 pm" src="https://cloud.githubusercontent.com/assets/994938/12473758/03c03b30-bfca-11e5-9d7c-4c44404972aa.png">

**Comment by daguar** [comment]
https://www.youtube.com/watch?v=dIto5mwDLxo&t=0m50s

**Comment by daguar** [comment]
Available on Hulu Plus
