### ISSUE TITLE
Do a quick web version of Dave's 2015 Twilio Signal conf talk

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#477]
a la Pinboard; low priority but folks said they found it useful, and I think it's decent content marketing/tactical insight

**Comment by lippytak** [comment]
feel free to grab simple template at
http://codeforamerica.github.io/the-mission-is-delivery/

On Mon, Jan 25, 2016 at 9:48 AM, Dave Guarino < notifications@github.com > wrote:
a la Pinboard; low priority but folks said they found it useful, and I think
it's decent content marketing/tactical insight
