### ISSUE TITLE
Double-check whether Caroline's conversion #s included non-online app submission

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#479]
I think you're probably right looking at it, but not clear from the PPT I think

**Comment by lippytak** [comment]
@carolinehays can you quickly clarify something for us?

In your sample of ~30 online applicants, approx what % of them submitted an online application on their first try? My memory says 40% but @daguar suggests the 40% number may also have included people who gave up online and went to other methods?

Thx!

**Comment by carolinehays** [comment]
Ah good clarification - 40% submitted an application on their first try through MBCW. that number doesn't include folks who told me they printed out an application to mail in or planned to go to the office. 
Happy to pull some more detail out of the data on what the breakdown of the other 60% was, e.g. how many gave up, how many went to other methods of applying, how many planned to try again online, if it would be helpful!

**Comment by daguar** [comment]
Ah okay, @lippytak was right on the money.

@carolinehays If it's quick and easy, I would say understanding how many people switched to a different application channel (office, paper, etc.) by channel would be useful, as well as how many straight-up gave up.

**Comment by carolinehays** [comment]
@daguar realized I captured this already in "next steps." Didn't get complete data on it, but of those that answered, 3 planned to go to an office. 2 of those explicitly mentioned printing an app and bringing it, the third had questions and figured could go to the office to get them answered and then apply there. 
![image](https://cloud.githubusercontent.com/assets/12751256/12858936/dd2fda76-cc07-11e5-80ee-e5f4031432e6.png)
