### ISSUE TITLE
Outline HKS presentation

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/health#482]

**Comment by alanjosephwilliams** [comment]
@daguar I'd love to be able to give feedback on what you prepare.  Preach the Delivery Gospel!

**Comment by daguar** [comment]
I forwarded an email with some context; sounds like only a 5-15 min prezo with the remaining ~60 mins being Q&A with David E. His focus is on being user-centered (why, how.)

**Comment by daguar** [comment]
https://docs.google.com/presentation/d/1j3Fs3HLo6rgTDRvScX4lxRZAvJrPrrmGCeCHsQwsU4o
