### ISSUE TITLE
"Iterative Development" Guide for CfA.org

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/health#483]

**Comment by alanjosephwilliams** [comment]
Upon request from @davidrleonard, I'm taking a pass at some content a la the User Needs 101 guide.

**Comment by davidrleonard** [comment]
Can I provide any support, @alanjosephwilliams? Thanks so much for your help — you are amazing.

**Comment by alanjosephwilliams** [comment]
don't think so, just a long day. writing an outline tonight, then turning
back to it first thing AM. Let's sync up by lunchtime.

On Tue, Feb 16, 2016 at 3:36 PM, David Leonard <notifications@github.com>
wrote:

> Can I provide any support, @alanjosephwilliams
> <https://github.com/alanjosephwilliams>? Thanks so much for your help —
> you are amazing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/483#issuecomment-184920318>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
