### ISSUE TITLE
Decide of any of Kims ideas are appealing+feasible

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#489]
- WIC + SNAP in certain counties
- Custom landing page for health clinics
- How to reach ~1m kids getting school meals and not SNAP
- Simplified application for senior applicants (e.g., http://www.mass.gov/eohhs/docs/dta/c-snapapp-elderly-eng.pdf)
- Procurement consulting on online app

**Comment by daguar** [comment]
I definitely think some of these are feasible and well-scoped smaller projects worth doing.

On the school meals, the new bill may be an opportunity, but probably requires resourcing.

**Comment by alanjosephwilliams** [comment]
Immediate next step is to schedule a time for Kim to meet ST. @stmayer pointed out, we should scope these as paid engagements that potentially lead to new head count. We can use that meeting as a deadline to think these through.

**Comment by alanjosephwilliams** [comment]
FU to Kim sent.

**Comment by alanjosephwilliams** [comment]
doing a little write up on this front in advance of Kim mtg set for 3/15
