### ISSUE TITLE
Set up web app for CalFresh conversion study

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#494]
- [x] Basic new app setup
- [x] Web form that collects county (dropdown), email and/or phone # (at least 1/2 required)
   - [x] Validates that _either_ email _or_ phone number is there
   - [x] Validate phone # (if present)
- [x] Front end design ( @alanjosephwilliams )
- [x] Have web app route to the correct destination (either to legacy site or randomize to GCF)
- [x] Have web app send data to the GSpreadsheet (POST to Zapier)
  - [x] Fields: county, destination [eg, MBCW, C4, YBN, GCF], phone number, email
  - [x] New field: timestamp
- [x] Add JS redirect after 5 seconds to redirect page
- [x] Set up Google Spreadsheet to collect the info
- [x] Configure Zapier to put the info in the GSpreadsheet
- [x] Force HTTPS
- [x] Make secret token from from env
- [x] Configure domain
   - [x] Configure in NameCheap
   - [x] Heroku SSL add-on / custom domain config
- [x] Set up Google Analytics
  - Maybe use CFA AdWords account to link AdWords to Analytics
  - [x] Try to capture outbound destination in Analytics
- [x] Test and then delete test data

**Comment by alanjosephwilliams** [comment]
Thanks for listing out the pieces @daguar . I'm going to forgo creating a separate issue for the frontend work.

**Comment by daguar** [comment]
:+1:

**Comment by daguar** [comment]
v1 checklist done above. It looks like this at present:

- [ ] Basic new app setup
- [ ] Web form that collects county (dropdown), email and/or phone # (at least 1/2 required)
   - [ ] Validates that _either_ email _or_ phone number is there
- [ ] Front end design ( @alanjosephwilliams )
- [ ] Have web app route to the correct destination (either to legacy site or randomize to GCF)
- [ ] Have web app send data to the GSpreadsheet (POST to Zapier)
  - Fields: county, destination [eg, MBCW, C4, YBN, GCF], phone number, email
- [ ] Set up Google Spreadsheet to collect the info
- [ ] Configure Zapier to put the info in the GSpreadsheet
- [ ] Force HTTPS
- [ ] Configure domain
   - [ ] Configure in NameCheap
   - [ ] Heroku SSL add-on / custom domain config
- [ ] Set up Google Analytics
  - Maybe use CFA AdWords account to link AdWords to Analytics
  - [ ] Try to capture outbound destination in Analytics
- [ ] Test and then delete test data

**Comment by daguar** [comment]
Basic new web app setup done (Rails app config'd with failing test): https://github.com/codeforamerica/calfresh-conversion-experiment

**Comment by daguar** [comment]
Basic web form done (though not the backend) so all good for @alanjosephwilliams to start on design

**Comment by daguar** [comment]
Now validates that either email or phone # is filled

**Comment by daguar** [comment]
Added:
- Validate email address (if present)
- Validate phone # (if present)

**Comment by daguar** [comment]
Validated phone # , not going to validate email address because easy to fake anyway

**Comment by daguar** [comment]
Domain and SSL all set up! Yay!

**Comment by alanjosephwilliams** [comment]
Woot! Front end is in motion.

On Wed, Mar 16, 2016 at 4:07 PM, Dave Guarino <notifications@github.com>
wrote:

> Domain and SSL all set up! Yay!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/494#issuecomment-197596252>
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
Done with:
 Have web app route to the correct destination (either to legacy site or randomize to GCF)

**Comment by daguar** [comment]
Done with:
 Have web app send data to the GSpreadsheet (POST to Zapier)
Fields: county, destination [eg, MBCW, C4, YBN, GCF], phone number, email
 Set up Google Spreadsheet to collect the info
 Configure Zapier to put the info in the GSpreadsheet

**Comment by daguar** [comment]
Done with adding timestamp

**Comment by daguar** [comment]
Done with the actual routing of people

**Comment by daguar** [comment]
Heads up @alanjosephwilliams — I've added another view at `app/views/external_sites/shell_for_outbound_linking.html.erb`

This is the "confirmation" view of sorts that folks will have before being automatically redirected to the correct system. It should be pretty easy to style (it's barely any content) and may automatically pull in stuff if you're doing it in the application layout, but heads up we'll need some tiny amount of design on that too.

**Comment by daguar** [comment]
(Aside: my motivation for this rather than auto-redirecting is (1) better user experience to me, and (2) we get Google Analytics with the URL of the destination we sent folks to, so a full view of the funnel in GA which is handy)

**Comment by daguar** [comment]
Oh hey! Secret token is now auto-generated in the env by Heroku. How nifty!

**Comment by daguar** [comment]
Done with  Force HTTPS

**Comment by daguar** [comment]
Done with JS redirect after 5 seconds

**Comment by daguar** [comment]
FE design done, w00t @alanjosephwilliams

**Comment by daguar** [comment]
GAnalytics set up and working!

**Comment by daguar** [comment]
Also, we capture the outbound destination of folks in GAnalytics (and our spreadsheet) :)

**Comment by alanjosephwilliams** [comment]
:boom:

On Thursday, March 17, 2016, Dave Guarino <notifications@github.com> wrote:

> GAnalytics set up and working!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/494#issuecomment-198136148>
>


-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
Tested and deleted data, yay!

**Comment by daguar** [comment]
We now redirect to CFA if someone goes to the root URL (as opposed to /apply, where our ads will send folks)
