### ISSUE TITLE
Data on Interview Rescheduling for Leo & Linda/Logan

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/health#496]
- number of requests
- percent responded to
- any data we have on whether interview was conducted
- any data we have on response time

**Comment by daguar** [comment]
- # of requests: 6
- All 6 clients successfully rescheduled!
- % responded to: 83% (5/6) — 1 client already had one scheduled on the books, and successfully completed it
- Response time: clients receive a text and/or email with their new interview time on average about ~1-2 hours after submitting the request on weekdays; on weekends, they're able to submit requests (unlike call center) and they get fulfilled Monday morning

**Comment by daguar** [comment]
@alanjosephwilliams For getting info on whether interview was conducted it's a bit tricky, I don't know who we've contacted, but that'd be the way to do it.

I know we contacted the first user (who didn't get one) and the user without a rescheduled interview (who DID get one.)

Have we contacted anyone else? If not, I'll go ahead and text/email them.

**Comment by alanjosephwilliams** [comment]
:+1: sounds great— go ahead and take the FUs

**Comment by daguar** [comment]
I've texted 3 clients to ask them.

I've excluded another 3 because:
- 2 we know the outcome already
- 1 asked to schedule theirs for a date in the future

**Comment by daguar** [comment]
@alanjosephwilliams you have what you need? If so, please close, if not please lmk what else you want. :fist:

**Comment by alanjosephwilliams** [comment]
I'm good to go :+1: closing now
