### ISSUE TITLE
CalFresh story gathering

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#503]

**Comment by alanjosephwilliams** [comment]
stories gathered, being sent to Ren

**Comment by daguar** [comment]
Just a heads up that I didn't see in our initial solicitation asking explicit consent to give folks' stories to a reporter — I'd really like it if we could explicitly ask the folks whose stories we intend to share prior to sending those over.

**Comment by alanjosephwilliams** [comment]
👌. its somewhat explicit: "your anonymous stories help us build support",
but could be more so.

On Wednesday, April 27, 2016, Dave Guarino <notifications@github.com> wrote:

> Just a heads up that I didn't see in our initial solicitation asking
> explicit consent to give folks' stories to a reporter — I'd really like it
> if we could explicitly ask the folks whose stories we intend to share prior
> to sending those over.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/503#issuecomment-215130638>
>


-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by stmayer** [comment]
We need to be very explicit. "Your stories will be stripped of identifying features and shared with xyz for the following purposes ..." Or something like that.
