### ISSUE TITLE
Set up mail server and credentials for interview rescheduling

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/health#513]
# Customize default host

  config.action_mailer.default_url_options = {
    :host           => ENV['HOSTNAME_FOR_URLS'],
    :protocol       => "https"
  }

  config.action_mailer.smtp_settings =  {
    :port           => ENV['MAILGUN_SMTP_PORT'],
    :address        => ENV['MAILGUN_SMTP_SERVER'],
    :user_name      => ENV['MAILGUN_SMTP_LOGIN'],
    :password       => ENV['MAILGUN_SMTP_PASSWORD'],
    :domain         => ENV['EMAIL_DOMAIN'],
    :authentication => :plain,
  }
  config.action_mailer.delivery_method = :smtp

  config.action_mailer.default_options = {
    :from => 'hello@getcalfresh.org'
  }

**Comment by ghost** [comment]
Waiting for DNS records to update to make mailgun happy
