### ISSUE TITLE
Create date selector input

### ISSUE THREAD

**Issue by danielladevera** [codeforamerica/health#528]
The current CSS written doesn't support a date select input, so let's make one and add it to the style guide.

**Comment by danielladevera** [comment]
<img width="525" alt="screen shot 2016-09-20 at 11 49 20 am" src="https://cloud.githubusercontent.com/assets/9830957/18684255/5d368fd4-7f28-11e6-8f32-8488af308859.png">

**Comment by danielladevera** [comment]
We wrapped each select input in `<div class="select">` then added `style="display: inline;"` so that they'd all be on the same line 😞

**Comment by norrishung** [comment]
I fixed the css on this so it should work now! Someone just needs to rewrite the helper in the gcf form builder to use the right html/classes.
