### ISSUE TITLE
Write-up: GCF vs. No Wrong Door

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/health#532]
In conversations with Mollie R, she is hoping for some thoughtful articulation of why we are focusing exclusively on SNAP, which goes against all of their research findings and conventional progressive policy wisdom. We heard a similar desire from Tiana W on Friday. I'm going to take a first pass at this over the next day or so.

**Comment by daguar** [comment]
One thing I think it'd be useful to discuss is it's not that we're dogmatic about this — it's more that we have very little data that "no wrong door" is the _right_ approach, and in actually building the services tends to make things more confusing for users, etc.
