### ISSUE TITLE
Balance user research questions

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#55]
- About half of all balance users who have one successful balance check never check again (https://github.com/codeforamerica/balance/issues/223). Why not?
- How many people try to use balance but never get a successful check? What goes wrong? How can we help folks get to their first successful check? (v1 is just data analysis at this point)
- How many people have (and use) MMS but not data? AKA what’s the differential value of MMS vs. simple website for sending verification docs?
- Are people comfortable sending picture text messages to HSA? Other gov agencies?

Assigning to @alanjosephwilliams not because it’s his job to answer but to inform ongoing user research sessions. Also very open to other ways of collecting/discussing this info - just wanted somewhere to get out thoughts for now. Also it’s pretty clear that different questions are best answered through different types of research, so maybe it makes sense to separate things out by research type.

**Comment by alanjosephwilliams** [comment]
Balance user research can be found in the Health folder on Google Drive.
