### ISSUE TITLE
Bundle PDF page number bugs

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/health#571]
If the verification bundle is mushing together pdfs, then the page count can be wrong.

Check later_docs 105 for an example

**Comment by daguar** [comment]
+1, this is confusing for them, and I'd noticed it too. We could just remove that line altogether to at least not confuse them.

**Comment by daguar** [comment]
I replaced the "3 page(s) below" with "See page(s) below" because of this problem — it's a quick fix and I don't think there's a huge amount of value beyond directing internal staff to look at all the pages underneath the cover one.
