### ISSUE TITLE
Balance in Alameda County

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/health#573]
Balance turned out to be the thing that got the Deputy Director very excited.

I looked at our Twilio Dashboard, and it looks like we will need to set up a balance-alameda # with a 510 area code if possible.

Once that's done, I will update the business card file and order a shipment to their office.

Showing up with value!

**Comment by daguar** [comment]
15102579395

**Comment by daguar** [comment]
spanish: 15102579762
