### ISSUE TITLE
Ship production /cbo page

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/health#589]
- [x]  @norris is going to checkin with @neilkhare and @egikow on needs they've identified
- [x] start with content 
- [ ] mockups
- [ ] implementation

- v1 does not need to include an actual sign up flow.
- Conversion will measured by contacting the team.
- Should include peer validation, list of benefits, and frequently asked questions

**Comment by alanjosephwilliams** [comment]
Just checking in on this checklist — @norrishung @danielladevera does it seem complete and up to date?

**Comment by daguar** [comment]
getting this live is priority 1 this week

**Comment by daguar** [comment]
live
