### ISSUE TITLE
Fix MEDA accounts

### ISSUE THREAD

**Issue by norrishung** [codeforamerica/health#598]
Accidentally created a username under SF marin food bank.

Also, need to provide the main user with her password (she forgot)

**Comment by daguar** [comment]
Can you give the database ID of the user? (Reminder, don't post any PII here, especially as this was opened in /health which is public.)

**Comment by daguar** [comment]
norris to slack us info

**Comment by norrishung** [comment]
I believe I added "Jacqueline (Lydia) Gomez” to the Food Bank of San Francisco and Marin instead of to MEDA

**Comment by daguar** [comment]
I assigned to myself because I thought I'd have time but @ondrae whichever of us hits this first after doing stuff should just do it (or maybe together pairing)

**Comment by daguar** [comment]
tomorrow*

**Comment by daguar** [comment]
fixed, no apps to fix
