### ISSUE TITLE
Immigration iteration

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/health#603]
Incorporating feedback from the food bank and the Bay Area legal aid folks in advance of Spanish rollout.

Two views targeted:
- the screener (which is giving poor results for mixed status households)
- Our "soft screen" later in the application (which incorrectly states some language, including focusing on the applicant instead of the household).

**Comment by daguar** [comment]
P3/stretch goal for this week

**Comment by alanjosephwilliams** [comment]
PR #1020 addressed the soft screen. I'm going to open a new ticket to address the screener design work
