### ISSUE TITLE
Reduce # of blurry documents

### ISSUE THREAD

**Issue by norrishung** [codeforamerica/health#619]
We've heard from Marin that documents come through blurry. This is also something we've seen as we process docs.

I can think of a couple of design features and engineering features that we could implement to help alleviate this.

- [ ] Make thumbnails bigger in the document list view so that users have visual feedback of what they uploaded (and if its blurry).

- [ ] Ask the user to check the readability of documents before sending to county

- [ ] Implement some level of computer vision to check if there are readable characters in the document. If there aren't, provide feedback to the user to double-check the document.

**Comment by norrishung** [comment]
@daguar writing up my ideas from yesterdays slack convo.

**Comment by bensheldon** [comment]
Moved to https://github.com/codeforamerica/gcf-backend/issues/1538
