### ISSUE TITLE
The CalFresh User Journey

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/health#71]
This will build off Jake's 2013 work documenting the letters received by a SNAP enrollee, as well as the conversation we had with Diana from the food bank on Friday. However, this document will be more centered on the user experience throughout this process.

I'll be using Google Docs and draw.io for the first iteration, with a hope that it facilitates commentary and refinement.

Goals:
- Give the entire team a visual and written reference for understanding the entire journey through this social safety net services—from awareness to exit or stability—to clarify thinking about where friction happens, and where opportunities may exist.
- Give us and stakeholders an reference for understanding where our _current interventions_ fit into the experience of using obtaining, using and managing CalFresh. 
- Serve a reference for more public-facing documentation of the subject.

**Comment by alanjosephwilliams** [comment]
The first two components of this are saved in the dropbox. They are 1) the current internal business process as we understand it, agnostic of the medium an application is submitted and 2) the user experience flow of Clean itself. 

From here, we want similar assets that focus on experience of going from a) trauma -> awareness -> application, and b) use and management of benefits. Perhaps some others as well.

Draw.io's sharing feature is currently non-operable. I'll look into getting some customer support. I retain a strong preference for using Google Docs / Apps / Add-ons as a means to lower the barriers to participation from both members of the team and our partners. I'll probably stick with it—one day (hopefully) allowing linked experience maps that can be viewed and commented upon in browser tabs.

**Comment by alanjosephwilliams** [comment]
#### (SFHSA) CalFresh Internal Business Process Map

Comments, questions, fact-checking welcome and wanted.
![calfresh business process v2](https://cloud.githubusercontent.com/assets/2983464/5895328/9810ffc4-a4d0-11e4-9200-da3eeada1c52.jpg)

**Comment by alanjosephwilliams** [comment]
#### Clean v0.5 UX Flow

Comments, questions, fact-checking welcome and wanted.
**note this is only the views and actions the user experiences, for now.
![clean ux flow jan 2015 1](https://cloud.githubusercontent.com/assets/2983464/5895333/ba55d424-a4d0-11e4-87d0-09fb9575e23f.jpg)

**Comment by lippytak** [comment]
Any next steps on this. If not let's close and consider it DOOOONE!

**Comment by alanjosephwilliams** [comment]
I think a lot of the questions we have in the field to RM staff could add another dimension to this—but let's consider it done for now.
