### ISSUE TITLE
Ping CDSS lawyer to assess risk on sharing CalFresh case # + status

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/health#73]

**Comment by daguar** [comment]
Huge :+1: — if we can create a stupid simple "application status" API endpoint we can build a nice little tool on top of it for assistors (and clients themselves) _aaaand_ it's a great illustration of gov't serving as a good platform. (Status endpoints should be a thing.)

**Comment by alanjosephwilliams** [comment]
This is long done imagine, @lippytak?

**Comment by lippytak** [comment]
Done. Risk assessment: low.
