### ISSUE TITLE
January User Research Summmary

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/health#74]
Over the next few weeks, we want to measure the magnitude of pain points experienced by [our target population](https://github.com/codeforamerica/health/wiki) relative to one another. This will help us articulate our product goals for Q1 2014. As a guiding heuristic to start with, we want to know the *five most significant pain points* faced by a CalFresh recipients in San Francisco.

The plan will follow the basic outline used in our [November](https://docs.google.com/a/codeforamerica.org/document/d/19-KthLJBWUwOCKvh5lzU8_lZJXpuegHWgkFyQ7YtlFQ/edit) research.

**Comment by alanjosephwilliams** [comment]
*(this comment will be updated with links to new issues representing each thread of research, where specific research questions and tasks will be documented).*

#### Background 
In 2014, immersive research (both original and residual from the 2013 fellowship) enabled the team to  opportunistically develop interventions into the experience of obtaining and utilizing CalFresh benefits in San Francisco. With emerging government partnerships and institutional support from Code for America, the Health Lab is able take a more strategic and scalable approach to our mission 2015.  

Concretely, this ecosystem of support has empowered us to evaluate the problems and opportunities we’ve discovered to date solely on the potential **impact of our investment**— a function of the depth (significance) and breadth (potential scale) of human impact we can realize with the available energy our team can bring to bear upon each.

From this strategic framework, an ambitious but well-defined priority for the year ahead has emerged: to **meaningfully improve California’s SNAP participation rate**. California has the lowest participation rate of any state, and the City and County of San Francisco has the lowest participation rate of any county in the state. There are approximately 3 million eligible Californians that do not receive the benefits our country has deemed they are entitled. 

As a result, we are beginning 2015 with two priorities: scaling the the use of Clean and seeking more certainty about the universe and magnitude of user experience problems related to citizens obtaining, using and maintaining the CalFresh benefits. The document represents an evolving user research agenda to advance both of those priorities.

------------

#### Research Goals & Overview

Our research goals in January 2015 are threefold, in descending order of priority:

##### [ Medium Term ] Mapping the CalFresh Journey
 
To build a more complete  “map of the territory” when it comes to pain points encountered by those seeking, using, or maintaining CalFresh benefits. Understanding the entire set of pain points experience will allow us to more confidently assess the 80/20 opportunities—the 20% of pain points that cause 80% of the pain. As a team, we’ve been using a heuristic of the “top 5” pain points. This “map” will help guide our Quarter-time experimentation, and evaluate how impactful our current product offerings are compared to other opportunities. We are seeking a well articulated map by the end of January, and an increasing level of confidence and nuance across Q1 and Q2.

The majority of our research will be focus validating our assumptions about existing pain points, and attempting to assess their magnitude relative to one another, across the program.

##### [ Short Term ] Improving the experience and effectiveness of Clean

Our product priorities for January are squarely focused on Clean.  Specifically, we are designing and developing features that aim to increase the ease with which users can reliably schedule an eligibility interview and assess their case status.

A secondary priority of our research will probe the experience of applying and enrolling more deeply, ensuring imminent feature development is meeting the most significant user needs.	

##### [ Long Term ] Building the CalFresh User Group

In Q1 and Q2, we want to develop an understanding of the CalFresh journey with an ever-greater level of detail. Achieving that deep user experience knowledge will require that our conversations with users become routine, and that we conduct research with a growing number of diverse user segments. 

A tertiary goal of this first research sprint is to contribute to the development of the infrastructure we must build in order to scale our research and testing efforts.

To pursue these goals we are conducting a pair of research sprints in January, surveying and interviewing eligible and enrolled citizens, along with eligibility workers CBO staff and other involved in the delivery of CalFesh services.

The first sprint will begin in earnest on January 12th and will extend through January 16th. In advance of sprint planning on January 19th, we will evaluate which channels to continue running and which to alter or discontinue; and we will consider deployment of research through other channels.


--------------

#### Research Sprint 1: Segments & Channels 

##### 1235 Mission Patrons [ In-person intercepts ] 

*Goals*
- Develop a measure of on-site (and general) client satisfaction
- Gauge the distribution and magnitude pain points for in-person tasks

*Questions to be answered* 
- What is the distribution of tasks that clients have visited 1235 to accomplish?
- What share of visits are for tasks that could be completed via phone, text or email?
- Why do client elect to conduct business in-person that could be completed remotely?
- How many visits to 1235 or other agency offices does the average client make per month?
- What share of visits conclude with a completed task?
- What share of visits conclude with client satisfaction with service received?

*Approach*
 - Intercepts at 1235 
   - People: two people—an interview and a note-taker.
   - Compensation: $5 Visa gift cards in exchange for 5 minutes of time.

##### California Balance Users [ Textit survey ]

*Goals*
- Gauge the biggest pain points across the CalFresh experience for Balance users.
- Gauge the tech literacy and capabilities of Balance users—in part as a way to gauge the feasibility for Clean features dependent on MMS, data plans, and e-mail access.
- Understand effective modes of user acquisition for Balance.

*Questions to be answered*
- What is the biggest ongoing source of friction for people already enrolled and using CalFresh benefits?
Is finding a place to use benefits an issue for Balance users?
- How did Balance users learn about the service?
What share of Balance users have access to e-mail on their phone?

*Approach*
- Textit Survey
  - People: brief pair to implement, then managed by Alan.
  - Compensation: $5 Amazon Gift Code


##### EBT-Near-Me Users [ Ethnio survey ]

*Goals*
 - Understand what information EBT Near Me users are seeking
 - Gauge whether locating CalFresh retailers is a pain point.
 - Gauge whether there are other pain points around the use of CalFresh benefits.

*Questions to be answered*
 - Are users seeking information about CalFresh, GA ATMs, or neither?
 - How frequently do EBTNM visitors have problems using benefits?
 - How long have EBTNM users been enrolled in CalFresh?
 - How were EBTNM users acquired?

*Approach*
- Ethnio Survey
   - All multiple choice



#### San Francisco & Solano County Eligibility Workers [ Wufoo survey ]

*Goal*
- Understand what eligibility workers perceive to be the biggest source of friction for their clients.
- Understand where incentives are aligned to improve the client experience and the Eligibility Worker experience.
- Understand how we might be able to more effectively recruit and onboard EWs to serve as referrers of Clean & Balance.

*Questions to be answered*
- What do eligibility workers perceive to be the most effective form of outreach for eligible and not enrolled citizens?
- Do eligibility workers perceive clients to have similar pain points to those reported by clients themselves?
- Do eligibility workers experience friction from any interaction that also constitutes friction from the client’s perspective?
- Are eligibility workers in a position to recommend services or advise clients on how to obtain, use or manage their benefits more effectively?

*Approach*
- Distribute through trusted contacts at San Francisco and Solano Counties.
   - Explanatory e-mail and Wufoo Survey 
   - 5 to 7 questions

**Comment by alanjosephwilliams** [comment]
@lipptak

**Comment by alanjosephwilliams** [comment]
4 intercepts conducted on the afternoon of Monday 1/12/2015.

#88

**Comment by lippytak** [comment]
Jan is over. Maybe link to output and close this?

**Comment by alanjosephwilliams** [comment]
Research is being aggregated in the wiki:
https://github.com/codeforamerica/health/wiki
