### ISSUE TITLE
Goal setting Health Lab 2015

### ISSUE THREAD

**Issue by RebeccaCoelius** [codeforamerica/health#76]
Goals: 
1. Have a clear statement and team sense of what the most important problems are to work on 2015 within SNAP and Medicare as measured by depth and breadth of human impact, and level of effort.
2. Create public goals that are problem and project specific. Ex- enroll x people in SF County in CalFresh using Clean. Increase Balance usage by Y% in SF County.

**Comment by RebeccaCoelius** [comment]
Goal setting V1 on Jan 5th. Got to high level goal statement and identified need to identify top 5 most important problems in USABILITY of SNAP services. 
Alan creating V1 research plan. 
Rebecca + Alan mtg today to review, discuss next steps for Goal setting. 
Rebecca will schedule V2 of goal setting late Jan to review research results and set problem and project specific goals.

**Comment by lippytak** [comment]
Aiming for delivery goals (not personal growth) and trying to be as specific as possible *without* setting arbitrary benchmarks that will displace sound thinking around tradeoffs. cc @RebeccaCoelius feel free to weigh in or ship if you're comfortable with these.

Jake's 2015 goals:
1. **Healthy Team** = Maintain clarity and enthusiasm.
2. **Real Impact** = Get 1+ service to growth stage OR get to ~1,000 approved CalFresh applications/month by EOY.
3. **Keep Learning** = By EOY we should be working on 1+ NEW problem that we don't know exists today. Our exploratory work should uncover big opportunities for future Health FA work.

@daguar I really want your feedback on this. Are these the correct Big Three things for me to focus on? Do you think I can be more specific without being arbitrary? Do you agree with the magnitude for 2?

**Comment by alanjosephwilliams** [comment]
### Alan' 2015 Goals

#### Deep Empathy

##### Concrete Proxy: The entire team is talking to users at least every two weeks—ultimately ensuring we have clarity about what problems exist, their magnitude, and how we might address them.

Ways this will likely manifest:
- Building the CalFresh Feedback Group.
- Monthly user research efforts.
- A library of user stories.
- Compelling narratives about the experiences of the [people we serve](https://github.com/codeforamerica/health/wiki).

#### Community Building

##### Concrete Proxy: a Homepage that inspires the *right* people to contribute, and gives them the understanding and tools to do so—driving human impact through growth.

Ways this will likely manifest:
- Health homepage
- Product marketing assets & campaigns
- Articulating an analytical outreach approach—toward creating a "learning organization" of partners.
- Storytelling about our the people we serve, the people we work with, and the products we build.

#### User Success

##### Concrete Proxy: Users satisfied with the ease with which they can use our tools to accomplish important tasks—ensuring we maximize the impact for each of our users.

Ways this will likely manifest:
- First-class UX (speed/performance, interactions, copywriting and visual design) in Beta and Live products.
- Well articulated UX strategy (tradeoffs, hypotheses, and knowledge) for products Alpha and above.

**Comment by daguar** [comment]
*Ensure engineering quality in the Health Lab*
- Implement engineering practices (e.g., monitoring, automated testing) to achieve both velocity and quality of digital service delivery, all in a pragmatic way (i.e., increasing standards as projects move from prototype to alpha to beta to live, and based on the specific learning goals of a project sprint)
- Explicitly articulate tradeoffs in making these engineering decisions

*Facilitate low-friction technical collaboration*
- Implement engineering processes (e.g., clear documentation, PR and QA processes, continuous integration) that keep team collaboration fast and high-quality
- Develop and effectively support a Health Lab "standard stack" (e.g., Ruby, Sinatra or Rails, Heroku) to bolster overall team velocity

*Analytic clarity around projects*
- Ensure that all projects have clear hypotheses and theories of change
- Ensure project-specific metrics and other evidence-gathering strategies (e.g., user interviews) that effectively measure the success of specific projects against their stated theory of change
