### ISSUE TITLE
HIPAA 2015

### ISSUE THREAD

**Issue by RebeccaCoelius** [codeforamerica/health#77]

**Comment by RebeccaCoelius** [comment]
- calls w/ cities to communicate HIPAA resources 
- follow up w/ Aptible for Jan HIPAA training
- V2 CfA Policies and Procedures w/ Deven McGraw by end of Jan

**Comment by RebeccaCoelius** [comment]
Somerville call completed. Follow up: Will send me policies/procedures from covered entities, info how how to become HIE Mass endpoint, requested we consider using the NIST HIPAA toolkit: http://scap.nist.gov/hipaa/

**Comment by RebeccaCoelius** [comment]
Chas confirmed for Jan 22 training. 
Emailed Deven McGraw, awaiting working mtg times next week.

**Comment by daguar** [comment]
Hey @RebeccaCoelius — I've converted the bullet items above into clickable checkboxes for you. You can do that by using `[ ]` in GitHub Issues. For example:

- [ ] The beginning of this line was done with `- [ ]`

You can read more here: https://help.github.com/articles/writing-on-github/#task-lists 

(I worry this might be off-topic but figured I might as well comment on the issue where it's relevant!)

**Comment by RebeccaCoelius** [comment]
ooh, thanks @dave

**Comment by fureigh** [comment]
Way to osmote, @daguar! :)

**Comment by RebeccaCoelius** [comment]
call scheduled w/ Deven

**Comment by lippytak** [comment]
@rebeccacoelius done? Okay to close?

**Comment by RebeccaCoelius** [comment]
Nope I have two outstanding activities- finalize policies/procedures, and
onboard fellows to Aptible which is happening in 25 minutes.

On Monday, February 2, 2015, Jake Solomon <notifications@github.com> wrote:

> @rebeccacoelius <https://github.com/rebeccacoelius> done? Okay to close?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/77#issuecomment-72521118>
> .
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by RebeccaCoelius** [comment]
Fellows now all have access to Aptible. Policies + Procedures shared with Chas, discussing again + Privacy officer responsibilities Friday. 

Putting the Mass HIE follow up on ice until more info on Somverville.

**Comment by RebeccaCoelius** [comment]
Closing issue to turn into discrete tasks.
