### ISSUE TITLE
Health Homepage Content Strategy v1

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/health#87]

**Comment by alanjosephwilliams** [comment]
### Health Focus Homepage

#### "Hero Unit"

Rotating:
- [ ] Problem statement
- [ ] Product Demo 
- [ ] Theory of change summary
#### Health Focus Area Overview

- [ ] Mission
- [ ] Approach
- [ ] Rebecca's Talk

#### Health Lab

- [ ] Mission
- [ ] Approach
- [ ] Product Preview Cards
- [ ] Jake's Talk
- [ ] One other piece of relevant and fresher content to be updated manually.

##### Fellowships

- [ ] Overview 
- [ ] Fellowship Approach ("Build Alphas")
- [ ] Focus Area City Card — links to main city page

##### Product Residents (when we have them)

- [ ] Overview
- [ ] Product Cards

##### Who We Area

- [ ] Rebecca
- [ ] Jake
- [ ] Dave
- [ ] Alan
- [ ] Gabrielle
- [ ] Fellows
- [ ] Fellows
- [ ] Fellows

### Health Focus Product Page

#### Page Title (e.g. our products)

- [ ] concise overview of our products, our encompassing theory of change, and encouragement to the audience to get involved as appropriate.

##### Product
  - [ ] Product Name (e.g. "Clean")
  - [ ] One sentence description of the product (e.g. "A dead-simple application for CalFresh in California")
  - [ ] Visual Product Demo (e.g. GIF on click, video, etc.)
  - [ ] Product Metadata
     - [ ] Phase of Work Badge (with link to explanation of phases)
     - [ ] Current Geographic Extent
  - [ ] Product Theory of Change Paragraph 
  - [ ] Segmented Calls to Action 
     - [ ] Adopt (Decision Maker Level)
     - [ ] Promote (Staff Level)
     - [ ] Contribute (Analyst Level)
     - [ ] Lurk (Activist / Think Tank Level)

**Comment by RebeccaCoelius** [comment]
Not sure where you want this, but here are my V1 Sections. Please consider draft and comment/edit away. 
https://docs.google.com/a/codeforamerica.org/document/d/1CgjJTWqJkDh3xJbbfrhqqXWWWpAoFmwVveppya5vidI/edit?usp=sharing

**Comment by alanjosephwilliams** [comment]
Our actual content will evolve through each iteration, but this strategy has set our direction. We can refer back to this closed issue, and open new issues for specific content needs.
