### ISSUE TITLE
Staff meeting updates, 1/15/15

### ISSUE THREAD

**Issue by daguar** [codeforamerica/health#89]
Seems like a good process for staff mtg updates is to discuss on issues prior to the meeting and generate what we think the top 3 updates are.

I'd also suggest maybe we rotate who does it each week? (who wants to this week?) Then that person can make The Call about which 3 of the ones people've posted they'll say?

For me a few ideas for updates:
- Initial planning on expanding Clean (our apply-for-food-stamps-in-10-minutes app) to Contra Costa County
- Used Balance to run a survey of food stamp recipients' satisfaction + pain points with APPLYING FOR and MANAGING their benefits; got ~20 responses in 24 hours

Others?

cc @RebeccaCoelius @lippytak @alanjosephwilliams

**Comment by daguar** [comment]
Based on Slack, I'll do today's. Please throw down other ideas/discussion for the key bits!

**Comment by lippytak** [comment]
@daguar +1 to process/you should run today. Dumping ideas:
- $5k from Amazon + props to Jennifer
- Couple build week secrets in the works :)
- We OFFICIALLY have some HSA staff time so we can build the Clean funnel
- Request for help: Trying to help recruit for Will's #3 to lead strategy on program integration/'no wrong door' in CA

**Comment by RebeccaCoelius** [comment]
Must be said:
- Please welcome Alicia Rouault, who will be our Economic Development Advisor as we continue our search for the ED lead. She will be focused on supporting the ED Fellows, and supporting the start of 2016 City Recruitment. 
-Related, we are still recruiting for the Focus Area lead for Economic Development. Please continue to spread the word. Rebecca will send out info again after staff meeting.

**Comment by daguar** [comment]
@RebeccaCoelius, I feel like if we're covering ALL FOCUS AREA stuff, then maybe it makes sense for you to own that and for us 3 to rotate on Health Lab updates?

Just thinking through if we're constrained to 2-3 things, and we're covering (All Focus Areas) + (Health FA) + (Health Lab) that it might be too much.

What you think?
