### ISSUE TITLE
Help Will Recruit

### ISSUE THREAD

**Issue by RebeccaCoelius** [codeforamerica/health#90]
# Lead no wrong door strategy in California

The Director of Social Services in CA (Will Lightbourne) is looking for someone to lead an audacious "no wrong door" vision in CA, where any interaction with the safety net is an opportunity to gracefully enroll someone in all available services.

Concretely, the biggest opportunity is cross-enrollment for Medicaid and SNAP (food stamps). CA has the largest Medicaid and SNAP populations in the country AND active CMS waivers to make cross-enrollment easy, yet ~3 million Californians only get one of these services when they could get both. 

The other big opportunity area is integration across Foster care, CalWORKS, and Child care. These are the core supports for children and families in CA, and they don't work together. Transitioning families between programs can be a nightmare.

This is a soft power role so it takes a special person but the big levers here are strategy, policy, and technology. This person would build/lead California's strategy to integrate social services, discover/blow up key policy barriers, and use technology as leverage. The last piece is important here - current leadership knows technology is the multiplier and needs someone on the team with a strong perspective.

Here's a link to the role (warning: it's bland!) but frankly it doesn't reflect the significance and potential impact that the current leadership envisions. All of us on the Code for America Health Team have deep respect for Will and excitement over the potential for the right person.

**Comment by RebeccaCoelius** [comment]
-emailed to all staff and Fellows
-Dave requested in staff meeting
- requested help from Jen
- Rebecca sent to Truman Scholars and Fulbright Fellows network

**Comment by daguar** [comment]
I sent to the strongest node I have if CA health policy / health care / consulting.

**Comment by daguar** [comment]
Moving this out of "current sprint" back to "ready" —— if this has significant stuff this sprint, please make subissues or if it's pretty much done feel free to close.

**Comment by RebeccaCoelius** [comment]
Resent to Fuzz and CfA staff+Fellows list.
Jake will email Will and say that while we will keep trying, an initial effort resulted in no applicants willing to work full time in Sacramento.
