### ISSUE TITLE
Health CodeAcross

### ISSUE THREAD

**Issue by RebeccaCoelius** [codeforamerica/health#96]
The Communities Team would like to have a health related challenge at City Camp 2015 taking place in late February.

**Comment by RebeccaCoelius** [comment]
Will draft ideas, discuss with Alan this week.

**Comment by daguar** [comment]
Is this CityCamp or CodeAcross? (ugh, names.) Just seems like the timing is for the latter?

**Comment by daguar** [comment]
edited name after confirming this is for CodeAcross

**Comment by RebeccaCoelius** [comment]
thanks @daguar
