### ISSUE TITLE
Finalize and distribute survey of Eligibility Workers

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/health#98]
First pass at questions for a survey of Eligibility Workers in San Francisco and Solano Counties. 

As with all of our January research, our goal is to get a more comprehensive understanding of the pain points experienced by our community as they obtain and use CalFresh, and we want to be able to evaluate the significance of those problems against one another—with the ultimate goal of making sure the projects and features we invest in are the highest and best use of our time.

Thus, for this survey of Eligibility Workers, we want to get their perspective on pain points in the application process, and in particular, their understanding of "breaks" in the funnel. Our research over the past two weeks has reinforced our understanding that the process of applying is far more dense with problems than the ongoing management and use of benefits. We should also be open to new information and problems unique to their day to day work.

- What is the biggest challenge you face in your job?
- What is the biggest challenge you face when interacting with clients?
- What share of applications you handle qualify or likely qualify for SNAP?
- What share of applications you handle successfully schedule and show up for (or conduct via phone) an eligibility interview?
- Of the eligibility interviews you conduct, what share are in person? What share are over the phone?
- What share of applications you handle submit all necessary verification documents before or as part of the eligibility interview?

cc @lippytak @daguar

**Comment by alanjosephwilliams** [comment]
- [ ] finalize questions (evaluating against our goals)
- [ ] set up survey via Wufoo
- [ ] determine whether or not any incentive is possible (restrictions on gifts?)
- [ ] give advance notice to Angela and Tiana that we're looking for their help distributing
- [ ] Make sure well-written e-mail with link to the survey hits inboxes at the right time on Monday or Tuesday morning (1/26 or 1/27) if not before.

**Comment by lippytak** [comment]
@ajw :+1: LMK if/when you want feedback and on what. A reminder of the goals is always helpful for context. I'm happy to do my best to circulate the survey whenever.

**Comment by alanjosephwilliams** [comment]
@lippytak I think we will shoot for finalized over the weekend, and shipping on Monday.

**Comment by alanjosephwilliams** [comment]
@lippytak I am letting you know that I want some feedback. Let's circulate ASAP—let me know what you need. Goals are more explicitly articulated above—this is squarely within our broader January research push.

https://codeforamerica.wufoo.com/forms/eligibillity-worker-feedback-survey/

![eligibillity worker feedback survey](https://cloud.githubusercontent.com/assets/2983464/5895796/533af8ce-a4de-11e4-8c08-b82d932d2632.png)

**Comment by lippytak** [comment]
Rad. Happy to get this out today. Just be warned people may freak out and not want to circulate to EWs but we should try.

As always here are my thoughts but I know you've put more thought into this than I so feel free to ignore/incorporate whatever you think is best:
- Consider asking folks what they think are the biggest pain points in the app process
- Let people expand with 'other or 'why' follow up questions on the specific pain points (scheduling interviews, no-shows, verification docs, not actually eligible)
- I think the 'challenge when interacting with clients' question will be hard to answer. What sorts of responses do you imagine?
- Not sure what we're getting out of the % phone interview question
- Ask their County to understand variance of bottlenecks
- Optional phone for follow up call
- Optional email to get a summary of results

**Comment by alanjosephwilliams** [comment]
Can you elaborate on "ask their County to understand variance of
bottlenecks"?

On Mon, Jan 26, 2015 at 6:52 AM, Jake Solomon <notifications@github.com>
wrote:

> Rad. Happy to get this out today. Just be warned people may freak out and
> not want to circulate to EWs but we should try.
>
> As always here are my thoughts but I know you've put more thought into
> this than I so feel free to ignore/incorporate whatever you think is best:
>
>    - Consider asking folks what they think are the biggest pain points in
>    the app process
>    - Let people expand with 'other or 'why' follow up questions on the
>    specific pain points (scheduling interviews, no-shows, verification docs,
>    not actually eligible)
>    - I think the 'challenge when interacting with clients' question will
>    be hard to answer. What sorts of responses do you imagine?
>    - Not sure what we're getting out of the % phone interview question
>    - Ask their County to understand variance of bottlenecks
>    - Optional phone for follow up call
>    - Optional email to get a summary of results
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/98#issuecomment-71471882>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by alanjosephwilliams** [comment]
Updated. I either agree in principle or in tactics with most of your suggestions.
https://codeforamerica.wufoo.com/forms/eligibillity-worker-feedback-survey/

**Comment by alanjosephwilliams** [comment]
![eligibillity worker feedback survey copy](https://cloud.githubusercontent.com/assets/2983464/5905880/394a6eda-a548-11e4-8b92-09a4f51f8e45.png)

**Comment by alanjosephwilliams** [comment]
@lippytak want to circle back on this today?

**Comment by lippytak** [comment]
Tomorrow OK? Calendar mostly open either block out 30 or just start the
convo!

**Comment by alanjosephwilliams** [comment]
Booked

On Thu, Jan 29, 2015 at 3:54 PM, Jake Solomon <notifications@github.com>
wrote:

> Tomorrow OK? Calendar mostly open either block out 30 or just start the
> convo!
>
> On Thu, Jan 29, 2015 at 3:39 PM, Alan Joseph Williams <
> notifications@github.com> wrote:
>
> > @lippytak <https://github.com/lippytak> want to circle back on this
> today?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/codeforamerica/health/issues/98#issuecomment-72127192>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/98#issuecomment-72128878>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by lippytak** [comment]
Shipped! Close this one?

:+1: to this first attempt to get the EW perspective!

**Comment by alanjosephwilliams** [comment]
Closed—big ups @lippytak
