### ISSUE TITLE
Health Page v1 Pull Request for review by Marketing

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/health#99]
By the end of the sprint, we'll submit a PR for review by the marketing team. It should be a narrowly tailored set of content, since we want something that is ready for public consumption.

**Comment by RebeccaCoelius** [comment]
@alanjosephwilliams As discussed on Slack, I want this Health FA "wrapper" content on the Lab product page for V1. I will focus on this content for the sprint.

Health Focus Area Overview

 Mission
 Approach
 Rebecca's Talk
 Anatomy / How pieces fit (specifically Health Lab)

**Comment by alanjosephwilliams** [comment]
Sounds good @RebeccaCoelius, this is definitely the right place to discuss requirements.

**Comment by RebeccaCoelius** [comment]
@alanjosephwilliams am I missing an issue? per Slack you are reviewing with David today but I don't see any of the content in progress here or in the original Health Home issue

**Comment by alanjosephwilliams** [comment]
Ah slight misunderstanding—David and I are pairing on the development of
modules that can be contributed back to the pattern library—so its mostly
working session around workflows, naming conventions, and stylistic
approaches. For example, Afterwards we'll have a good "product card"
HTML/CSS module that we can apply the variety of product-specific content
to.

On Mon, Jan 26, 2015 at 10:47 AM, RebeccaCoelius <notifications@github.com>
wrote:

> @alanjosephwilliams <https://github.com/alanjosephwilliams> am I missing
> an issue? per Slack you are reviewing with David today but I don't see any
> of the content in progress here or in the original Health Home issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/99#issuecomment-71514184>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by alanjosephwilliams** [comment]
This very well might not happen by the end of the sprint due to The Plague. We've got a good design, and we've been well on-boarded into the process for contributing back to the pattern library. We are now in implementation phase.

**Comment by alanjosephwilliams** [comment]
After discussion in Retro on Friday, we are changing our approach on the Homepage work.

We had enumerated 4 use cases for this project—2 product marketing use cases, and 2 general FA use cases. The product marketing use cases were upping the complexity and time requirements of the project—particularly in the development of new, generalized patterns to be contributed back to the site's pattern library. As a result, we are going to table the CfA website as a channel for product marketing for the time being.

The Homepage v1 scope of work is now limited to providing a good v1 for the general Focus Area needs that @RebeccaCoelius has. We can use completely off-the-shelf components and focus our time on getting the content and media right.

**Comment by alanjosephwilliams** [comment]
We have the layout and components of v1 on a branch called "health-homepage". The screenshot attached shows the work done to date. In advance of our meeting to review on Thursday, we'll need to:
- continue to tailor and improve our final v1 messaging and copywriting
- identify the idea pull quote from a partner, and secure a headshot for them.
- identify a header image that fits the page well and reinforces our messaging.
- identify three media assets to represent our government, non-profit, and institutional partners respectively.
- identify any missing content or other gaps.
![homepage_v1_for_review](https://cloud.githubusercontent.com/assets/2983464/5996677/d9291702-aa62-11e4-9d9a-f03853b8c717.png)

**Comment by RebeccaCoelius** [comment]
This generally makes sense to me esp since we aren't in product marketing
mode right now, but I want to be we aren't losing ALL descriptions of the
Health Lab projects since this is where your product marketing use cases
overlapped with my own. A basic description of what we are working on, why,
theory of change, and status for each project/product is necessary to meet
my use cases.

Rebecca Coelius, MD
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by alanjosephwilliams** [comment]
That sounds good to me. I suggest as a rule of thumb we only include product names and descriptions (theories of change) for those projects that are "alpha" or above—which as of today includes Balance, Clean, Connect, and EBT Near Me.

**Comment by RebeccaCoelius** [comment]
Absolutely, that was my assumption but thank you for making it clear.

Rebecca Coelius, MD
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by RebeccaCoelius** [comment]
@alanjosephwilliams where should I make comments on Content?

**Comment by alanjosephwilliams** [comment]
You can either make them here, or if you want, I could pull out all of the
content into a Google Doc that we could edit. Whatever you prefer!

On Mon, Feb 2, 2015 at 1:28 PM, RebeccaCoelius <notifications@github.com>
wrote:

> @alanjosephwilliams <https://github.com/alanjosephwilliams> where should
> I make comments on Content?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/99#issuecomment-72541579>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by RebeccaCoelius** [comment]
need to update this page when we do PR for Homepage so language consistent. http://www.codeforamerica.org/our-work/focus-areas/

**Comment by alanjosephwilliams** [comment]
Updated homepage layout and copywriting—matches the Google Doc found here
https://docs.google.com/a/codeforamerica.org/document/d/1Ma95E_WxxjdFilEjdB1tLm8ENuf3O-P9zRwWp7j2t5o/edit
![homepage_v1 1_for_review](https://cloud.githubusercontent.com/assets/2983464/6053157/94eac75e-ac90-11e4-81c8-08d677e7b5d3.png)

**Comment by alanjosephwilliams** [comment]
Let's make sure all content is in line with the Style Guide:
https://docs.google.com/a/codeforamerica.org/document/d/1d4lhm_8kmTQ4nXzOPxmlOmSdyt6C0OV1LY2TfdKL9sU/edit

**Comment by alanjosephwilliams** [comment]
Notes from our 2/5/2015 meeting w/ JA & David.

- "Seperateness"
- Allusions to other work—Let's make sure we link to the Fellowship page
  - Let's make sure that on the Fellowship page, we communicate clearly about product outcomes, and how they fit with Product Residencies and even more mature work via the Health Lab
- What are we comfortable with regarding the Fellowship Outcomes
- Let's duplicate content about how FAs work on both FA umbrella p age and the Health FA page--let's work on cutting our first "Our Approach" section.
- Move toward "Code for America" in places we use "we" and "our".
- Let's think about moving away from "structure" and move towards "How we work towards outcomes". Fellowships move to something like "Alphas". Residencies are more "Maturing Products" and Lab is more "Building and Scaling". Maybe a tripartite section that reflects these, up toward the top,
- There is also everything else we do—making gov't easy to copy, etc. 
- One contact route via the full team enumeration.
- Logos, other symbols of our existing partners as we ditch the fellowship cards.
- Up the name of Leo, downsize the source
- Video down below with contact—maybe?

**Comment by lippytak** [comment]
Done?

**Comment by RebeccaCoelius** [comment]
Yes

On Saturday, February 14, 2015, Jake Solomon <notifications@github.com>
wrote:

> Done?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/health/issues/99#issuecomment-74398369>
> .
>


-- 
Rebecca Coelius, MD
Director of Health
Code for America
415 298 2872
LinkedIn <http://www.linkedin.com/in/rebeccacoelius>
Twitter <http://twitter.com/#!/RebeccaCoelius>

**Comment by lippytak** [comment]
yay!
